// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Returns an access token in the response body and sets\nthe refresh token as an httpOnly cookie scoped to /auth.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log in with email and password",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Log out of the current session",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Reads the refresh token from the httpOnly cookie, rotates\nit, and returns a new access token plus a new refresh\ncookie. Reusing an already-rotated refresh token revokes\nits entire token family and forces a fresh login.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Exchange the refresh token cookie for a new access/refresh token pair",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new account",
                "parameters": [
                    {
                        "description": "Register request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    }
                }
            }
        },
        "/moments": {
            "get": {
                "description": "The authenticated user's personal archive timeline, newest occurrence first",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "moments"
                ],
                "summary": "List moments",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Moments per page (default 20, max 100)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_ListMomentsResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new manually-captured Moment for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "moments"
                ],
                "summary": "Capture a new moment",
                "parameters": [
                    {
                        "description": "Create moment request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.CreateMomentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_MomentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    }
                }
            }
        },
        "/moments/search": {
            "get": {
                "description": "Global text Search over the authenticated user's own Moments",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "moments"
                ],
                "summary": "Search moments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search text",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Moments per page (default 20, max 100)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_ListMomentsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    }
                }
            }
        },
        "/moments/{id}": {
            "get": {
                "description": "Get a single Moment belonging to the authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "moments"
                ],
                "summary": "Get a moment by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Moment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_MomentResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    }
                }
            },
            "put": {
                "description": "Full-representation update of a Moment owned by the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "moments"
                ],
                "summary": "Update a moment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Moment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update moment request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.UpdateMomentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_MomentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    }
                }
            },
            "delete": {
                "description": "Soft-deletes a Moment owned by the authenticated user",
                "tags": [
                    "moments"
                ],
                "summary": "Delete a moment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Moment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    }
                }
            }
        },
        "/moments/{id}/images": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "moments"
                ],
                "summary": "List images for a moment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Moment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-array_github_com_ngodingvareng_memoria_internal_delivery_rest_dto_MomentImageResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "moments"
                ],
                "summary": "Upload an image for a moment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Moment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Image file",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_MomentImageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    }
                }
            }
        },
        "/moments/{id}/images/{imageId}": {
            "delete": {
                "tags": [
                    "moments"
                ],
                "summary": "Delete a moment image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Moment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Image ID",
                        "name": "imageId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/threads": {
            "get": {
                "description": "Search and filter the authenticated user's threads, with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "threads"
                ],
                "summary": "Search / list threads",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by name (partial, case-insensitive)",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by whether the thread is archived",
                        "name": "archived",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Threads per page (default 20, max 100)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_SearchThreadsResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new thread for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "threads"
                ],
                "summary": "Create a new thread",
                "parameters": [
                    {
                        "description": "Create thread request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.CreateThreadRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_ThreadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    }
                }
            }
        },
        "/threads/{id}": {
            "get": {
                "description": "Get a single thread belonging to the authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "threads"
                ],
                "summary": "Get an thread by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Thread ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_ThreadResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    }
                }
            },
            "put": {
                "description": "Full-representation update of an thread owned by the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "threads"
                ],
                "summary": "Update an thread",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Thread ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update thread request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.UpdateThreadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_ThreadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    }
                }
            },
            "delete": {
                "description": "Soft-deletes an thread owned by the authenticated user",
                "tags": [
                    "threads"
                ],
                "summary": "Delete an thread",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Thread ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    }
                }
            }
        },
        "/threads/{id}/images": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "threads"
                ],
                "summary": "List images for an thread",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Thread ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-array_github_com_ngodingvareng_memoria_internal_delivery_rest_dto_ThreadImageResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "threads"
                ],
                "summary": "Upload an image for an thread",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Thread ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Image file",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_ThreadImageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any"
                        }
                    }
                }
            }
        },
        "/threads/{id}/images/{imageId}": {
            "delete": {
                "tags": [
                    "threads"
                ],
                "summary": "Delete an thread image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Thread ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Image ID",
                        "name": "imageId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/threads/{id}/moments": {
            "get": {
                "description": "A single Thread's browsable timeline, newest occurrence first",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "moments"
                ],
                "summary": "List a thread's moments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Thread ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Moments per page (default 20, max 100)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_ListMomentsResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.CreateMomentRequest": {
            "type": "object",
            "required": [
                "occurred_at"
            ],
            "properties": {
                "client_id": {
                    "description": "ClientID lets an offline-captured Moment be synced twice (e.g. a\nflaky retry) without creating a duplicate.",
                    "type": "string"
                },
                "color_hex": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number",
                    "maximum": 90,
                    "minimum": -90
                },
                "longitude": {
                    "type": "number",
                    "maximum": 180,
                    "minimum": -180
                },
                "note": {
                    "type": "string",
                    "maxLength": 10000
                },
                "occurred_at": {
                    "type": "string",
                    "example": "2026-08-04T14:30:00+09:00"
                },
                "occurred_utc_offset_minutes": {
                    "description": "The local UTC offset in effect where it happened, in minutes.\nOmitted means UTC (0) — see the moments.occurred_utc_offset_minutes\ncolumn comment for the ±1020 (±17h) bound.",
                    "type": "integer",
                    "maximum": 1020,
                    "minimum": -1020,
                    "example": 540
                },
                "origin": {
                    "description": "Origin defaults to \"manual\" server-side when omitted. \"commitment\"\nis deliberately not accepted here — Commitment-generated Moments\nnever go through this path (FEATURES.md).",
                    "type": "string",
                    "enum": [
                        "manual",
                        "import"
                    ]
                },
                "place_name": {
                    "type": "string",
                    "maxLength": 255
                },
                "recorded_at": {
                    "description": "RecordedAt is for offline sync only: the true local time the user\nactually wrote the Moment down. Omitted means \"now\" (ordinary\nonline capture) — see FEATURES.md's Time table.",
                    "type": "string"
                },
                "thread_id": {
                    "type": "string"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.CreateThreadRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "color_hex": {
                    "type": "string",
                    "example": "#FF5733"
                },
                "description": {
                    "type": "string",
                    "maxLength": 2000,
                    "example": "Push-ups and a run every weekday morning"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "Morning workout"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.ListMomentsResponse": {
            "type": "object",
            "properties": {
                "moments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.MomentResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.PaginationResponse"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "budi@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "correct horse battery staple"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "AccessToken is meant to be held in memory on the frontend (not\nlocalStorage) and sent via the Authorization: Bearer header.",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIs..."
                },
                "expires_in": {
                    "description": "ExpiresIn is in seconds, so the frontend can schedule a silent\nrefresh shortly before the access token actually expires.",
                    "type": "integer",
                    "example": 900
                },
                "user": {
                    "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.UserResponse"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.MomentImageResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "url": {
                    "type": "string",
                    "example": "https://storage.example.com/moments/.../abc123.jpg?X-Amz-..."
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.MomentResponse": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "color_hex": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-08-04T14:35:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "note": {
                    "type": "string"
                },
                "occurred_at": {
                    "description": "OccurredAt is reconstructed from occurred_local +\noccurred_utc_offset_minutes, so it round-trips exactly the wall\ntime and offset the Moment was captured with.",
                    "type": "string",
                    "example": "2026-08-04T14:30:00+09:00"
                },
                "occurred_utc_offset_minutes": {
                    "type": "integer",
                    "example": 540
                },
                "origin": {
                    "type": "string",
                    "example": "manual"
                },
                "place_name": {
                    "type": "string"
                },
                "recorded_at": {
                    "type": "string",
                    "example": "2026-08-04T14:35:00Z"
                },
                "settling_time_seconds": {
                    "type": "integer",
                    "example": 300
                },
                "thread_id": {
                    "type": "string",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-08-04T14:35:00Z"
                },
                "user_id": {
                    "type": "string",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.PaginationResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "page_size": {
                    "type": "integer",
                    "example": 20
                },
                "total": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "budi@example.com"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "Budi Santoso"
                },
                "password": {
                    "description": "scrypt hashes the whole password with no truncation. max=256 is\njust a generous sane upper bound (prevents someone posting a\nmulti-KB \"password\" that'd waste CPU/memory on the scrypt KDF\nfor no real security benefit).",
                    "type": "string",
                    "maxLength": 256,
                    "minLength": 8,
                    "example": "correct horse battery staple"
                },
                "username": {
                    "description": "Matches users.chk_users_username_format — lowercase letters,\ndigits, underscore, and dot only. Stored as typed, matched\ncase-insensitively for uniqueness. See the \"username\" custom\nvalidator registered in AuthHandler.",
                    "type": "string",
                    "example": "budisantoso"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.SearchThreadsResponse": {
            "type": "object",
            "properties": {
                "pagination": {
                    "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.PaginationResponse"
                },
                "threads": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.ThreadResponse"
                    }
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.ThreadImageResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "url": {
                    "type": "string",
                    "example": "https://storage.example.com/threads/.../abc123.jpg?X-Amz-..."
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.ThreadResponse": {
            "type": "object",
            "properties": {
                "archived_at": {
                    "type": "string",
                    "example": "2026-07-20T10:00:00Z"
                },
                "circle_id": {
                    "type": "string",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "color_hex": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-07-20T10:00:00Z"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "name": {
                    "type": "string",
                    "example": "Morning workout"
                },
                "sort_order": {
                    "type": "integer",
                    "example": 0
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-07-20T10:00:00Z"
                },
                "user_id": {
                    "type": "string",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.UpdateMomentRequest": {
            "type": "object",
            "required": [
                "occurred_at"
            ],
            "properties": {
                "color_hex": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number",
                    "maximum": 90,
                    "minimum": -90
                },
                "longitude": {
                    "type": "number",
                    "maximum": 180,
                    "minimum": -180
                },
                "note": {
                    "type": "string",
                    "maxLength": 10000
                },
                "occurred_at": {
                    "type": "string",
                    "example": "2026-08-04T14:30:00+09:00"
                },
                "occurred_utc_offset_minutes": {
                    "type": "integer",
                    "maximum": 1020,
                    "minimum": -1020,
                    "example": 540
                },
                "place_name": {
                    "type": "string",
                    "maxLength": 255
                },
                "thread_id": {
                    "type": "string"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.UpdateThreadRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "color_hex": {
                    "type": "string",
                    "example": "#FF5733"
                },
                "description": {
                    "type": "string",
                    "maxLength": 2000,
                    "example": "Push-ups and a run every weekday morning"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "Morning workout"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-07-20T10:00:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "budi@example.com"
                },
                "email_verified": {
                    "type": "boolean",
                    "example": false
                },
                "id": {
                    "type": "string",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "name": {
                    "type": "string",
                    "example": "Budi Santoso"
                },
                "username": {
                    "type": "string",
                    "example": "budisantoso"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-any": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {},
                "errors": {},
                "message": {
                    "type": "string",
                    "example": "Success"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-array_github_com_ngodingvareng_memoria_internal_delivery_rest_dto_MomentImageResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.MomentImageResponse"
                    }
                },
                "errors": {},
                "message": {
                    "type": "string",
                    "example": "Success"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-array_github_com_ngodingvareng_memoria_internal_delivery_rest_dto_ThreadImageResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.ThreadImageResponse"
                    }
                },
                "errors": {},
                "message": {
                    "type": "string",
                    "example": "Success"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_ListMomentsResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.ListMomentsResponse"
                },
                "errors": {},
                "message": {
                    "type": "string",
                    "example": "Success"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_LoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.LoginResponse"
                },
                "errors": {},
                "message": {
                    "type": "string",
                    "example": "Success"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_MomentImageResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.MomentImageResponse"
                },
                "errors": {},
                "message": {
                    "type": "string",
                    "example": "Success"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_MomentResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.MomentResponse"
                },
                "errors": {},
                "message": {
                    "type": "string",
                    "example": "Success"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_SearchThreadsResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.SearchThreadsResponse"
                },
                "errors": {},
                "message": {
                    "type": "string",
                    "example": "Success"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_ThreadImageResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.ThreadImageResponse"
                },
                "errors": {},
                "message": {
                    "type": "string",
                    "example": "Success"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_ThreadResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.ThreadResponse"
                },
                "errors": {},
                "message": {
                    "type": "string",
                    "example": "Success"
                }
            }
        },
        "github_com_ngodingvareng_memoria_internal_delivery_rest_dto.WebResponse-github_com_ngodingvareng_memoria_internal_delivery_rest_dto_UserResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/github_com_ngodingvareng_memoria_internal_delivery_rest_dto.UserResponse"
                },
                "errors": {},
                "message": {
                    "type": "string",
                    "example": "Success"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Book API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
