-- name: CreateCircleUsernameInvite :one
-- The held-back direct add: written only when the target's
-- circle_invite_policy requires their confirmation. A direct add that
-- clears the policy goes straight to AddCircleMembers instead and
-- produces no row here.
INSERT INTO circle_invites(circle_id, invited_by_user_id, kind, invitee_user_id, expires_at)
VALUES (
    sqlc.arg(circle_id),
    sqlc.arg(invited_by_user_id),
    'username',
    sqlc.arg(invitee_user_id),
    sqlc.arg(expires_at)
)
RETURNING *;

-- name: GetPendingCircleUsernameInvite :one
-- Backs the "already invited" check before writing a new one, so the
-- caller can report it rather than tripping
-- uq_circle_invites_pending_username. Treats a lapsed row as gone even
-- if nothing has stamped it 'expired' yet — see
-- ListPendingCircleInvitesByInviteeID.
SELECT *
FROM circle_invites
WHERE circle_id = sqlc.arg(circle_id)
    AND invitee_user_id = sqlc.arg(invitee_user_id)
    AND kind = 'username'
    AND status = 'pending'
    AND (expires_at IS NULL OR expires_at > NOW());

-- name: ListPendingCircleInvitesByInviteeID :many
-- The user's incoming invites. Expiry is evaluated here rather than
-- swept by a job: nothing sets status = 'expired' on a schedule, so a
-- lapsed row must never be treated as live on the strength of its
-- status column alone.
SELECT *
FROM circle_invites
WHERE invitee_user_id = sqlc.arg(invitee_user_id)
    AND kind = 'username'
    AND status = 'pending'
    AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC;

-- name: AcceptCircleUsernameInvite :one
-- Returns no row if the invite was already answered, revoked, or has
-- lapsed — the caller must treat that as a failed accept and not add the
-- member. Membership itself is a separate AddCircleMembers call in the
-- same transaction.
UPDATE circle_invites
SET status = 'accepted',
    responded_at = NOW()
WHERE id = sqlc.arg(id)
    AND invitee_user_id = sqlc.arg(invitee_user_id)
    AND kind = 'username'
    AND status = 'pending'
    AND (expires_at IS NULL OR expires_at > NOW())
RETURNING *;

-- name: DeclineCircleUsernameInvite :one
UPDATE circle_invites
SET status = 'declined',
    responded_at = NOW()
WHERE id = sqlc.arg(id)
    AND invitee_user_id = sqlc.arg(invitee_user_id)
    AND kind = 'username'
    AND status = 'pending'
RETURNING *;

-- name: RevokeCircleUsernameInvite :one
-- The inviting side withdrawing an invite the recipient has not answered.
UPDATE circle_invites
SET status = 'revoked',
    responded_at = NOW()
WHERE id = sqlc.arg(id)
    AND circle_id = sqlc.arg(circle_id)
    AND kind = 'username'
    AND status = 'pending'
RETURNING *;


-- ---------------------------------------------------------
-- Invite links
-- ---------------------------------------------------------

-- name: RevokeActiveCircleInviteLink :one
-- Rotation, step one. Must run in the same transaction as
-- CreateCircleInviteLink: uq_circle_invites_active_link permits only one
-- live link per Circle, so the insert fails unless this ran first. That
-- is the point — "the old link stops working" is enforced by the schema,
-- not by the caller remembering.
--
-- Returns no row when the Circle has no link yet, which is the ordinary
-- first-generation case and not an error.
UPDATE circle_invites
SET status = 'revoked',
    responded_at = NOW()
WHERE circle_id = sqlc.arg(circle_id)
    AND kind = 'link'
    AND status = 'active'
RETURNING *;

-- name: CreateCircleInviteLink :one
-- token_hash is the SHA-256 of a random string generated by the caller;
-- the raw token is returned to the user once and never stored. Links
-- carry no expiry and no usage limit by design (FEATURES.md, Circle
-- Invite) — rotation is the only way one ever stops working.
INSERT INTO circle_invites(circle_id, invited_by_user_id, kind, token_hash, requires_approval, status)
VALUES (
    sqlc.arg(circle_id),
    sqlc.arg(invited_by_user_id),
    'link',
    sqlc.arg(token_hash),
    sqlc.arg(requires_approval),
    'active'
)
RETURNING *;

-- name: GetActiveCircleInviteLinkByCircleID :one
-- The Circle's link as shown in its settings. Only token_hash is stored,
-- so the shareable URL has to be reconstructed from the raw token the
-- generating call returned — it cannot be recovered later, and a member
-- who lost it regenerates instead.
SELECT *
FROM circle_invites
WHERE circle_id = sqlc.arg(circle_id)
    AND kind = 'link'
    AND status = 'active';

-- name: GetActiveCircleInviteLinkByTokenHash :one
-- The join path: resolves a followed link to its Circle. A rotated link
-- is 'revoked' and matches nothing here.
SELECT *
FROM circle_invites
WHERE token_hash = sqlc.arg(token_hash)
    AND kind = 'link'
    AND status = 'active';

-- name: SetCircleInviteLinkRequiresApproval :one
-- Toggling the approval requirement on the live link, without rotating
-- it. Requests already open stay open either way; turning approval off
-- does not admit them retroactively.
UPDATE circle_invites
SET requires_approval = sqlc.arg(requires_approval)
WHERE circle_id = sqlc.arg(circle_id)
    AND kind = 'link'
    AND status = 'active'
RETURNING *;
