-- name: CreateCommittedMoment :one
-- Auto-generated by the scheduler worker when a Commitment fires.
-- occurred_at is set equal to due_at at creation time.
-- ON CONFLICT mirrors uq_moments_thread_id_due_at exactly, so a
-- duplicate generation attempt (e.g. two worker instances racing) is
-- silently ignored instead of erroring.
INSERT INTO moments(
    thread_id,
    commitment_id,
    status,
    due_at,
    occurred_at
) VALUES (
    sqlc.arg(thread_id),
    sqlc.arg(commitment_id),
    'due',
    sqlc.arg(due_at),
    sqlc.arg(due_at)
)
ON CONFLICT(thread_id, due_at) WHERE deleted_at IS NULL DO NOTHING
    RETURNING *;

-- name: CreateManualMoment :one
-- A Moment the user captured themselves. occurred_at may be backdated;
-- due_at/commitment_id stay NULL because nothing was ever owed.
-- Manual Moments carry no meaningful state — see the note on
-- moments.status in TODO.md.
INSERT INTO moments(
    thread_id,
    status,
    occurred_at,
    content,
    color_hex
) VALUES (
    sqlc.arg(thread_id),
    sqlc.arg(status),
    sqlc.arg(occurred_at),
    sqlc.narg(content),
    sqlc.narg(color_hex)
)
RETURNING *;

-- name: GetMomentByID :one
SELECT * FROM moments
WHERE id = sqlc.arg(id) AND deleted_at IS NULL;

-- name: ListMomentsByThreadID :many
-- Timeline/history view for one Thread, newest occurrence first.
SELECT * FROM moments
WHERE thread_id = sqlc.arg(thread_id) AND deleted_at IS NULL
ORDER BY occurred_at DESC
LIMIT sqlc.arg(page_limit)
OFFSET sqlc.arg(page_offset);

-- name: RecordMoment :one
-- The user answers a due Moment, optionally attaching content/color.
-- "WHERE status = 'due'" avoids a race against the timeout job flipping
-- the same row at the same time.
UPDATE moments
SET status = sqlc.arg(status),
    captured_at = NOW(),
    content = sqlc.narg(content),
    color_hex = sqlc.narg(color_hex),
    updated_at = NOW()
WHERE id = sqlc.arg(id) AND status = 'due'
    RETURNING *;

-- name: UpdateMomentContent :one
-- Edit a Moment's content/color after the fact, without touching
-- status/captured_at. A Moment is never final — see FEATURES.md,
-- "Moments are never final".
UPDATE moments
SET content = sqlc.narg(content),
    color_hex = sqlc.narg(color_hex),
    updated_at = NOW()
WHERE id = sqlc.arg(id)
    AND deleted_at IS NULL
    RETURNING *;

-- name: ListDueMomentsPastDeadline :many
-- Candidates the timeout worker is about to flip to 'missed'; useful for
-- logging and for the opt-in "Moment missed" notification. Mirrors the
-- condition in MarkOverdueMomentsAsMissed below.
SELECT moments.*
FROM moments
    JOIN threads ON threads.id = moments.thread_id
WHERE moments.status = 'due'
    AND moments.deleted_at IS NULL
    AND threads.deleted_at IS NULL
    AND threads.confirmation_timeout_minutes IS NOT NULL
    AND moments.due_at
    + (threads.confirmation_timeout_minutes || ' minutes')::interval < NOW();

-- name: MarkOverdueMomentsAsMissed :execrows
-- The timeout job itself: bulk-flip every 'due' Moment whose confirmation
-- window (due_at + threads.confirmation_timeout_minutes) has closed.
-- Run this on a schedule (e.g. every minute).
UPDATE moments
SET status = 'missed',
    updated_at = NOW()
FROM threads
WHERE threads.id = moments.thread_id
    AND moments.status = 'due'
    AND moments.deleted_at IS NULL
    AND threads.deleted_at IS NULL
    AND threads.confirmation_timeout_minutes IS NOT NULL
    AND moments.due_at
    + (threads.confirmation_timeout_minutes || ' minutes')::interval < NOW();

-- name: SoftDeleteMoment :exec
UPDATE moments
SET deleted_at = NOW()
WHERE id = sqlc.arg(id)
    AND deleted_at IS NULL;

-- name: RestoreMoment :exec
UPDATE moments
SET deleted_at = NULL
WHERE id = sqlc.arg(id);

-- name: GetHeatmapData :many
-- GitHub-contribution-graph-style data for Rhythms: Moment count per day,
-- bucketed in the user's own timezone (users.timezone), across all of
-- that user's Threads, between [from_date, to_date).
SELECT
    (moments.occurred_at AT TIME ZONE users.timezone)::date AS day,
    COUNT(*)::bigint AS moment_count
FROM moments
    JOIN threads ON threads.id = moments.thread_id
    JOIN users ON users.id = threads.user_id
WHERE threads.user_id = sqlc.arg(user_id)
    AND moments.deleted_at IS NULL
    AND threads.deleted_at IS NULL
    AND moments.occurred_at >= sqlc.arg(from_date)
    AND moments.occurred_at < sqlc.arg(to_date)
GROUP BY day
ORDER BY day;

-- name: GetSettlingTimeStats :many
-- Raw data for the "Time to Tell" chart (see FEATURES.md, Rhythms): how
-- long a Moment took to settle into a record. Measured here as due_at ->
-- captured_at for Commitment-generated Moments.
--
-- NOTE: FEATURES.md defines Time to Tell over *manual* Moments as
-- occurred_at -> recorded_at, which is a different (and the intended)
-- measurement. This query is the Commitment-side punctuality figure and
-- must not be presented as Time to Tell — see TODO.md.
SELECT
    id,
    due_at,
    captured_at,
    EXTRACT(EPOCH FROM (captured_at - due_at))::bigint AS delay_seconds
FROM moments
WHERE thread_id = sqlc.arg(thread_id)
    AND deleted_at IS NULL
    AND due_at IS NOT NULL
    AND captured_at IS NOT NULL
ORDER BY due_at;
