[project]
name = "ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "moez-rd", email = "rahmat.ge4@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
ai = "ai:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
