// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_captures.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmActivityCapture = `-- name: ConfirmActivityCapture :one
    UPDATE activity_captures
    SET status = $1,
        confirmed_at = NOW(),
        content = $2,
        color_hex = $3,
        updated_at = NOW()
    WHERE id = $4 AND status = 'awaiting'
        RETURNING id, activity_id, schedule_id, status, scheduled_at, confirmed_at, occurred_at, content, color_hex, created_at, updated_at, deleted_at
`

type ConfirmActivityCaptureParams struct {
	Status   ActivityCaptureStatus
	Content  pgtype.Text
	ColorHex pgtype.Text
	ID       uuid.UUID
}

// User checks an awaiting item off as done or not done, optionally with
// a moment (content/color). "WHERE status = 'awaiting'" avoids a race
// against the timeout job flipping the same row at the same time.
func (q *Queries) ConfirmActivityCapture(ctx context.Context, arg ConfirmActivityCaptureParams) (ActivityCapture, error) {
	row := q.db.QueryRow(ctx, confirmActivityCapture,
		arg.Status,
		arg.Content,
		arg.ColorHex,
		arg.ID,
	)
	var i ActivityCapture
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.ScheduleID,
		&i.Status,
		&i.ScheduledAt,
		&i.ConfirmedAt,
		&i.OccurredAt,
		&i.Content,
		&i.ColorHex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createManualActivityCapture = `-- name: CreateManualActivityCapture :one
    INSERT INTO activity_captures(
        activity_id,
        status,
        occurred_at,
        content,
        color_hex
    ) VALUES (
        $1,
        $2,
        $3,
        $4,
        $5
    )
    RETURNING id, activity_id, schedule_id, status, scheduled_at, confirmed_at, occurred_at, content, color_hex, created_at, updated_at, deleted_at
`

type CreateManualActivityCaptureParams struct {
	ActivityID uuid.UUID
	Status     ActivityCaptureStatus
	OccurredAt pgtype.Timestamptz
	Content    pgtype.Text
	ColorHex   pgtype.Text
}

// User-logged item for a non-fixed-schedule activity, created directly
// as 'captured' or 'missed' (never 'awaiting'). occurred_at may be
// backdated by the user; scheduled_at/schedule_id stay NULL.
func (q *Queries) CreateManualActivityCapture(ctx context.Context, arg CreateManualActivityCaptureParams) (ActivityCapture, error) {
	row := q.db.QueryRow(ctx, createManualActivityCapture,
		arg.ActivityID,
		arg.Status,
		arg.OccurredAt,
		arg.Content,
		arg.ColorHex,
	)
	var i ActivityCapture
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.ScheduleID,
		&i.Status,
		&i.ScheduledAt,
		&i.ConfirmedAt,
		&i.OccurredAt,
		&i.Content,
		&i.ColorHex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createScheduledActivityCapture = `-- name: CreateScheduledActivityCapture :one
INSERT INTO activity_captures(
    activity_id,
    schedule_id,
    status,
    scheduled_at,
    occurred_at
) VALUES (
    $1,
    $2,
    'awaiting',
    $3,
    $3
)
ON CONFLICT(activity_id, scheduled_at) WHERE deleted_at IS NULL DO NOTHING
    RETURNING id, activity_id, schedule_id, status, scheduled_at, confirmed_at, occurred_at, content, color_hex, created_at, updated_at, deleted_at
`

type CreateScheduledActivityCaptureParams struct {
	ActivityID  uuid.UUID
	ScheduleID  pgtype.UUID
	ScheduledAt pgtype.Timestamptz
}

// Auto-generated by the scheduler worker when a fixed schedule fires.
// occurred_at is set equal to scheduled_at at creation time.
// ON CONFLICT mirrors uq_activity_captures_activity_scheduled_at exactly,
// so a duplicate generation attempt (e.g. two worker instances racing)
// is silently ignored instead of erroring.
func (q *Queries) CreateScheduledActivityCapture(ctx context.Context, arg CreateScheduledActivityCaptureParams) (ActivityCapture, error) {
	row := q.db.QueryRow(ctx, createScheduledActivityCapture, arg.ActivityID, arg.ScheduleID, arg.ScheduledAt)
	var i ActivityCapture
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.ScheduleID,
		&i.Status,
		&i.ScheduledAt,
		&i.ConfirmedAt,
		&i.OccurredAt,
		&i.Content,
		&i.ColorHex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActivityCaptureByID = `-- name: GetActivityCaptureByID :one
    SELECT id, activity_id, schedule_id, status, scheduled_at, confirmed_at, occurred_at, content, color_hex, created_at, updated_at, deleted_at FROM activity_captures
    WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetActivityCaptureByID(ctx context.Context, id uuid.UUID) (ActivityCapture, error) {
	row := q.db.QueryRow(ctx, getActivityCaptureByID, id)
	var i ActivityCapture
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.ScheduleID,
		&i.Status,
		&i.ScheduledAt,
		&i.ConfirmedAt,
		&i.OccurredAt,
		&i.Content,
		&i.ColorHex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getConfirmationDelayStats = `-- name: GetConfirmationDelayStats :many
    SELECT
        id,
        scheduled_at,
        confirmed_at,
        EXTRACT(EPOCH FROM (confirmed_at - scheduled_at)) ::bigint AS delay_seconds
    FROM activity_captures
    WHERE activity_id = $1
        AND deleted_at IS NULL
        AND scheduled_at IS NOT NULL
        AND confirmed_at IS NOT NULL
    ORDER BY scheduled_at
`

type GetConfirmationDelayStatsRow struct {
	ID           uuid.UUID
	ScheduledAt  pgtype.Timestamptz
	ConfirmedAt  pgtype.Timestamptz
	DelaySeconds int64
}

// "Waktu muncul -> konfirmasi" chart for one fixed-schedule activity:
// how long after scheduled_at did the user actually confirm each item.
func (q *Queries) GetConfirmationDelayStats(ctx context.Context, activityID uuid.UUID) ([]GetConfirmationDelayStatsRow, error) {
	rows, err := q.db.Query(ctx, getConfirmationDelayStats, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConfirmationDelayStatsRow{}
	for rows.Next() {
		var i GetConfirmationDelayStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.ScheduledAt,
			&i.ConfirmedAt,
			&i.DelaySeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHeatmapData = `-- name: GetHeatmapData :many
    SELECT
        (activity_captures.occurred_at AT TIME ZONE users.timezone) ::date AS day,
        COUNT(*) ::bigint AS item_count
    FROM activity_captures
        JOIN activities ON activities.id = activity_captures.activity_id
        JOIN users ON users.id = activities.user_id
    WHERE activities.user_id = $1
        AND activity_captures.deleted_at IS NULL
        AND activities.deleted_at IS NULL
        AND activity_captures.occurred_at >= $2
        AND activity_captures.occurred_at < $3
    GROUP BY day
    ORDER BY day
`

type GetHeatmapDataParams struct {
	UserID   uuid.UUID
	FromDate pgtype.Timestamptz
	ToDate   pgtype.Timestamptz
}

type GetHeatmapDataRow struct {
	Day       pgtype.Date
	ItemCount int64
}

// GitHub-contribution-graph-style data: item count per day, bucketed in
// the user's own timezone (users.timezone), across all of that user's
// activities, between [from_date, to_date).
func (q *Queries) GetHeatmapData(ctx context.Context, arg GetHeatmapDataParams) ([]GetHeatmapDataRow, error) {
	rows, err := q.db.Query(ctx, getHeatmapData, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHeatmapDataRow{}
	for rows.Next() {
		var i GetHeatmapDataRow
		if err := rows.Scan(&i.Day, &i.ItemCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityCapturesByActivityID = `-- name: ListActivityCapturesByActivityID :many
    SELECT id, activity_id, schedule_id, status, scheduled_at, confirmed_at, occurred_at, content, color_hex, created_at, updated_at, deleted_at FROM activity_captures
    WHERE activity_id = $1 AND deleted_at IS NULL
    ORDER BY occurred_at DESC
    LIMIT $3
    OFFSET $2
`

type ListActivityCapturesByActivityIDParams struct {
	ActivityID uuid.UUID
	PageOffset int32
	PageLimit  int32
}

// Timeline/history view for one activity, newest occurrence first.
func (q *Queries) ListActivityCapturesByActivityID(ctx context.Context, arg ListActivityCapturesByActivityIDParams) ([]ActivityCapture, error) {
	rows, err := q.db.Query(ctx, listActivityCapturesByActivityID, arg.ActivityID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityCapture{}
	for rows.Next() {
		var i ActivityCapture
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.ScheduleID,
			&i.Status,
			&i.ScheduledAt,
			&i.ConfirmedAt,
			&i.OccurredAt,
			&i.Content,
			&i.ColorHex,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAwaitingItemsPastDeadline = `-- name: ListAwaitingItemsPastDeadline :many
    SELECT activity_captures.id, activity_captures.activity_id, activity_captures.schedule_id, activity_captures.status, activity_captures.scheduled_at, activity_captures.confirmed_at, activity_captures.occurred_at, activity_captures.content, activity_captures.color_hex, activity_captures.created_at, activity_captures.updated_at, activity_captures.deleted_at
    FROM activity_captures
        JOIN activities ON activities.id = activity_captures.activity_id
    WHERE activity_captures.status = 'awaiting'
        AND activity_captures.deleted_at IS NULL
        AND activities.deleted_at IS NULL
        AND activities.confirmation_timeout_minutes IS NOT NULL
        AND activity_captures.scheduled_at
        + (activities.confirmation_timeout_minutes | | ' minutes') ::interval < NOW()
`

// Candidates the timeout worker is about to flip to 'missed'; useful for
// notifying the user beforehand, logging, etc. Mirrors the condition in
// MarkOverdueItemsAsMissed below.
func (q *Queries) ListAwaitingItemsPastDeadline(ctx context.Context) ([]ActivityCapture, error) {
	rows, err := q.db.Query(ctx, listAwaitingItemsPastDeadline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityCapture{}
	for rows.Next() {
		var i ActivityCapture
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.ScheduleID,
			&i.Status,
			&i.ScheduledAt,
			&i.ConfirmedAt,
			&i.OccurredAt,
			&i.Content,
			&i.ColorHex,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOverdueItemsAsMissed = `-- name: MarkOverdueItemsAsMissed :execrows
    UPDATE activity_captures
    SET status = 'missed',
        updated_at = NOW()
    FROM activities
    WHERE activities.id = activity_captures.activity_id
        AND activity_captures.status = 'awaiting'
        AND activity_captures.deleted_at IS NULL
        AND activities.deleted_at IS NULL
        AND activities.confirmation_timeout_minutes IS NOT NULL
        AND activity_captures.scheduled_at
        + (activities.confirmation_timeout_minutes | | ' minutes') ::interval < NOW()
`

// The timeout job itself: bulk-flip every 'awaiting' item whose deadline
// (scheduled_at + activities.confirmation_timeout_minutes) has passed.
// Run this on a schedule (e.g. every minute).
func (q *Queries) MarkOverdueItemsAsMissed(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markOverdueItemsAsMissed)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreActivityCapture = `-- name: RestoreActivityCapture :exec
    UPDATE activity_captures
    SET deleted_at = NULL
    WHERE id = $1
`

func (q *Queries) RestoreActivityCapture(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreActivityCapture, id)
	return err
}

const softDeleteActivityCapture = `-- name: SoftDeleteActivityCapture :exec
    UPDATE activity_captures
    SET deleted_at = NOW()
    WHERE id = $1
        AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteActivityCapture(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteActivityCapture, id)
	return err
}

const updateActivityCaptureMoment = `-- name: UpdateActivityCaptureMoment :one
    UPDATE activity_captures
    SET content = $1,
        color_hex = $2,
        updated_at = NOW()
    WHERE id = $3
        AND deleted_at IS NULL
        RETURNING id, activity_id, schedule_id, status, scheduled_at, confirmed_at, occurred_at, content, color_hex, created_at, updated_at, deleted_at
`

type UpdateActivityCaptureMomentParams struct {
	Content  pgtype.Text
	ColorHex pgtype.Text
	ID       uuid.UUID
}

// Edit the logged moment (content/color) after the fact, without
// touching status/confirmed_at.
func (q *Queries) UpdateActivityCaptureMoment(ctx context.Context, arg UpdateActivityCaptureMomentParams) (ActivityCapture, error) {
	row := q.db.QueryRow(ctx, updateActivityCaptureMoment, arg.Content, arg.ColorHex, arg.ID)
	var i ActivityCapture
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.ScheduleID,
		&i.Status,
		&i.ScheduledAt,
		&i.ConfirmedAt,
		&i.OccurredAt,
		&i.Content,
		&i.ColorHex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
