// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_items.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmActivityItem = `-- name: ConfirmActivityItem :one
    UPDATE activity_items
    SET status = $1,
        confirmed_at = NOW(),
        content = $2,
        color_palette = $3,
        updated_at = NOW()
    WHERE id = $4 AND status = 'awaiting'
        RETURNING id, activity_id, schedule_id, status, scheduled_at, confirmed_at, occurred_at, content, color_palette, created_at, updated_at, deleted_at
`

type ConfirmActivityItemParams struct {
	Status       ActivityItemStatus
	Content      pgtype.Text
	ColorPalette pgtype.Text
	ID           uuid.UUID
}

// User checks an awaiting item off as done or not done, optionally with
// a moment (content/color). "WHERE status = 'awaiting'" avoids a race
// against the timeout job flipping the same row at the same time.
func (q *Queries) ConfirmActivityItem(ctx context.Context, arg ConfirmActivityItemParams) (ActivityItem, error) {
	row := q.db.QueryRow(ctx, confirmActivityItem,
		arg.Status,
		arg.Content,
		arg.ColorPalette,
		arg.ID,
	)
	var i ActivityItem
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.ScheduleID,
		&i.Status,
		&i.ScheduledAt,
		&i.ConfirmedAt,
		&i.OccurredAt,
		&i.Content,
		&i.ColorPalette,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createManualActivityItem = `-- name: CreateManualActivityItem :one
    INSERT INTO activity_items(
        activity_id,
        status,
        occurred_at,
        content,
        color_palette
    ) VALUES (
        $1,
        $2,
        $3,
        $4,
        $5
    )
    RETURNING id, activity_id, schedule_id, status, scheduled_at, confirmed_at, occurred_at, content, color_palette, created_at, updated_at, deleted_at
`

type CreateManualActivityItemParams struct {
	ActivityID   uuid.UUID
	Status       ActivityItemStatus
	OccurredAt   pgtype.Timestamptz
	Content      pgtype.Text
	ColorPalette pgtype.Text
}

// User-logged item for a non-fixed-schedule activity, created directly
// as 'captured' or 'missed' (never 'awaiting'). occurred_at may be
// backdated by the user; scheduled_at/schedule_id stay NULL.
func (q *Queries) CreateManualActivityItem(ctx context.Context, arg CreateManualActivityItemParams) (ActivityItem, error) {
	row := q.db.QueryRow(ctx, createManualActivityItem,
		arg.ActivityID,
		arg.Status,
		arg.OccurredAt,
		arg.Content,
		arg.ColorPalette,
	)
	var i ActivityItem
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.ScheduleID,
		&i.Status,
		&i.ScheduledAt,
		&i.ConfirmedAt,
		&i.OccurredAt,
		&i.Content,
		&i.ColorPalette,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createScheduledActivityItem = `-- name: CreateScheduledActivityItem :one
INSERT INTO activity_items(
    activity_id,
    schedule_id,
    status,
    scheduled_at,
    occurred_at
) VALUES (
    $1,
    $2,
    'awaiting',
    $3,
    $3
)
ON CONFLICT(activity_id, scheduled_at) WHERE deleted_at IS NULL DO NOTHING
    RETURNING id, activity_id, schedule_id, status, scheduled_at, confirmed_at, occurred_at, content, color_palette, created_at, updated_at, deleted_at
`

type CreateScheduledActivityItemParams struct {
	ActivityID  uuid.UUID
	ScheduleID  pgtype.UUID
	ScheduledAt pgtype.Timestamptz
}

// Auto-generated by the scheduler worker when a fixed schedule fires.
// occurred_at is set equal to scheduled_at at creation time.
// ON CONFLICT mirrors uq_activity_items_activity_scheduled_at exactly,
// so a duplicate generation attempt (e.g. two worker instances racing)
// is silently ignored instead of erroring.
func (q *Queries) CreateScheduledActivityItem(ctx context.Context, arg CreateScheduledActivityItemParams) (ActivityItem, error) {
	row := q.db.QueryRow(ctx, createScheduledActivityItem, arg.ActivityID, arg.ScheduleID, arg.ScheduledAt)
	var i ActivityItem
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.ScheduleID,
		&i.Status,
		&i.ScheduledAt,
		&i.ConfirmedAt,
		&i.OccurredAt,
		&i.Content,
		&i.ColorPalette,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActivityItemByID = `-- name: GetActivityItemByID :one
    SELECT id, activity_id, schedule_id, status, scheduled_at, confirmed_at, occurred_at, content, color_palette, created_at, updated_at, deleted_at FROM activity_items
    WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetActivityItemByID(ctx context.Context, id uuid.UUID) (ActivityItem, error) {
	row := q.db.QueryRow(ctx, getActivityItemByID, id)
	var i ActivityItem
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.ScheduleID,
		&i.Status,
		&i.ScheduledAt,
		&i.ConfirmedAt,
		&i.OccurredAt,
		&i.Content,
		&i.ColorPalette,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getConfirmationDelayStats = `-- name: GetConfirmationDelayStats :many
    SELECT
        id,
        scheduled_at,
        confirmed_at,
        EXTRACT(EPOCH FROM (confirmed_at - scheduled_at)) ::bigint AS delay_seconds
    FROM activity_items
    WHERE activity_id = $1
        AND deleted_at IS NULL
        AND scheduled_at IS NOT NULL
        AND confirmed_at IS NOT NULL
    ORDER BY scheduled_at
`

type GetConfirmationDelayStatsRow struct {
	ID           uuid.UUID
	ScheduledAt  pgtype.Timestamptz
	ConfirmedAt  pgtype.Timestamptz
	DelaySeconds int64
}

// "Waktu muncul -> konfirmasi" chart for one fixed-schedule activity:
// how long after scheduled_at did the user actually confirm each item.
func (q *Queries) GetConfirmationDelayStats(ctx context.Context, activityID uuid.UUID) ([]GetConfirmationDelayStatsRow, error) {
	rows, err := q.db.Query(ctx, getConfirmationDelayStats, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConfirmationDelayStatsRow{}
	for rows.Next() {
		var i GetConfirmationDelayStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.ScheduledAt,
			&i.ConfirmedAt,
			&i.DelaySeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHeatmapData = `-- name: GetHeatmapData :many
    SELECT
        (activity_items.occurred_at AT TIME ZONE users.timezone) ::date AS day,
        COUNT(*) ::bigint AS item_count
    FROM activity_items
        JOIN activities ON activities.id = activity_items.activity_id
        JOIN users ON users.id = activities.user_id
    WHERE activities.user_id = $1
        AND activity_items.deleted_at IS NULL
        AND activities.deleted_at IS NULL
        AND activity_items.occurred_at >= $2
        AND activity_items.occurred_at < $3
    GROUP BY day
    ORDER BY day
`

type GetHeatmapDataParams struct {
	UserID   uuid.UUID
	FromDate pgtype.Timestamptz
	ToDate   pgtype.Timestamptz
}

type GetHeatmapDataRow struct {
	Day       pgtype.Date
	ItemCount int64
}

// GitHub-contribution-graph-style data: item count per day, bucketed in
// the user's own timezone (users.timezone), across all of that user's
// activities, between [from_date, to_date).
func (q *Queries) GetHeatmapData(ctx context.Context, arg GetHeatmapDataParams) ([]GetHeatmapDataRow, error) {
	rows, err := q.db.Query(ctx, getHeatmapData, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHeatmapDataRow{}
	for rows.Next() {
		var i GetHeatmapDataRow
		if err := rows.Scan(&i.Day, &i.ItemCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityItemsByActivityID = `-- name: ListActivityItemsByActivityID :many
    SELECT id, activity_id, schedule_id, status, scheduled_at, confirmed_at, occurred_at, content, color_palette, created_at, updated_at, deleted_at FROM activity_items
    WHERE activity_id = $1 AND deleted_at IS NULL
    ORDER BY occurred_at DESC
    LIMIT $3
    OFFSET $2
`

type ListActivityItemsByActivityIDParams struct {
	ActivityID uuid.UUID
	PageOffset int32
	PageLimit  int32
}

// Timeline/history view for one activity, newest occurrence first.
func (q *Queries) ListActivityItemsByActivityID(ctx context.Context, arg ListActivityItemsByActivityIDParams) ([]ActivityItem, error) {
	rows, err := q.db.Query(ctx, listActivityItemsByActivityID, arg.ActivityID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityItem{}
	for rows.Next() {
		var i ActivityItem
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.ScheduleID,
			&i.Status,
			&i.ScheduledAt,
			&i.ConfirmedAt,
			&i.OccurredAt,
			&i.Content,
			&i.ColorPalette,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAwaitingItemsPastDeadline = `-- name: ListAwaitingItemsPastDeadline :many
    SELECT activity_items.id, activity_items.activity_id, activity_items.schedule_id, activity_items.status, activity_items.scheduled_at, activity_items.confirmed_at, activity_items.occurred_at, activity_items.content, activity_items.color_palette, activity_items.created_at, activity_items.updated_at, activity_items.deleted_at
    FROM activity_items
        JOIN activities ON activities.id = activity_items.activity_id
    WHERE activity_items.status = 'awaiting'
        AND activity_items.deleted_at IS NULL
        AND activities.deleted_at IS NULL
        AND activities.confirmation_timeout_minutes IS NOT NULL
        AND activity_items.scheduled_at
        + (activities.confirmation_timeout_minutes | | ' minutes') ::interval < NOW()
`

// Candidates the timeout worker is about to flip to 'missed'; useful for
// notifying the user beforehand, logging, etc. Mirrors the condition in
// MarkOverdueItemsAsMissed below.
func (q *Queries) ListAwaitingItemsPastDeadline(ctx context.Context) ([]ActivityItem, error) {
	rows, err := q.db.Query(ctx, listAwaitingItemsPastDeadline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityItem{}
	for rows.Next() {
		var i ActivityItem
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.ScheduleID,
			&i.Status,
			&i.ScheduledAt,
			&i.ConfirmedAt,
			&i.OccurredAt,
			&i.Content,
			&i.ColorPalette,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOverdueItemsAsMissed = `-- name: MarkOverdueItemsAsMissed :execrows
    UPDATE activity_items
    SET status = 'missed',
        updated_at = NOW()
    FROM activities
    WHERE activities.id = activity_items.activity_id
        AND activity_items.status = 'awaiting'
        AND activity_items.deleted_at IS NULL
        AND activities.deleted_at IS NULL
        AND activities.confirmation_timeout_minutes IS NOT NULL
        AND activity_items.scheduled_at
        + (activities.confirmation_timeout_minutes | | ' minutes') ::interval < NOW()
`

// The timeout job itself: bulk-flip every 'awaiting' item whose deadline
// (scheduled_at + activities.confirmation_timeout_minutes) has passed.
// Run this on a schedule (e.g. every minute).
func (q *Queries) MarkOverdueItemsAsMissed(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markOverdueItemsAsMissed)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreActivityItem = `-- name: RestoreActivityItem :exec
    UPDATE activity_items
    SET deleted_at = NULL
    WHERE id = $1
`

func (q *Queries) RestoreActivityItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreActivityItem, id)
	return err
}

const softDeleteActivityItem = `-- name: SoftDeleteActivityItem :exec
    UPDATE activity_items
    SET deleted_at = NOW()
    WHERE id = $1
        AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteActivityItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteActivityItem, id)
	return err
}

const updateActivityItemMoment = `-- name: UpdateActivityItemMoment :one
    UPDATE activity_items
    SET content = $1,
        color_palette = $2,
        updated_at = NOW()
    WHERE id = $3
        AND deleted_at IS NULL
        RETURNING id, activity_id, schedule_id, status, scheduled_at, confirmed_at, occurred_at, content, color_palette, created_at, updated_at, deleted_at
`

type UpdateActivityItemMomentParams struct {
	Content      pgtype.Text
	ColorPalette pgtype.Text
	ID           uuid.UUID
}

// Edit the logged moment (content/color) after the fact, without
// touching status/confirmed_at.
func (q *Queries) UpdateActivityItemMoment(ctx context.Context, arg UpdateActivityItemMomentParams) (ActivityItem, error) {
	row := q.db.QueryRow(ctx, updateActivityItemMoment, arg.Content, arg.ColorPalette, arg.ID)
	var i ActivityItem
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.ScheduleID,
		&i.Status,
		&i.ScheduledAt,
		&i.ConfirmedAt,
		&i.OccurredAt,
		&i.Content,
		&i.ColorPalette,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
