// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_schedule_histories.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createActivityScheduleHistory = `-- name: CreateActivityScheduleHistory :one
INSERT INTO activity_schedule_histories(
    activity_id,
    schedule_id,
    cron_expression,
    timezone,
    active_from,
    active_until
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, activity_id, schedule_id, cron_expression, timezone, active_from, active_until
`

type CreateActivityScheduleHistoryParams struct {
	ActivityID     uuid.UUID
	ScheduleID     pgtype.UUID
	CronExpression string
	Timezone       pgtype.Text
	ActiveFrom     pgtype.Timestamptz
	ActiveUntil    pgtype.Timestamptz
}

// Archive a schedule's values before it's changed or retired.
func (q *Queries) CreateActivityScheduleHistory(ctx context.Context, arg CreateActivityScheduleHistoryParams) (ActivityScheduleHistory, error) {
	row := q.db.QueryRow(ctx, createActivityScheduleHistory,
		arg.ActivityID,
		arg.ScheduleID,
		arg.CronExpression,
		arg.Timezone,
		arg.ActiveFrom,
		arg.ActiveUntil,
	)
	var i ActivityScheduleHistory
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.ScheduleID,
		&i.CronExpression,
		&i.Timezone,
		&i.ActiveFrom,
		&i.ActiveUntil,
	)
	return i, err
}

const listScheduleHistoryByActivityID = `-- name: ListScheduleHistoryByActivityID :many
SELECT id, activity_id, schedule_id, cron_expression, timezone, active_from, active_until FROM activity_schedule_histories
WHERE activity_id = $1
ORDER BY active_from DESC
`

// "How has this activity's schedule changed over time" view.
func (q *Queries) ListScheduleHistoryByActivityID(ctx context.Context, activityID uuid.UUID) ([]ActivityScheduleHistory, error) {
	rows, err := q.db.Query(ctx, listScheduleHistoryByActivityID, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityScheduleHistory{}
	for rows.Next() {
		var i ActivityScheduleHistory
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.ScheduleID,
			&i.CronExpression,
			&i.Timezone,
			&i.ActiveFrom,
			&i.ActiveUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
