// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_images.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addActivityImage = `-- name: AddActivityImage :one
INSERT INTO activity_images(activity_id, image_path, image_alt)
VALUES ($1, $2, $3)
RETURNING id, activity_id, image_path, image_alt, created_at
`

type AddActivityImageParams struct {
	ActivityID uuid.UUID
	ImagePath  string
	ImageAlt   pgtype.Text
}

func (q *Queries) AddActivityImage(ctx context.Context, arg AddActivityImageParams) (ActivityImage, error) {
	row := q.db.QueryRow(ctx, addActivityImage, arg.ActivityID, arg.ImagePath, arg.ImageAlt)
	var i ActivityImage
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.ImagePath,
		&i.ImageAlt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteActivityImage = `-- name: DeleteActivityImage :exec
DELETE FROM activity_images
WHERE id = $1
    AND activity_id = $2
`

type DeleteActivityImageParams struct {
	ID         uuid.UUID
	ActivityID uuid.UUID
}

func (q *Queries) DeleteActivityImage(ctx context.Context, arg DeleteActivityImageParams) error {
	_, err := q.db.Exec(ctx, deleteActivityImage, arg.ID, arg.ActivityID)
	return err
}

const listActivityImagesByActivityID = `-- name: ListActivityImagesByActivityID :many
SELECT id, activity_id, image_path, image_alt, created_at
FROM activity_images
WHERE activity_id = $1
ORDER BY created_at
`

func (q *Queries) ListActivityImagesByActivityID(ctx context.Context, activityID uuid.UUID) ([]ActivityImage, error) {
	rows, err := q.db.Query(ctx, listActivityImagesByActivityID, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityImage{}
	for rows.Next() {
		var i ActivityImage
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.ImagePath,
			&i.ImageAlt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
