// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: circle_members.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCircleCreatorAsAdmin = `-- name: AddCircleCreatorAsAdmin :one

INSERT INTO circle_members(circle_id, user_id, role, can_invite, can_capture)
VALUES ($1, $2, 'admin', TRUE, TRUE)
RETURNING circle_id, user_id, role, can_invite, can_capture, joined_at, left_at
`

type AddCircleCreatorAsAdminParams struct {
	CircleID uuid.UUID
	UserID   uuid.UUID
}

// Beyond the Circle Invite flow queries, this file also carries general
// membership management: role changes, permission edits, leaving, and
// listing a Circle's roster.
// The one write CreateCircle's caller must run in the same transaction
// right after inserting the Circle row (FEATURES.md, Circle
// Permissions: "The user who creates a circle becomes its admin").
// Deliberately separate from AddCircleMembers, which is the invite
// flow's admit path and always seats people as plain members.
func (q *Queries) AddCircleCreatorAsAdmin(ctx context.Context, arg AddCircleCreatorAsAdminParams) (CircleMember, error) {
	row := q.db.QueryRow(ctx, addCircleCreatorAsAdmin, arg.CircleID, arg.UserID)
	var i CircleMember
	err := row.Scan(
		&i.CircleID,
		&i.UserID,
		&i.Role,
		&i.CanInvite,
		&i.CanCapture,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const addCircleMembers = `-- name: AddCircleMembers :many
INSERT INTO circle_members(circle_id, user_id)
SELECT $1::uuid, member_id
FROM unnest($2::uuid[]) AS member_id
ON CONFLICT (circle_id, user_id) DO UPDATE
SET left_at = NULL,
    joined_at = NOW(),
    role = 'member',
    can_invite = FALSE,
    can_capture = TRUE
WHERE circle_members.left_at IS NOT NULL
RETURNING circle_id, user_id, role, can_invite, can_capture, joined_at, left_at
`

type AddCircleMembersParams struct {
	CircleID uuid.UUID
	UserIds  []uuid.UUID
}

// The single write that admits people, whichever path they came in by:
// a direct add, an accepted username invite, or an approved join
// request. Takes a set because a direct add names several users at once
// (FEATURES.md, Circle Invite).
//
// The upsert is not decoration. Leaving a Circle stamps left_at instead
// of deleting the row, so the primary key survives the departure and a
// returning member would collide with it on a plain INSERT. Rejoining
// resets role and permissions to the defaults rather than restoring what
// the user held before: otherwise an admin who was removed could be
// handed admin back by any member who happens to have invite rights.
//
// Users who are already active members conflict but do not match the
// WHERE, so they are silently skipped and absent from the result — which
// makes the call idempotent and the returned rows exactly "who newly
// joined".
func (q *Queries) AddCircleMembers(ctx context.Context, arg AddCircleMembersParams) ([]CircleMember, error) {
	rows, err := q.db.Query(ctx, addCircleMembers, arg.CircleID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CircleMember{}
	for rows.Next() {
		var i CircleMember
		if err := rows.Scan(
			&i.CircleID,
			&i.UserID,
			&i.Role,
			&i.CanInvite,
			&i.CanCapture,
			&i.JoinedAt,
			&i.LeftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const canUserInviteToCircle = `-- name: CanUserInviteToCircle :one
SELECT EXISTS(
    SELECT 1
    FROM circle_members
    WHERE circle_id = $1
        AND user_id = $2
        AND left_at IS NULL
        AND can_invite = TRUE
) AS can_invite
`

type CanUserInviteToCircleParams struct {
	CircleID uuid.UUID
	UserID   uuid.UUID
}

// Gates every entry point in the Circle Invite flow: adding users
// directly, generating or rotating the link, and deciding join requests.
// Checks can_invite alone because chk_circle_members_admin_can_invite
// guarantees an admin always carries it — role never has to be tested
// separately here.
func (q *Queries) CanUserInviteToCircle(ctx context.Context, arg CanUserInviteToCircleParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserInviteToCircle, arg.CircleID, arg.UserID)
	var can_invite bool
	err := row.Scan(&can_invite)
	return can_invite, err
}

const getActiveCircleMember = `-- name: GetActiveCircleMember :one
SELECT circle_id, user_id, role, can_invite, can_capture, joined_at, left_at
FROM circle_members
WHERE circle_id = $1
    AND user_id = $2
    AND left_at IS NULL
`

type GetActiveCircleMemberParams struct {
	CircleID uuid.UUID
	UserID   uuid.UUID
}

// Active membership is (left_at IS NULL), never mere row existence — see
// the migration's comment on circle_members.
func (q *Queries) GetActiveCircleMember(ctx context.Context, arg GetActiveCircleMemberParams) (CircleMember, error) {
	row := q.db.QueryRow(ctx, getActiveCircleMember, arg.CircleID, arg.UserID)
	var i CircleMember
	err := row.Scan(
		&i.CircleID,
		&i.UserID,
		&i.Role,
		&i.CanInvite,
		&i.CanCapture,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const isSoleActiveCircleAdmin = `-- name: IsSoleActiveCircleAdmin :one
SELECT
    EXISTS(
        SELECT 1 FROM circle_members AS target
        WHERE target.circle_id = $1
            AND target.user_id = $2
            AND target.left_at IS NULL
            AND target.role = 'admin'
    )
    AND NOT EXISTS(
        SELECT 1 FROM circle_members AS other
        WHERE other.circle_id = $1
            AND other.user_id != $2
            AND other.left_at IS NULL
            AND other.role = 'admin'
    ) AS is_sole_admin
`

type IsSoleActiveCircleAdminParams struct {
	CircleID uuid.UUID
	UserID   uuid.UUID
}

// True when user_id is currently an active admin of circle_id and no
// other active admin exists — the guard LeaveCircle and
// UpdateMemberRole (usecase layer) check before letting an admin
// self-leave or self-demote, so a Circle is never left with zero
// admins. Same TOCTOU tolerance as the other unlocked read-then-write
// sequences already accepted elsewhere in this codebase (see TODO.md).
func (q *Queries) IsSoleActiveCircleAdmin(ctx context.Context, arg IsSoleActiveCircleAdminParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, isSoleActiveCircleAdmin, arg.CircleID, arg.UserID)
	var is_sole_admin pgtype.Bool
	err := row.Scan(&is_sole_admin)
	return is_sole_admin, err
}

const leaveCircle = `-- name: LeaveCircle :exec
UPDATE circle_members
SET left_at = NOW()
WHERE circle_id = $1
    AND user_id = $2
    AND left_at IS NULL
`

type LeaveCircleParams struct {
	CircleID uuid.UUID
	UserID   uuid.UUID
}

// Self-service departure. :exec — a mismatched WHERE (not a member,
// already left) is a silent no-op; the caller already knows the actor's
// own membership state without re-checking here.
func (q *Queries) LeaveCircle(ctx context.Context, arg LeaveCircleParams) error {
	_, err := q.db.Exec(ctx, leaveCircle, arg.CircleID, arg.UserID)
	return err
}

const listActiveCircleMembers = `-- name: ListActiveCircleMembers :many
SELECT circle_id, user_id, role, can_invite, can_capture, joined_at, left_at
FROM circle_members
WHERE circle_id = $1
    AND left_at IS NULL
ORDER BY joined_at
`

// The Circle's roster.
func (q *Queries) ListActiveCircleMembers(ctx context.Context, circleID uuid.UUID) ([]CircleMember, error) {
	rows, err := q.db.Query(ctx, listActiveCircleMembers, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CircleMember{}
	for rows.Next() {
		var i CircleMember
		if err := rows.Scan(
			&i.CircleID,
			&i.UserID,
			&i.Role,
			&i.CanInvite,
			&i.CanCapture,
			&i.JoinedAt,
			&i.LeftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCircleIDsSharedBetweenUsers = `-- name: ListCircleIDsSharedBetweenUsers :many
SELECT a.circle_id
FROM circle_members AS a
    JOIN circle_members AS b ON b.circle_id = a.circle_id
WHERE a.user_id = $1
    AND b.user_id = $2
    AND a.left_at IS NULL
    AND b.left_at IS NULL
`

type ListCircleIDsSharedBetweenUsersParams struct {
	UserA uuid.UUID
	UserB uuid.UUID
}

// Which Circles user_a and user_b both actively belong to — for
// surfaces that genuinely mean that and nothing else, such as the
// mention flow's optional "Share to circle too?" step (FEATURES.md,
// Mention). Both memberships must be active: a Circle one of them has
// left is not shared ground. Deliberately returns the ids, not just a
// boolean — the offer needs to name the Circles, and computing this
// server-side means user_b's other, unrelated Circle memberships are
// never exposed to user_a.
//
// This is NOT how audience_policy = 'known' is evaluated. That tier is a
// union of this and an explicit mark, and has its own query — use
// IsUserKnownTo, or a user who marked someone without sharing a Circle
// will be told they are unreachable.
func (q *Queries) ListCircleIDsSharedBetweenUsers(ctx context.Context, arg ListCircleIDsSharedBetweenUsersParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCircleIDsSharedBetweenUsers, arg.UserA, arg.UserB)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var circle_id uuid.UUID
		if err := rows.Scan(&circle_id); err != nil {
			return nil, err
		}
		items = append(items, circle_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCircleMember = `-- name: RemoveCircleMember :exec
UPDATE circle_members AS target
SET left_at = NOW()
WHERE target.circle_id = $1
    AND target.user_id = $2
    AND target.left_at IS NULL
    AND EXISTS (
        SELECT 1 FROM circle_members AS remover
        WHERE remover.circle_id = $1
            AND remover.user_id = $3
            AND remover.left_at IS NULL
            AND remover.role = 'admin'
    )
`

type RemoveCircleMemberParams struct {
	CircleID        uuid.UUID
	UserID          uuid.UUID
	RemovedByUserID uuid.UUID
}

// Admin-forced removal of someone else. Requires the actor to be an
// active admin, checked in the same statement so a non-admin's attempt
// and a foreign circle_id/user_id are indistinguishable — same
// no-row-is-a-no-op reasoning as LeaveCircle. The target row is aliased
// explicitly since the EXISTS subquery below also scans circle_members —
// an unaliased target reads as ambiguous to sqlc's analyzer otherwise.
func (q *Queries) RemoveCircleMember(ctx context.Context, arg RemoveCircleMemberParams) error {
	_, err := q.db.Exec(ctx, removeCircleMember, arg.CircleID, arg.UserID, arg.RemovedByUserID)
	return err
}

const updateCircleMemberPermissions = `-- name: UpdateCircleMemberPermissions :one
UPDATE circle_members AS target
SET can_invite = $1,
    can_capture = $2
WHERE target.circle_id = $3
    AND target.user_id = $4
    AND target.left_at IS NULL
    AND EXISTS (
        SELECT 1 FROM circle_members AS actor
        WHERE actor.circle_id = $3
            AND actor.user_id = $5
            AND actor.left_at IS NULL
            AND actor.role = 'admin'
    )
RETURNING circle_id, user_id, role, can_invite, can_capture, joined_at, left_at
`

type UpdateCircleMemberPermissionsParams struct {
	CanInvite       bool
	CanCapture      bool
	CircleID        uuid.UUID
	UserID          uuid.UUID
	ChangedByUserID uuid.UUID
}

// Admin-only. Setting can_invite = FALSE on an active admin row would
// violate chk_circle_members_admin_can_invite and fails at the database
// level — callers should only offer this control for 'member' rows.
func (q *Queries) UpdateCircleMemberPermissions(ctx context.Context, arg UpdateCircleMemberPermissionsParams) (CircleMember, error) {
	row := q.db.QueryRow(ctx, updateCircleMemberPermissions,
		arg.CanInvite,
		arg.CanCapture,
		arg.CircleID,
		arg.UserID,
		arg.ChangedByUserID,
	)
	var i CircleMember
	err := row.Scan(
		&i.CircleID,
		&i.UserID,
		&i.Role,
		&i.CanInvite,
		&i.CanCapture,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const updateCircleMemberRole = `-- name: UpdateCircleMemberRole :one
UPDATE circle_members AS target
SET role = $1,
    can_invite = CASE WHEN $1::circle_role = 'admin' THEN TRUE ELSE target.can_invite END
WHERE target.circle_id = $2
    AND target.user_id = $3
    AND target.left_at IS NULL
    AND EXISTS (
        SELECT 1 FROM circle_members AS actor
        WHERE actor.circle_id = $2
            AND actor.user_id = $4
            AND actor.left_at IS NULL
            AND actor.role = 'admin'
    )
RETURNING circle_id, user_id, role, can_invite, can_capture, joined_at, left_at
`

type UpdateCircleMemberRoleParams struct {
	Role            CircleRole
	CircleID        uuid.UUID
	UserID          uuid.UUID
	ChangedByUserID uuid.UUID
}

// Admin-only, same actor-check shape as RemoveCircleMember. Promoting to
// 'admin' also forces can_invite = TRUE in the same statement —
// chk_circle_members_admin_can_invite requires it, and leaving that to a
// second call would let the row violate the constraint in between.
func (q *Queries) UpdateCircleMemberRole(ctx context.Context, arg UpdateCircleMemberRoleParams) (CircleMember, error) {
	row := q.db.QueryRow(ctx, updateCircleMemberRole,
		arg.Role,
		arg.CircleID,
		arg.UserID,
		arg.ChangedByUserID,
	)
	var i CircleMember
	err := row.Scan(
		&i.CircleID,
		&i.UserID,
		&i.Role,
		&i.CanInvite,
		&i.CanCapture,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}
