// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commitment_histories.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCommitmentHistory = `-- name: CreateCommitmentHistory :one
INSERT INTO commitment_histories(
    thread_id,
    commitment_id,
    cron_expression,
    timezone,
    active_from,
    active_until
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, thread_id, commitment_id, cron_expression, timezone, active_from, active_until
`

type CreateCommitmentHistoryParams struct {
	ThreadID       uuid.UUID
	CommitmentID   pgtype.UUID
	CronExpression string
	Timezone       pgtype.Text
	ActiveFrom     pgtype.Timestamptz
	ActiveUntil    pgtype.Timestamptz
}

// Archive a Commitment's values before it's changed or retired.
func (q *Queries) CreateCommitmentHistory(ctx context.Context, arg CreateCommitmentHistoryParams) (CommitmentHistory, error) {
	row := q.db.QueryRow(ctx, createCommitmentHistory,
		arg.ThreadID,
		arg.CommitmentID,
		arg.CronExpression,
		arg.Timezone,
		arg.ActiveFrom,
		arg.ActiveUntil,
	)
	var i CommitmentHistory
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.CommitmentID,
		&i.CronExpression,
		&i.Timezone,
		&i.ActiveFrom,
		&i.ActiveUntil,
	)
	return i, err
}

const listCommitmentHistoryByThreadID = `-- name: ListCommitmentHistoryByThreadID :many
SELECT id, thread_id, commitment_id, cron_expression, timezone, active_from, active_until FROM commitment_histories
WHERE thread_id = $1
ORDER BY active_from DESC
`

// "How has this Thread's commitments changed over time" view.
func (q *Queries) ListCommitmentHistoryByThreadID(ctx context.Context, threadID uuid.UUID) ([]CommitmentHistory, error) {
	rows, err := q.db.Query(ctx, listCommitmentHistoryByThreadID, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommitmentHistory{}
	for rows.Next() {
		var i CommitmentHistory
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.CommitmentID,
			&i.CronExpression,
			&i.Timezone,
			&i.ActiveFrom,
			&i.ActiveUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
