// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commitments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCommitment = `-- name: CreateCommitment :one
INSERT INTO commitments(thread_id, cron_expression, timezone)
VALUES ($1, $2, $3)
RETURNING id, thread_id, cron_expression, timezone, created_at
`

type CreateCommitmentParams struct {
	ThreadID       uuid.UUID
	CronExpression string
	Timezone       pgtype.Text
}

func (q *Queries) CreateCommitment(ctx context.Context, arg CreateCommitmentParams) (Commitment, error) {
	row := q.db.QueryRow(ctx, createCommitment, arg.ThreadID, arg.CronExpression, arg.Timezone)
	var i Commitment
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.CronExpression,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCommitment = `-- name: DeleteCommitment :exec
DELETE FROM commitments
WHERE id = $1 AND thread_id = $2
`

type DeleteCommitmentParams struct {
	ID       uuid.UUID
	ThreadID uuid.UUID
}

// Retire a Commitment entirely. The caller should archive it into
// commitment_histories first. Existing Moments that referenced it keep
// thread_id intact and just get commitment_id set to NULL (composite FK,
// ON DELETE SET NULL (commitment_id)).
func (q *Queries) DeleteCommitment(ctx context.Context, arg DeleteCommitmentParams) error {
	_, err := q.db.Exec(ctx, deleteCommitment, arg.ID, arg.ThreadID)
	return err
}

const getCommitmentByID = `-- name: GetCommitmentByID :one
SELECT id, thread_id, cron_expression, timezone, created_at
FROM commitments
WHERE id = $1 AND thread_id = $2
`

type GetCommitmentByIDParams struct {
	ID       uuid.UUID
	ThreadID uuid.UUID
}

func (q *Queries) GetCommitmentByID(ctx context.Context, arg GetCommitmentByIDParams) (Commitment, error) {
	row := q.db.QueryRow(ctx, getCommitmentByID, arg.ID, arg.ThreadID)
	var i Commitment
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.CronExpression,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const listCommitmentsByThreadID = `-- name: ListCommitmentsByThreadID :many
SELECT id, thread_id, cron_expression, timezone, created_at
FROM commitments
WHERE thread_id = $1
ORDER BY created_at
`

// Can return more than one row: a Thread may carry several concurrent
// Commitments (e.g. a morning one and an evening one), each with its own
// recurrence rule.
func (q *Queries) ListCommitmentsByThreadID(ctx context.Context, threadID uuid.UUID) ([]Commitment, error) {
	rows, err := q.db.Query(ctx, listCommitmentsByThreadID, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Commitment{}
	for rows.Next() {
		var i Commitment
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.CronExpression,
			&i.Timezone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommitmentsForGeneration = `-- name: ListCommitmentsForGeneration :many
SELECT commitments.id, commitments.thread_id, commitments.cron_expression, commitments.timezone, commitments.created_at FROM commitments
    JOIN threads ON threads.id = commitments.thread_id
WHERE threads.deleted_at IS NULL AND threads.has_commitment = TRUE
`

// Feed for the scheduler worker: every Commitment belonging to a
// non-deleted Thread. The worker evaluates cron_expression/timezone
// itself and calls moments.CreateCommittedMoment when a slot fires.
func (q *Queries) ListCommitmentsForGeneration(ctx context.Context) ([]Commitment, error) {
	rows, err := q.db.Query(ctx, listCommitmentsForGeneration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Commitment{}
	for rows.Next() {
		var i Commitment
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.CronExpression,
			&i.Timezone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommitment = `-- name: UpdateCommitment :one
UPDATE commitments
SET cron_expression = $1,
    timezone = $2
WHERE id = $3 AND thread_id = $4
    RETURNING id, thread_id, cron_expression, timezone, created_at
`

type UpdateCommitmentParams struct {
	CronExpression string
	Timezone       pgtype.Text
	ID             uuid.UUID
	ThreadID       uuid.UUID
}

// Update in place (same id) so existing moments.commitment_id links stay
// valid. The caller must insert a row into commitment_histories with the
// OLD cron_expression/timezone BEFORE calling this, in the same
// transaction.
func (q *Queries) UpdateCommitment(ctx context.Context, arg UpdateCommitmentParams) (Commitment, error) {
	row := q.db.QueryRow(ctx, updateCommitment,
		arg.CronExpression,
		arg.Timezone,
		arg.ID,
		arg.ThreadID,
	)
	var i Commitment
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.CronExpression,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}
