// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: data_exports.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDataExport = `-- name: CreateDataExport :one
INSERT INTO data_exports(user_id)
VALUES ($1)
RETURNING id, user_id, status, file_path, byte_size, error_message, requested_at, completed_at, expires_at
`

// "Export all my data" (FEATURES.md, Data Controls). Starts in
// 'pending'; the export worker moves it through running -> ready/failed.
func (q *Queries) CreateDataExport(ctx context.Context, userID uuid.UUID) (DataExport, error) {
	row := q.db.QueryRow(ctx, createDataExport, userID)
	var i DataExport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.FilePath,
		&i.ByteSize,
		&i.ErrorMessage,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteDataExport = `-- name: DeleteDataExport :exec
DELETE FROM data_exports
WHERE id = $1
`

// Called after the underlying file has been removed from storage.
func (q *Queries) DeleteDataExport(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDataExport, id)
	return err
}

const getDataExportByID = `-- name: GetDataExportByID :one
SELECT id, user_id, status, file_path, byte_size, error_message, requested_at, completed_at, expires_at
FROM data_exports
WHERE id = $1
    AND user_id = $2
`

type GetDataExportByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// user_id in the WHERE clause doubles as an ownership check.
func (q *Queries) GetDataExportByID(ctx context.Context, arg GetDataExportByIDParams) (DataExport, error) {
	row := q.db.QueryRow(ctx, getDataExportByID, arg.ID, arg.UserID)
	var i DataExport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.FilePath,
		&i.ByteSize,
		&i.ErrorMessage,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getLatestActiveDataExportByUserID = `-- name: GetLatestActiveDataExportByUserID :one
SELECT id, user_id, status, file_path, byte_size, error_message, requested_at, completed_at, expires_at
FROM data_exports
WHERE user_id = $1
    AND status IN ('pending', 'running')
ORDER BY requested_at DESC
LIMIT 1
`

// Lets the usecase avoid queuing a duplicate export while one is
// already pending/running for this user.
func (q *Queries) GetLatestActiveDataExportByUserID(ctx context.Context, userID uuid.UUID) (DataExport, error) {
	row := q.db.QueryRow(ctx, getLatestActiveDataExportByUserID, userID)
	var i DataExport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.FilePath,
		&i.ByteSize,
		&i.ErrorMessage,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listDataExportsByUserID = `-- name: ListDataExportsByUserID :many
SELECT id, user_id, status, file_path, byte_size, error_message, requested_at, completed_at, expires_at
FROM data_exports
WHERE user_id = $1
ORDER BY requested_at DESC
`

// Export history, newest first.
func (q *Queries) ListDataExportsByUserID(ctx context.Context, userID uuid.UUID) ([]DataExport, error) {
	rows, err := q.db.Query(ctx, listDataExportsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DataExport{}
	for rows.Next() {
		var i DataExport
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.FilePath,
			&i.ByteSize,
			&i.ErrorMessage,
			&i.RequestedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredReadyDataExports = `-- name: ListExpiredReadyDataExports :many
SELECT id, user_id, status, file_path, byte_size, error_message, requested_at, completed_at, expires_at
FROM data_exports
WHERE status = 'ready'
    AND expires_at IS NOT NULL
    AND expires_at < NOW()
`

// Periodic cleanup job: exports whose download link has expired and
// whose stored file can now be removed from object storage.
func (q *Queries) ListExpiredReadyDataExports(ctx context.Context) ([]DataExport, error) {
	rows, err := q.db.Query(ctx, listExpiredReadyDataExports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DataExport{}
	for rows.Next() {
		var i DataExport
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.FilePath,
			&i.ByteSize,
			&i.ErrorMessage,
			&i.RequestedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDataExportFailed = `-- name: MarkDataExportFailed :exec
UPDATE data_exports
SET status = 'failed',
    error_message = $1,
    completed_at = NOW()
WHERE id = $2
`

type MarkDataExportFailedParams struct {
	ErrorMessage pgtype.Text
	ID           uuid.UUID
}

func (q *Queries) MarkDataExportFailed(ctx context.Context, arg MarkDataExportFailedParams) error {
	_, err := q.db.Exec(ctx, markDataExportFailed, arg.ErrorMessage, arg.ID)
	return err
}

const markDataExportReady = `-- name: MarkDataExportReady :exec
UPDATE data_exports
SET status = 'ready',
    file_path = $1,
    byte_size = $2,
    completed_at = NOW(),
    expires_at = $3
WHERE id = $4
`

type MarkDataExportReadyParams struct {
	FilePath  pgtype.Text
	ByteSize  pgtype.Int8
	ExpiresAt pgtype.Timestamptz
	ID        uuid.UUID
}

func (q *Queries) MarkDataExportReady(ctx context.Context, arg MarkDataExportReadyParams) error {
	_, err := q.db.Exec(ctx, markDataExportReady,
		arg.FilePath,
		arg.ByteSize,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}

const markDataExportRunning = `-- name: MarkDataExportRunning :exec
UPDATE data_exports
SET status = 'running'
WHERE id = $1
    AND status = 'pending'
`

func (q *Queries) MarkDataExportRunning(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markDataExportRunning, id)
	return err
}
