// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moment_circles.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listCircleIDsByMomentID = `-- name: ListCircleIDsByMomentID :many
SELECT circle_id
FROM moment_circles
WHERE moment_id = $1
`

// Which Circles a personal Moment is currently shared into, for its
// own edit/unshare UI.
func (q *Queries) ListCircleIDsByMomentID(ctx context.Context, momentID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCircleIDsByMomentID, momentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var circle_id uuid.UUID
		if err := rows.Scan(&circle_id); err != nil {
			return nil, err
		}
		items = append(items, circle_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMomentsSharedToCircle = `-- name: ListMomentsSharedToCircle :many
SELECT moments.id, moments.user_id, moments.thread_id, moments.origin, moments.occurred_at, moments.occurred_local, moments.occurred_utc_offset_minutes, moments.occurred_on, moments.recorded_at, moments.settling_time, moments.note, moments.color_hex, moments.place_name, moments.latitude, moments.longitude, moments.search_document, moments.client_id, moments.last_viewed_at, moments.created_at, moments.updated_at, moments.deleted_at, moment_circles.shared_by_user_id, moment_circles.shared_at
FROM moment_circles
    JOIN moments ON moments.id = moment_circles.moment_id
WHERE moment_circles.circle_id = $1
    AND moments.deleted_at IS NULL
ORDER BY moment_circles.shared_at DESC
LIMIT $3
OFFSET $2
`

type ListMomentsSharedToCircleParams struct {
	CircleID   uuid.UUID
	PageOffset int32
	PageLimit  int32
}

type ListMomentsSharedToCircleRow struct {
	ID                       uuid.UUID
	UserID                   uuid.UUID
	ThreadID                 pgtype.UUID
	Origin                   MomentOrigin
	OccurredAt               pgtype.Timestamptz
	OccurredLocal            pgtype.Timestamp
	OccurredUtcOffsetMinutes int16
	OccurredOn               pgtype.Date
	RecordedAt               pgtype.Timestamptz
	SettlingTime             pgtype.Interval
	Note                     pgtype.Text
	ColorHex                 pgtype.Text
	PlaceName                pgtype.Text
	Latitude                 pgtype.Numeric
	Longitude                pgtype.Numeric
	SearchDocument           interface{}
	ClientID                 pgtype.UUID
	LastViewedAt             pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	DeletedAt                pgtype.Timestamptz
	SharedByUserID           pgtype.UUID
	SharedAt                 pgtype.Timestamptz
}

// Personal Moments shared into this Circle via the mention flow.
// Combined with the Circle's own collaborative-Thread Moments
// (threads.circle_id), this is the Circle's Album (FEATURES.md,
// Looking Back).
func (q *Queries) ListMomentsSharedToCircle(ctx context.Context, arg ListMomentsSharedToCircleParams) ([]ListMomentsSharedToCircleRow, error) {
	rows, err := q.db.Query(ctx, listMomentsSharedToCircle, arg.CircleID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMomentsSharedToCircleRow{}
	for rows.Next() {
		var i ListMomentsSharedToCircleRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ThreadID,
			&i.Origin,
			&i.OccurredAt,
			&i.OccurredLocal,
			&i.OccurredUtcOffsetMinutes,
			&i.OccurredOn,
			&i.RecordedAt,
			&i.SettlingTime,
			&i.Note,
			&i.ColorHex,
			&i.PlaceName,
			&i.Latitude,
			&i.Longitude,
			&i.SearchDocument,
			&i.ClientID,
			&i.LastViewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SharedByUserID,
			&i.SharedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shareMomentToCircle = `-- name: ShareMomentToCircle :one
INSERT INTO moment_circles(moment_id, circle_id, shared_by_user_id)
VALUES ($1, $2, $3)
ON CONFLICT (moment_id, circle_id) DO NOTHING
RETURNING moment_id, circle_id, shared_by_user_id, shared_at
`

type ShareMomentToCircleParams struct {
	MomentID       uuid.UUID
	CircleID       uuid.UUID
	SharedByUserID pgtype.UUID
}

// The "Share to circle too?" step of the mention flow (FEATURES.md,
// Mention) — never a standalone "share" action. Idempotent: sharing
// into a Circle it's already shared to is a no-op.
func (q *Queries) ShareMomentToCircle(ctx context.Context, arg ShareMomentToCircleParams) (MomentCircle, error) {
	row := q.db.QueryRow(ctx, shareMomentToCircle, arg.MomentID, arg.CircleID, arg.SharedByUserID)
	var i MomentCircle
	err := row.Scan(
		&i.MomentID,
		&i.CircleID,
		&i.SharedByUserID,
		&i.SharedAt,
	)
	return i, err
}

const unshareMomentFromCircle = `-- name: UnshareMomentFromCircle :exec
DELETE FROM moment_circles
WHERE moment_id = $1
    AND circle_id = $2
`

type UnshareMomentFromCircleParams struct {
	MomentID uuid.UUID
	CircleID uuid.UUID
}

func (q *Queries) UnshareMomentFromCircle(ctx context.Context, arg UnshareMomentFromCircleParams) error {
	_, err := q.db.Exec(ctx, unshareMomentFromCircle, arg.MomentID, arg.CircleID)
	return err
}
