// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moment_images.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addMomentImage = `-- name: AddMomentImage :one
INSERT INTO moment_images(
    moment_id, image_path, image_alt,
    content_type, byte_size, width, height, metadata_stripped
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8
)
RETURNING id, moment_id, image_path, image_alt, content_type, byte_size, width, height, metadata_stripped, sort_order, created_at
`

type AddMomentImageParams struct {
	MomentID         uuid.UUID
	ImagePath        string
	ImageAlt         pgtype.Text
	ContentType      pgtype.Text
	ByteSize         pgtype.Int8
	Width            pgtype.Int4
	Height           pgtype.Int4
	MetadataStripped bool
}

func (q *Queries) AddMomentImage(ctx context.Context, arg AddMomentImageParams) (MomentImage, error) {
	row := q.db.QueryRow(ctx, addMomentImage,
		arg.MomentID,
		arg.ImagePath,
		arg.ImageAlt,
		arg.ContentType,
		arg.ByteSize,
		arg.Width,
		arg.Height,
		arg.MetadataStripped,
	)
	var i MomentImage
	err := row.Scan(
		&i.ID,
		&i.MomentID,
		&i.ImagePath,
		&i.ImageAlt,
		&i.ContentType,
		&i.ByteSize,
		&i.Width,
		&i.Height,
		&i.MetadataStripped,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMomentImage = `-- name: DeleteMomentImage :exec
DELETE FROM moment_images
WHERE id = $1
    AND moment_id = $2
`

type DeleteMomentImageParams struct {
	ID       uuid.UUID
	MomentID uuid.UUID
}

func (q *Queries) DeleteMomentImage(ctx context.Context, arg DeleteMomentImageParams) error {
	_, err := q.db.Exec(ctx, deleteMomentImage, arg.ID, arg.MomentID)
	return err
}

const listMomentImagesByMomentID = `-- name: ListMomentImagesByMomentID :many
SELECT id, moment_id, image_path, image_alt, content_type, byte_size, width, height, metadata_stripped, sort_order, created_at
FROM moment_images
WHERE moment_id = $1
ORDER BY sort_order, created_at
`

func (q *Queries) ListMomentImagesByMomentID(ctx context.Context, momentID uuid.UUID) ([]MomentImage, error) {
	rows, err := q.db.Query(ctx, listMomentImagesByMomentID, momentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MomentImage{}
	for rows.Next() {
		var i MomentImage
		if err := rows.Scan(
			&i.ID,
			&i.MomentID,
			&i.ImagePath,
			&i.ImageAlt,
			&i.ContentType,
			&i.ByteSize,
			&i.Width,
			&i.Height,
			&i.MetadataStripped,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
