// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCommittedMoment = `-- name: CreateCommittedMoment :one
INSERT INTO moments(
    thread_id,
    commitment_id,
    status,
    due_at,
    occurred_at
) VALUES (
    $1,
    $2,
    'due',
    $3,
    $3
)
ON CONFLICT(thread_id, due_at) WHERE deleted_at IS NULL DO NOTHING
    RETURNING id, thread_id, commitment_id, status, due_at, captured_at, occurred_at, content, color_hex, created_at, updated_at, deleted_at
`

type CreateCommittedMomentParams struct {
	ThreadID     uuid.UUID
	CommitmentID pgtype.UUID
	DueAt        pgtype.Timestamptz
}

// Auto-generated by the scheduler worker when a Commitment fires.
// occurred_at is set equal to due_at at creation time.
// ON CONFLICT mirrors uq_moments_thread_id_due_at exactly, so a
// duplicate generation attempt (e.g. two worker instances racing) is
// silently ignored instead of erroring.
func (q *Queries) CreateCommittedMoment(ctx context.Context, arg CreateCommittedMomentParams) (Moment, error) {
	row := q.db.QueryRow(ctx, createCommittedMoment, arg.ThreadID, arg.CommitmentID, arg.DueAt)
	var i Moment
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.CommitmentID,
		&i.Status,
		&i.DueAt,
		&i.CapturedAt,
		&i.OccurredAt,
		&i.Content,
		&i.ColorHex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createManualMoment = `-- name: CreateManualMoment :one
INSERT INTO moments(
    thread_id,
    status,
    occurred_at,
    content,
    color_hex
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, thread_id, commitment_id, status, due_at, captured_at, occurred_at, content, color_hex, created_at, updated_at, deleted_at
`

type CreateManualMomentParams struct {
	ThreadID   uuid.UUID
	Status     MomentStatus
	OccurredAt pgtype.Timestamptz
	Content    pgtype.Text
	ColorHex   pgtype.Text
}

// A Moment the user captured themselves. occurred_at may be backdated;
// due_at/commitment_id stay NULL because nothing was ever owed.
// Manual Moments carry no meaningful state — see the note on
// moments.status in TODO.md.
func (q *Queries) CreateManualMoment(ctx context.Context, arg CreateManualMomentParams) (Moment, error) {
	row := q.db.QueryRow(ctx, createManualMoment,
		arg.ThreadID,
		arg.Status,
		arg.OccurredAt,
		arg.Content,
		arg.ColorHex,
	)
	var i Moment
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.CommitmentID,
		&i.Status,
		&i.DueAt,
		&i.CapturedAt,
		&i.OccurredAt,
		&i.Content,
		&i.ColorHex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getHeatmapData = `-- name: GetHeatmapData :many
SELECT
    (moments.occurred_at AT TIME ZONE users.timezone)::date AS day,
    COUNT(*)::bigint AS moment_count
FROM moments
    JOIN threads ON threads.id = moments.thread_id
    JOIN users ON users.id = threads.user_id
WHERE threads.user_id = $1
    AND moments.deleted_at IS NULL
    AND threads.deleted_at IS NULL
    AND moments.occurred_at >= $2
    AND moments.occurred_at < $3
GROUP BY day
ORDER BY day
`

type GetHeatmapDataParams struct {
	UserID   uuid.UUID
	FromDate pgtype.Timestamptz
	ToDate   pgtype.Timestamptz
}

type GetHeatmapDataRow struct {
	Day         pgtype.Date
	MomentCount int64
}

// GitHub-contribution-graph-style data for Rhythms: Moment count per day,
// bucketed in the user's own timezone (users.timezone), across all of
// that user's Threads, between [from_date, to_date).
func (q *Queries) GetHeatmapData(ctx context.Context, arg GetHeatmapDataParams) ([]GetHeatmapDataRow, error) {
	rows, err := q.db.Query(ctx, getHeatmapData, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHeatmapDataRow{}
	for rows.Next() {
		var i GetHeatmapDataRow
		if err := rows.Scan(&i.Day, &i.MomentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMomentByID = `-- name: GetMomentByID :one
SELECT id, thread_id, commitment_id, status, due_at, captured_at, occurred_at, content, color_hex, created_at, updated_at, deleted_at FROM moments
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMomentByID(ctx context.Context, id uuid.UUID) (Moment, error) {
	row := q.db.QueryRow(ctx, getMomentByID, id)
	var i Moment
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.CommitmentID,
		&i.Status,
		&i.DueAt,
		&i.CapturedAt,
		&i.OccurredAt,
		&i.Content,
		&i.ColorHex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSettlingTimeStats = `-- name: GetSettlingTimeStats :many
SELECT
    id,
    due_at,
    captured_at,
    EXTRACT(EPOCH FROM (captured_at - due_at))::bigint AS delay_seconds
FROM moments
WHERE thread_id = $1
    AND deleted_at IS NULL
    AND due_at IS NOT NULL
    AND captured_at IS NOT NULL
ORDER BY due_at
`

type GetSettlingTimeStatsRow struct {
	ID           uuid.UUID
	DueAt        pgtype.Timestamptz
	CapturedAt   pgtype.Timestamptz
	DelaySeconds int64
}

// Raw data for the "Time to Tell" chart (see FEATURES.md, Rhythms): how
// long a Moment took to settle into a record. Measured here as due_at ->
// captured_at for Commitment-generated Moments.
//
// NOTE: FEATURES.md defines Time to Tell over *manual* Moments as
// occurred_at -> recorded_at, which is a different (and the intended)
// measurement. This query is the Commitment-side punctuality figure and
// must not be presented as Time to Tell — see TODO.md.
func (q *Queries) GetSettlingTimeStats(ctx context.Context, threadID uuid.UUID) ([]GetSettlingTimeStatsRow, error) {
	rows, err := q.db.Query(ctx, getSettlingTimeStats, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSettlingTimeStatsRow{}
	for rows.Next() {
		var i GetSettlingTimeStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.DueAt,
			&i.CapturedAt,
			&i.DelaySeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueMomentsPastDeadline = `-- name: ListDueMomentsPastDeadline :many
SELECT moments.id, moments.thread_id, moments.commitment_id, moments.status, moments.due_at, moments.captured_at, moments.occurred_at, moments.content, moments.color_hex, moments.created_at, moments.updated_at, moments.deleted_at
FROM moments
    JOIN threads ON threads.id = moments.thread_id
WHERE moments.status = 'due'
    AND moments.deleted_at IS NULL
    AND threads.deleted_at IS NULL
    AND threads.confirmation_timeout_minutes IS NOT NULL
    AND moments.due_at
    + (threads.confirmation_timeout_minutes || ' minutes')::interval < NOW()
`

// Candidates the timeout worker is about to flip to 'missed'; useful for
// logging and for the opt-in "Moment missed" notification. Mirrors the
// condition in MarkOverdueMomentsAsMissed below.
func (q *Queries) ListDueMomentsPastDeadline(ctx context.Context) ([]Moment, error) {
	rows, err := q.db.Query(ctx, listDueMomentsPastDeadline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Moment{}
	for rows.Next() {
		var i Moment
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.CommitmentID,
			&i.Status,
			&i.DueAt,
			&i.CapturedAt,
			&i.OccurredAt,
			&i.Content,
			&i.ColorHex,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMomentsByThreadID = `-- name: ListMomentsByThreadID :many
SELECT id, thread_id, commitment_id, status, due_at, captured_at, occurred_at, content, color_hex, created_at, updated_at, deleted_at FROM moments
WHERE thread_id = $1 AND deleted_at IS NULL
ORDER BY occurred_at DESC
LIMIT $3
OFFSET $2
`

type ListMomentsByThreadIDParams struct {
	ThreadID   uuid.UUID
	PageOffset int32
	PageLimit  int32
}

// Timeline/history view for one Thread, newest occurrence first.
func (q *Queries) ListMomentsByThreadID(ctx context.Context, arg ListMomentsByThreadIDParams) ([]Moment, error) {
	rows, err := q.db.Query(ctx, listMomentsByThreadID, arg.ThreadID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Moment{}
	for rows.Next() {
		var i Moment
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.CommitmentID,
			&i.Status,
			&i.DueAt,
			&i.CapturedAt,
			&i.OccurredAt,
			&i.Content,
			&i.ColorHex,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOverdueMomentsAsMissed = `-- name: MarkOverdueMomentsAsMissed :execrows
UPDATE moments
SET status = 'missed',
    updated_at = NOW()
FROM threads
WHERE threads.id = moments.thread_id
    AND moments.status = 'due'
    AND moments.deleted_at IS NULL
    AND threads.deleted_at IS NULL
    AND threads.confirmation_timeout_minutes IS NOT NULL
    AND moments.due_at
    + (threads.confirmation_timeout_minutes || ' minutes')::interval < NOW()
`

// The timeout job itself: bulk-flip every 'due' Moment whose confirmation
// window (due_at + threads.confirmation_timeout_minutes) has closed.
// Run this on a schedule (e.g. every minute).
func (q *Queries) MarkOverdueMomentsAsMissed(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markOverdueMomentsAsMissed)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordMoment = `-- name: RecordMoment :one
UPDATE moments
SET status = $1,
    captured_at = NOW(),
    content = $2,
    color_hex = $3,
    updated_at = NOW()
WHERE id = $4 AND status = 'due'
    RETURNING id, thread_id, commitment_id, status, due_at, captured_at, occurred_at, content, color_hex, created_at, updated_at, deleted_at
`

type RecordMomentParams struct {
	Status   MomentStatus
	Content  pgtype.Text
	ColorHex pgtype.Text
	ID       uuid.UUID
}

// The user answers a due Moment, optionally attaching content/color.
// "WHERE status = 'due'" avoids a race against the timeout job flipping
// the same row at the same time.
func (q *Queries) RecordMoment(ctx context.Context, arg RecordMomentParams) (Moment, error) {
	row := q.db.QueryRow(ctx, recordMoment,
		arg.Status,
		arg.Content,
		arg.ColorHex,
		arg.ID,
	)
	var i Moment
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.CommitmentID,
		&i.Status,
		&i.DueAt,
		&i.CapturedAt,
		&i.OccurredAt,
		&i.Content,
		&i.ColorHex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const restoreMoment = `-- name: RestoreMoment :exec
UPDATE moments
SET deleted_at = NULL
WHERE id = $1
`

func (q *Queries) RestoreMoment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreMoment, id)
	return err
}

const softDeleteMoment = `-- name: SoftDeleteMoment :exec
UPDATE moments
SET deleted_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMoment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteMoment, id)
	return err
}

const updateMomentContent = `-- name: UpdateMomentContent :one
UPDATE moments
SET content = $1,
    color_hex = $2,
    updated_at = NOW()
WHERE id = $3
    AND deleted_at IS NULL
    RETURNING id, thread_id, commitment_id, status, due_at, captured_at, occurred_at, content, color_hex, created_at, updated_at, deleted_at
`

type UpdateMomentContentParams struct {
	Content  pgtype.Text
	ColorHex pgtype.Text
	ID       uuid.UUID
}

// Edit a Moment's content/color after the fact, without touching
// status/captured_at. A Moment is never final — see FEATURES.md,
// "Moments are never final".
func (q *Queries) UpdateMomentContent(ctx context.Context, arg UpdateMomentContentParams) (Moment, error) {
	row := q.db.QueryRow(ctx, updateMomentContent, arg.Content, arg.ColorHex, arg.ID)
	var i Moment
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.CommitmentID,
		&i.Status,
		&i.DueAt,
		&i.CapturedAt,
		&i.OccurredAt,
		&i.Content,
		&i.ColorHex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
