// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moment_mentions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMomentMention = `-- name: CreateMomentMention :one
INSERT INTO moment_mentions(moment_id, mentioned_user_id, display_name)
VALUES ($1, $2, $3)
RETURNING id, moment_id, mentioned_user_id, display_name, removed_at, created_at
`

type CreateMomentMentionParams struct {
	MomentID        uuid.UUID
	MentionedUserID pgtype.UUID
	DisplayName     string
}

// display_name is a snapshot taken at mention time (see the column
// comment): the caller resolves it from the mentioned user's current
// name before calling this, it is not derived here.
func (q *Queries) CreateMomentMention(ctx context.Context, arg CreateMomentMentionParams) (MomentMention, error) {
	row := q.db.QueryRow(ctx, createMomentMention, arg.MomentID, arg.MentionedUserID, arg.DisplayName)
	var i MomentMention
	err := row.Scan(
		&i.ID,
		&i.MomentID,
		&i.MentionedUserID,
		&i.DisplayName,
		&i.RemovedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMomentMention = `-- name: DeleteMomentMention :exec
DELETE FROM moment_mentions
WHERE id = $1
    AND moment_id = $2
`

type DeleteMomentMentionParams struct {
	ID       uuid.UUID
	MomentID uuid.UUID
}

// The Moment's owner deleting a mention they added by mistake — distinct
// from RemoveMomentMention, which is the mentioned user leaving on
// their own initiative.
func (q *Queries) DeleteMomentMention(ctx context.Context, arg DeleteMomentMentionParams) error {
	_, err := q.db.Exec(ctx, deleteMomentMention, arg.ID, arg.MomentID)
	return err
}

const isUserActivelyMentioned = `-- name: IsUserActivelyMentioned :one
SELECT EXISTS(
    SELECT 1
    FROM moment_mentions
    WHERE moment_id = $1
        AND mentioned_user_id = $2
        AND removed_at IS NULL
) AS mentioned
`

type IsUserActivelyMentionedParams struct {
	MomentID        uuid.UUID
	MentionedUserID pgtype.UUID
}

// Backs the mention-context half of ResponseAccessChecker.ResolveAudience:
// whether userID may act/read in a Moment's mention context (circle_id
// IS NULL comments/reactions) as something other than its owner.
func (q *Queries) IsUserActivelyMentioned(ctx context.Context, arg IsUserActivelyMentionedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserActivelyMentioned, arg.MomentID, arg.MentionedUserID)
	var mentioned bool
	err := row.Scan(&mentioned)
	return mentioned, err
}

const listMentionedMomentsByUserID = `-- name: ListMentionedMomentsByUserID :many
SELECT moments.id, moments.user_id, moments.thread_id, moments.origin, moments.occurred_at, moments.occurred_local, moments.occurred_utc_offset_minutes, moments.occurred_on, moments.recorded_at, moments.settling_time, moments.note, moments.color_hex, moments.place_name, moments.latitude, moments.longitude, moments.search_document, moments.client_id, moments.last_viewed_at, moments.created_at, moments.updated_at, moments.deleted_at
FROM moment_mentions
    JOIN moments ON moments.id = moment_mentions.moment_id
WHERE moment_mentions.mentioned_user_id = $1
    AND moment_mentions.removed_at IS NULL
    AND moments.deleted_at IS NULL
ORDER BY moments.occurred_at DESC
LIMIT $3
OFFSET $2
`

type ListMentionedMomentsByUserIDParams struct {
	MentionedUserID pgtype.UUID
	PageOffset      int32
	PageLimit       int32
}

// "Mentioned Moments" (FEATURES.md, Looking Back): every Moment the
// user has ever been mentioned in, newest occurrence first.
func (q *Queries) ListMentionedMomentsByUserID(ctx context.Context, arg ListMentionedMomentsByUserIDParams) ([]Moment, error) {
	rows, err := q.db.Query(ctx, listMentionedMomentsByUserID, arg.MentionedUserID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Moment{}
	for rows.Next() {
		var i Moment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ThreadID,
			&i.Origin,
			&i.OccurredAt,
			&i.OccurredLocal,
			&i.OccurredUtcOffsetMinutes,
			&i.OccurredOn,
			&i.RecordedAt,
			&i.SettlingTime,
			&i.Note,
			&i.ColorHex,
			&i.PlaceName,
			&i.Latitude,
			&i.Longitude,
			&i.SearchDocument,
			&i.ClientID,
			&i.LastViewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMomentMentionsByMomentID = `-- name: ListMomentMentionsByMomentID :many
SELECT id, moment_id, mentioned_user_id, display_name, removed_at, created_at
FROM moment_mentions
WHERE moment_id = $1
    AND removed_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListMomentMentionsByMomentID(ctx context.Context, momentID uuid.UUID) ([]MomentMention, error) {
	rows, err := q.db.Query(ctx, listMomentMentionsByMomentID, momentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MomentMention{}
	for rows.Next() {
		var i MomentMention
		if err := rows.Scan(
			&i.ID,
			&i.MomentID,
			&i.MentionedUserID,
			&i.DisplayName,
			&i.RemovedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMomentMention = `-- name: RemoveMomentMention :exec
UPDATE moment_mentions
SET removed_at = NOW()
WHERE moment_id = $1
    AND mentioned_user_id = $2
    AND removed_at IS NULL
`

type RemoveMomentMentionParams struct {
	MomentID        uuid.UUID
	MentionedUserID pgtype.UUID
}

// "Leaving a mention": the mentioned user removes themselves. The
// Moment stays with its owner, unchanged apart from this — see
// FEATURES.md, Leaving a mention.
func (q *Queries) RemoveMomentMention(ctx context.Context, arg RemoveMomentMentionParams) error {
	_, err := q.db.Exec(ctx, removeMomentMention, arg.MomentID, arg.MentionedUserID)
	return err
}
