// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countNotifications = `-- name: CountNotifications :one
SELECT COUNT(*)::bigint
FROM notifications
WHERE user_id = $1
    AND deliver_after <= NOW()
`

// Total visible rows, for ListNotifications' pagination footer.
func (q *Queries) CountNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNotifications, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*)::bigint
FROM notifications
WHERE user_id = $1
    AND deliver_after <= NOW()
    AND read_at IS NULL
`

// Backs the header bell badge.
func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications(
    user_id, kind, actor_user_id,
    moment_id, thread_id, commitment_id, commitment_occurrence_id,
    circle_id, circle_invite_id, circle_join_request_id,
    recap_id, resurfacing_id,
    payload, deliver_after
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10,
    $11, $12,
    $13, $14
)
RETURNING id, user_id, kind, actor_user_id, moment_id, thread_id, commitment_id, commitment_occurrence_id, circle_id, circle_invite_id, circle_join_request_id, recap_id, resurfacing_id, payload, deliver_after, delivered_at, read_at, created_at
`

type CreateNotificationParams struct {
	UserID                 uuid.UUID
	Kind                   NotificationKind
	ActorUserID            pgtype.UUID
	MomentID               pgtype.UUID
	ThreadID               pgtype.UUID
	CommitmentID           pgtype.UUID
	CommitmentOccurrenceID pgtype.UUID
	CircleID               pgtype.UUID
	CircleInviteID         pgtype.UUID
	CircleJoinRequestID    pgtype.UUID
	RecapID                pgtype.UUID
	ResurfacingID          pgtype.UUID
	Payload                []byte
	DeliverAfter           pgtype.Timestamptz
}

// One row per deliverable alert. All subject columns are nullable and the
// caller only ever populates the one(s) relevant to kind — see
// entity.Notification's own field comments for which subject goes with
// which kind. deliver_after defaults to NOW() unless the caller is
// honoring quiet hours, in which case it's pushed forward by the usecase
// before this query runs.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Kind,
		arg.ActorUserID,
		arg.MomentID,
		arg.ThreadID,
		arg.CommitmentID,
		arg.CommitmentOccurrenceID,
		arg.CircleID,
		arg.CircleInviteID,
		arg.CircleJoinRequestID,
		arg.RecapID,
		arg.ResurfacingID,
		arg.Payload,
		arg.DeliverAfter,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.ActorUserID,
		&i.MomentID,
		&i.ThreadID,
		&i.CommitmentID,
		&i.CommitmentOccurrenceID,
		&i.CircleID,
		&i.CircleInviteID,
		&i.CircleJoinRequestID,
		&i.RecapID,
		&i.ResurfacingID,
		&i.Payload,
		&i.DeliverAfter,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsByUserID = `-- name: ListNotificationsByUserID :many
SELECT id, user_id, kind, actor_user_id, moment_id, thread_id, commitment_id, commitment_occurrence_id, circle_id, circle_invite_id, circle_join_request_id, recap_id, resurfacing_id, payload, deliver_after, delivered_at, read_at, created_at
FROM notifications
WHERE user_id = $1
    AND deliver_after <= NOW()
ORDER BY created_at DESC
LIMIT $3
OFFSET $2
`

type ListNotificationsByUserIDParams struct {
	UserID     uuid.UUID
	PageOffset int32
	PageLimit  int32
}

// The in-app notification feed: everything past its deliver_after (quiet
// hours held rows are simply not yet visible), newest first. Uses
// idx_notifications_user_created_at.
func (q *Queries) ListNotificationsByUserID(ctx context.Context, arg ListNotificationsByUserIDParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUserID, arg.UserID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.ActorUserID,
			&i.MomentID,
			&i.ThreadID,
			&i.CommitmentID,
			&i.CommitmentOccurrenceID,
			&i.CircleID,
			&i.CircleInviteID,
			&i.CircleJoinRequestID,
			&i.RecapID,
			&i.ResurfacingID,
			&i.Payload,
			&i.DeliverAfter,
			&i.DeliveredAt,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read_at = NOW()
WHERE user_id = $1
    AND deliver_after <= NOW()
    AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET read_at = NOW()
WHERE id = $1
    AND user_id = $2
    AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Owner-scoped; a WHERE clause matching zero rows (already read, wrong
// owner, or not found) is a silent no-op.
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}
