// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddMomentImage(ctx context.Context, arg AddMomentImageParams) (MomentImage, error)
	AddThreadImage(ctx context.Context, arg AddThreadImageParams) (ThreadImage, error)
	ArchiveThread(ctx context.Context, arg ArchiveThreadParams) error
	// Total matching row count for SearchThreads, ignoring
	// page_limit/page_offset — used to compute pagination metadata.
	CountSearchThreads(ctx context.Context, arg CountSearchThreadsParams) (int64, error)
	CreateCommitment(ctx context.Context, arg CreateCommitmentParams) (Commitment, error)
	// Archive a Commitment's values before it's changed or retired.
	CreateCommitmentHistory(ctx context.Context, arg CreateCommitmentHistoryParams) (CommitmentHistory, error)
	CreateCredentialUserAccount(ctx context.Context, arg CreateCredentialUserAccountParams) (UserAccount, error)
	// "Export all my data" (FEATURES.md, Data Controls). Starts in
	// 'pending'; the export worker moves it through running -> ready/failed.
	CreateDataExport(ctx context.Context, userID uuid.UUID) (DataExport, error)
	// The manual/import capture path — origin distinguishes the two, but
	// both are ordinary, fully-editable Moments with no state (FEATURES.md:
	// "A manually captured Moment has no state"). Commitment-generated
	// Moments are created from commitment_occurrences instead, one
	// migration later, and never go through this query.
	//
	// ON CONFLICT mirrors uq_moments_user_client_id: a Moment captured
	// offline and synced twice (e.g. a flaky retry) is silently ignored
	// instead of erroring, so capture never shows a failure state for
	// something already recorded.
	CreateMoment(ctx context.Context, arg CreateMomentParams) (Moment, error)
	// display_name is a snapshot taken at mention time (see the column
	// comment): the caller resolves it from the mentioned user's current
	// name before calling this, it is not derived here.
	CreateMomentMention(ctx context.Context, arg CreateMomentMentionParams) (MomentMention, error)
	CreateOAuthUserAccount(ctx context.Context, arg CreateOAuthUserAccountParams) (UserAccount, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	// circle_id NULL creates a personal Thread owned by user_id; setting it
	// creates a collaborative Thread owned by the Circle instead (see the
	// header comment on the threads table).
	CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Idempotent: blocking someone already blocked is a no-op, not an error.
	CreateUserBlock(ctx context.Context, arg CreateUserBlockParams) error
	// Idempotent: muting someone already muted is a no-op, not an error.
	CreateUserMute(ctx context.Context, arg CreateUserMuteParams) error
	CreateUserVerification(ctx context.Context, arg CreateUserVerificationParams) (UserVerification, error)
	// Retire a Commitment entirely. The caller should archive it into
	// commitment_histories first. Existing Moments that referenced it keep
	// thread_id intact and just get commitment_id set to NULL (composite FK,
	// ON DELETE SET NULL (commitment_id)).
	DeleteCommitment(ctx context.Context, arg DeleteCommitmentParams) error
	// Called after the underlying file has been removed from storage.
	DeleteDataExport(ctx context.Context, id uuid.UUID) error
	// Periodic cleanup job, same pattern as
	// refresh_tokens.idx_refresh_tokens_expires_at.
	DeleteExpiredUserVerifications(ctx context.Context) (int64, error)
	DeleteMomentImage(ctx context.Context, arg DeleteMomentImageParams) error
	// The Moment's owner deleting a mention they added by mistake — distinct
	// from RemoveMomentMention, which is the mentioned user leaving on
	// their own initiative.
	DeleteMomentMention(ctx context.Context, arg DeleteMomentMentionParams) error
	DeleteThreadImage(ctx context.Context, arg DeleteThreadImageParams) error
	// Unlink a provider. user_id in the WHERE clause is a safety check so a
	// caller can't unlink someone else's account by guessing an id.
	DeleteUserAccount(ctx context.Context, arg DeleteUserAccountParams) error
	DeleteUserBlock(ctx context.Context, arg DeleteUserBlockParams) error
	DeleteUserMute(ctx context.Context, arg DeleteUserMuteParams) error
	DeleteUserVerification(ctx context.Context, id uuid.UUID) error
	// Invalidate any previously-issued pending codes before issuing a new
	// one for the same identifier (e.g. "resend OTP").
	DeleteUserVerificationsByIdentifier(ctx context.Context, identifier string) error
	GetCommitmentByID(ctx context.Context, arg GetCommitmentByIDParams) (Commitment, error)
	GetCredentialUserAccountByUserID(ctx context.Context, userID uuid.UUID) (UserAccount, error)
	// user_id in the WHERE clause doubles as an ownership check.
	GetDataExportByID(ctx context.Context, arg GetDataExportByIDParams) (DataExport, error)
	// GitHub-contribution-graph-style data for Rhythms: Moment count per
	// calendar day. Buckets by occurred_on — the local date where each
	// Moment happened — never by the viewer's current timezone, per the
	// occurred_on column comment in the archive schema migration.
	GetHeatmapData(ctx context.Context, arg GetHeatmapDataParams) ([]GetHeatmapDataRow, error)
	// Lets the usecase avoid queuing a duplicate export while one is
	// already pending/running for this user.
	GetLatestActiveDataExportByUserID(ctx context.Context, userID uuid.UUID) (DataExport, error)
	// user_id in the WHERE clause doubles as an ownership check. A Moment
	// reached via a mention or a Circle share is authorized through
	// moment_mentions/moment_circles instead — see those query files.
	GetMomentByID(ctx context.Context, arg GetMomentByIDParams) (Moment, error)
	GetRefreshTokenByTokenHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	// Raw data for the Time to Tell chart (FEATURES.md, Rhythms): how long
	// a Moment took to settle into a record. Scoped to origin = 'manual'
	// because Time to Tell is explicitly a manual-Moment stat and must
	// never be merged with, or presented alongside, Commitment adherence
	// (a separate punctuality measurement that will live on
	// commitment_occurrences).
	GetSettlingTimeStats(ctx context.Context, userID uuid.UUID) ([]GetSettlingTimeStatsRow, error)
	// No ownership/membership filter — callers on a collaborative Thread
	// must authorize separately (see GetThreadWithAccess) since access
	// there is governed by circle_members, not user_id.
	GetThreadByID(ctx context.Context, id uuid.UUID) (Thread, error)
	// "Can this viewer reach this Thread at all" — true for the Thread's
	// creator, and for any active member of the Circle that owns it when
	// it's collaborative.
	GetThreadWithAccess(ctx context.Context, arg GetThreadWithAccessParams) (Thread, error)
	// Login lookup: OAuth callback (provider_id, account_id from the
	// provider) or credential login (provider_id = 'credential', account_id
	// = whatever convention the app uses, e.g. the user's id or email).
	GetUserAccountByProvider(ctx context.Context, arg GetUserAccountByProviderParams) (UserAccount, error)
	// Case-insensitive lookup, matches uq_users_email_lower.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// Case-insensitive lookup, matches uq_users_username_lower. Backs
	// @mention resolution and "invite by entering their username" (Circle
	// Invite) — callers must additionally check discoverable_by_username
	// for the invite path, since a mentionable user may still opt out of
	// being found by handle.
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// Validate an incoming OTP/token. The app should still delete it (see
	// DeleteUserVerification) in the same transaction to prevent reuse.
	GetValidUserVerification(ctx context.Context, arg GetValidUserVerificationParams) (UserVerification, error)
	HardDeleteThread(ctx context.Context, arg HardDeleteThreadParams) error
	// Actually cascades into user_accounts/refresh_tokens/threads/moments/...
	// Only call this from the purge job, on rows already past their grace
	// period.
	HardDeleteUser(ctx context.Context, id uuid.UUID) error
	// Called after a wrong password. The usecase decides whether the
	// returned failed_login_attempts count crosses the configured
	// lockout threshold and, if so, calls LockCredentialUserAccount.
	IncrementFailedLoginAttempts(ctx context.Context, userID uuid.UUID) (UserAccount, error)
	// Blocking is symmetric in effect (see the migration's header comment
	// on user_blocks): this must gate every view/mention/comment/reaction
	// access check, tested both ways since only the blocker's row exists.
	IsBlockedEitherDirection(ctx context.Context, arg IsBlockedEitherDirectionParams) (bool, error)
	// Muting is one-directional and purely a view filter — only the
	// muter's own rendering changes, so this is never checked both ways
	// (compare user_blocks.IsBlockedEitherDirection).
	IsUserMuted(ctx context.Context, arg IsUserMutedParams) (bool, error)
	// Every live push target for a recipient — notifications queued in
	// `notifications` are delivered to each of these.
	ListActiveUserDevicesByUserID(ctx context.Context, userID uuid.UUID) ([]UserDevice, error)
	// "Blocked users" settings surface.
	ListBlockedUsersByBlockerID(ctx context.Context, blockerUserID uuid.UUID) ([]UserBlock, error)
	// Which Circles a personal Moment is currently shared into, for its
	// own edit/unshare UI.
	ListCircleIDsByMomentID(ctx context.Context, momentID uuid.UUID) ([]uuid.UUID, error)
	// "How has this Thread's commitments changed over time" view.
	ListCommitmentHistoryByThreadID(ctx context.Context, threadID uuid.UUID) ([]CommitmentHistory, error)
	// Can return more than one row: a Thread may carry several concurrent
	// Commitments (e.g. a morning one and an evening one), each with its own
	// recurrence rule.
	ListCommitmentsByThreadID(ctx context.Context, threadID uuid.UUID) ([]Commitment, error)
	// Feed for the scheduler worker: every Commitment belonging to a
	// non-deleted Thread. The worker evaluates cron_expression/timezone
	// itself and calls moments.CreateCommittedMoment when a slot fires.
	ListCommitmentsForGeneration(ctx context.Context) ([]Commitment, error)
	// Export history, newest first.
	ListDataExportsByUserID(ctx context.Context, userID uuid.UUID) ([]DataExport, error)
	// Periodic cleanup job: exports whose download link has expired and
	// whose stored file can now be removed from object storage.
	ListExpiredReadyDataExports(ctx context.Context) ([]DataExport, error)
	// "Mentioned Moments" (FEATURES.md, Looking Back): every Moment the
	// user has ever been mentioned in, newest occurrence first.
	ListMentionedMomentsByUserID(ctx context.Context, arg ListMentionedMomentsByUserIDParams) ([]Moment, error)
	ListMomentImagesByMomentID(ctx context.Context, momentID uuid.UUID) ([]MomentImage, error)
	ListMomentMentionsByMomentID(ctx context.Context, momentID uuid.UUID) ([]MomentMention, error)
	// A single Thread's browsable timeline. No user_id filter: a
	// collaborative Thread holds Moments captured by several members, and
	// access to the Thread itself is checked upstream (see
	// threads.GetThreadWithAccess).
	ListMomentsByThreadID(ctx context.Context, arg ListMomentsByThreadIDParams) ([]Moment, error)
	// The personal archive timeline: every Moment this user owns, newest
	// occurrence first.
	ListMomentsByUserID(ctx context.Context, arg ListMomentsByUserIDParams) ([]Moment, error)
	// Echoes same-day-and-month flashback. The caller computes the IN-list
	// of prior-year occurred_on dates for "today" (e.g. every August 4th
	// going back); matching against occurred_on lets
	// idx_moments_user_occurred_on serve this directly instead of an
	// expression index on extract(month/day) — see that index's comment.
	ListMomentsOnDates(ctx context.Context, arg ListMomentsOnDatesParams) ([]Moment, error)
	// Personal Moments shared into this Circle via the mention flow.
	// Combined with the Circle's own collaborative-Thread Moments
	// (threads.circle_id), this is the Circle's Album (FEATURES.md,
	// Looking Back).
	ListMomentsSharedToCircle(ctx context.Context, arg ListMomentsSharedToCircleParams) ([]ListMomentsSharedToCircleRow, error)
	// "Muted users" settings surface.
	ListMutedUsersByMuterID(ctx context.Context, muterUserID uuid.UUID) ([]UserMute, error)
	// The "My Threads" list: Threads this user created that are not owned
	// by a Circle.
	ListPersonalThreadsByUserID(ctx context.Context, userID uuid.UUID) ([]Thread, error)
	ListThreadImagesByThreadID(ctx context.Context, threadID uuid.UUID) ([]ThreadImage, error)
	// A Circle's collaborative Threads.
	ListThreadsByCircleID(ctx context.Context, circleID pgtype.UUID) ([]Thread, error)
	// "Linked accounts" list in account settings.
	ListUserAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]UserAccount, error)
	// For a purge job: pass purge_before = NOW() - INTERVAL '30 days' (or
	// whatever grace period is chosen) from the application.
	ListUsersPendingPurge(ctx context.Context, purgeBefore pgtype.Timestamptz) ([]User, error)
	LockCredentialUserAccount(ctx context.Context, arg LockCredentialUserAccountParams) error
	MarkDataExportFailed(ctx context.Context, arg MarkDataExportFailedParams) error
	MarkDataExportReady(ctx context.Context, arg MarkDataExportReadyParams) error
	MarkDataExportRunning(ctx context.Context, id uuid.UUID) error
	// "Leaving a mention": the mentioned user removes themselves. The
	// Moment stays with its owner, unchanged apart from this — see
	// FEATURES.md, Leaving a mention.
	RemoveMomentMention(ctx context.Context, arg RemoveMomentMentionParams) error
	// Called after a successful login to clear any accumulated failures.
	ResetFailedLoginAttempts(ctx context.Context, userID uuid.UUID) error
	RestoreMoment(ctx context.Context, arg RestoreMomentParams) error
	RestoreThread(ctx context.Context, arg RestoreThreadParams) error
	RestoreUser(ctx context.Context, id uuid.UUID) error
	RevokeAllRefreshTokensByUserID(ctx context.Context, userID uuid.UUID) error
	// Logout-everywhere / account deletion.
	RevokeAllUserDevicesByUserID(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error
	// Unregister a single device (e.g. explicit logout on that device).
	RevokeUserDevice(ctx context.Context, arg RevokeUserDeviceParams) error
	// Rotate is a compare-and-swap: it only succeeds if the row is still
	// active (revoked_at IS NULL) when this statement runs. If two
	// concurrent Refresh requests race on the same token, only one can
	// win; the loser gets 0 affected rows and the usecase rolls back its
	// whole transaction.
	RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (int64, error)
	// Global text Search (FEATURES.md, Looking Back) over one user's own
	// Moments, backed by idx_moments_search_document.
	SearchMoments(ctx context.Context, arg SearchMomentsParams) ([]Moment, error)
	// Search & filter personal threads for the authenticated user's thread
	// list. All filters are optional (NULL = "don't filter on this"):
	//   - name: case-insensitive partial match (ILIKE) against threads.name
	//   - archived: exact match against (archived_at IS NOT NULL)
	// Ordered by sort_order then newest-first; paginated via
	// page_limit / page_offset.
	SearchThreads(ctx context.Context, arg SearchThreadsParams) ([]Thread, error)
	SetUserEmailVerified(ctx context.Context, id uuid.UUID) error
	// The "Share to circle too?" step of the mention flow (FEATURES.md,
	// Mention) — never a standalone "share" action. Idempotent: sharing
	// into a Circle it's already shared to is a no-op.
	ShareMomentToCircle(ctx context.Context, arg ShareMomentToCircleParams) (MomentCircle, error)
	// Per FEATURES.md Lifecycle & Deletion, the caller must also remove
	// this Moment's shares/mentions/comments/reactions in the same
	// transaction — deleting a Moment removes it everywhere, not just from
	// the owner's own archive.
	SoftDeleteMoment(ctx context.Context, arg SoftDeleteMomentParams) error
	SoftDeleteThread(ctx context.Context, arg SoftDeleteThreadParams) error
	// Starts the recovery grace period. Caller should also revoke all
	// refresh tokens (see refresh_tokens.RevokeAllRefreshTokensByUserID) in
	// the same transaction.
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	// Owner-only, per the last_viewed_at column comment: this is not a read
	// receipt and never runs for any viewer other than moments.user_id.
	TouchMomentLastViewed(ctx context.Context, arg TouchMomentLastViewedParams) error
	TouchUserDeviceLastSeen(ctx context.Context, id uuid.UUID) error
	UnarchiveThread(ctx context.Context, arg UnarchiveThreadParams) error
	UnshareMomentFromCircle(ctx context.Context, arg UnshareMomentFromCircleParams) error
	// Update in place (same id) so existing moments.commitment_id links stay
	// valid. The caller must insert a row into commitment_histories with the
	// OLD cron_expression/timezone BEFORE calling this, in the same
	// transaction.
	UpdateCommitment(ctx context.Context, arg UpdateCommitmentParams) (Commitment, error)
	// A Moment is never final (FEATURES.md, "Moments are never final") —
	// note, color, location, and even occurred_at may be edited at any
	// point, including years later; occurred_at is the one timestamp the
	// user is the authority on (see the Time table). recorded_at is never
	// touched here: it is stamped once, at capture, and stays fixed.
	UpdateMoment(ctx context.Context, arg UpdateMomentParams) (Moment, error)
	// Called after a token refresh with the provider.
	UpdateOAuthUserAccountTokens(ctx context.Context, arg UpdateOAuthUserAccountTokensParams) error
	UpdateThread(ctx context.Context, arg UpdateThreadParams) (Thread, error)
	// Manual reordering on the Thread list; the archive itself always
	// stays ordered by occurred_at regardless of this value.
	UpdateThreadSortOrder(ctx context.Context, arg UpdateThreadSortOrderParams) error
	// Password change / reset flow.
	UpdateUserAccountPasswordHash(ctx context.Context, arg UpdateUserAccountPasswordHashParams) error
	// Social Interaction Controls + Data Controls (FEATURES.md, Privacy &
	// Control) — the account-level privacy toggles, separate from profile
	// content so a settings screen can save them independently.
	UpdateUserPrivacySettings(ctx context.Context, arg UpdateUserPrivacySettingsParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	// Registering a push token. Re-registering an existing active token
	// (reinstall, re-login on the same device) refreshes ownership and
	// last_seen_at instead of failing uq_user_devices_push_token.
	UpsertUserDevice(ctx context.Context, arg UpsertUserDeviceParams) (UserDevice, error)
}

var _ Querier = (*Queries)(nil)
