// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddActivityCaptureImage(ctx context.Context, arg AddActivityCaptureImageParams) (ActivityCaptureImage, error)
	AddActivityImage(ctx context.Context, arg AddActivityImageParams) (ActivityImage, error)
	// User checks an awaiting item off as done or not done, optionally with
	// a moment (content/color). "WHERE status = 'awaiting'" avoids a race
	// against the timeout job flipping the same row at the same time.
	ConfirmActivityCapture(ctx context.Context, arg ConfirmActivityCaptureParams) (ActivityCapture, error)
	// Total matching row count for SearchActivities, ignoring
	// page_limit/page_offset — used to compute pagination metadata.
	CountSearchActivities(ctx context.Context, arg CountSearchActivitiesParams) (int64, error)
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	CreateActivitySchedule(ctx context.Context, arg CreateActivityScheduleParams) (ActivitySchedule, error)
	// Archive a schedule's values before it's changed or retired.
	CreateActivityScheduleHistory(ctx context.Context, arg CreateActivityScheduleHistoryParams) (ActivityScheduleHistory, error)
	CreateCredentialUserAccount(ctx context.Context, arg CreateCredentialUserAccountParams) (UserAccount, error)
	// User-logged item for a non-fixed-schedule activity, created directly
	// as 'captured' or 'missed' (never 'awaiting'). occurred_at may be
	// backdated by the user; scheduled_at/schedule_id stay NULL.
	CreateManualActivityCapture(ctx context.Context, arg CreateManualActivityCaptureParams) (ActivityCapture, error)
	CreateOAuthUserAccount(ctx context.Context, arg CreateOAuthUserAccountParams) (UserAccount, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	// Auto-generated by the scheduler worker when a fixed schedule fires.
	// occurred_at is set equal to scheduled_at at creation time.
	// ON CONFLICT mirrors uq_activity_captures_activity_scheduled_at exactly,
	// so a duplicate generation attempt (e.g. two worker instances racing)
	// is silently ignored instead of erroring.
	CreateScheduledActivityCapture(ctx context.Context, arg CreateScheduledActivityCaptureParams) (ActivityCapture, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserVerification(ctx context.Context, arg CreateUserVerificationParams) (UserVerification, error)
	DeleteActivityCaptureImage(ctx context.Context, arg DeleteActivityCaptureImageParams) error
	DeleteActivityImage(ctx context.Context, arg DeleteActivityImageParams) error
	// Retire a schedule entirely. The caller should archive it into
	// activity_schedule_histories first. Existing activity_captures that
	// referenced it keep activity_id intact and just get schedule_id set to
	// NULL (composite FK, ON DELETE SET NULL (schedule_id)).
	DeleteActivitySchedule(ctx context.Context, arg DeleteActivityScheduleParams) error
	// Periodic cleanup job.
	DeleteExpiredUserVerifications(ctx context.Context) (int64, error)
	// Unlink a provider. user_id in the WHERE clause is a safety check so a
	// caller can't unlink someone else's account by guessing an id.
	DeleteUserAccount(ctx context.Context, arg DeleteUserAccountParams) error
	DeleteUserVerification(ctx context.Context, id uuid.UUID) error
	// Invalidate any previously-issued pending codes before issuing a new
	// one for the same identifier (e.g. "resend OTP").
	DeleteUserVerificationsByIdentifier(ctx context.Context, identifier string) error
	// user_id in the WHERE clause doubles as an ownership check.
	GetActivityByID(ctx context.Context, arg GetActivityByIDParams) (Activity, error)
	GetActivityCaptureByID(ctx context.Context, id uuid.UUID) (ActivityCapture, error)
	GetActivityScheduleByID(ctx context.Context, arg GetActivityScheduleByIDParams) (ActivitySchedule, error)
	// "Waktu muncul -> konfirmasi" chart for one fixed-schedule activity:
	// how long after scheduled_at did the user actually confirm each item.
	GetConfirmationDelayStats(ctx context.Context, activityID uuid.UUID) ([]GetConfirmationDelayStatsRow, error)
	GetCredentialUserAccountByUserID(ctx context.Context, userID uuid.UUID) (UserAccount, error)
	// GitHub-contribution-graph-style data: item count per day, bucketed in
	// the user's own timezone (users.timezone), across all of that user's
	// activities, between [from_date, to_date).
	GetHeatmapData(ctx context.Context, arg GetHeatmapDataParams) ([]GetHeatmapDataRow, error)
	GetRefreshTokenByTokenHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	// Login lookup: OAuth callback (provider_id, account_id from the
	// provider) or credential login (provider_id = 'credential', account_id
	// = whatever convention the app uses, e.g. the user's id or email).
	GetUserAccountByProvider(ctx context.Context, arg GetUserAccountByProviderParams) (UserAccount, error)
	// Case-insensitive lookup, matches uq_users_email_lower.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// Validate an incoming OTP/token. The app should still delete it (see
	// DeleteUserVerification) in the same transaction to prevent reuse.
	GetValidUserVerification(ctx context.Context, arg GetValidUserVerificationParams) (UserVerification, error)
	HardDeleteActivity(ctx context.Context, arg HardDeleteActivityParams) error
	// Actually cascades into user_accounts/user_sessions/activities/... Only
	// call this from the purge job, on rows already past their grace period.
	HardDeleteUser(ctx context.Context, id uuid.UUID) error
	// Can return more than one row: an activity may have multiple
	// concurrently active schedules (e.g. "pagi" and "sore").
	ListActiveSchedulesByActivityID(ctx context.Context, activityID uuid.UUID) ([]ActivitySchedule, error)
	// Feed for the scheduler worker: every active schedule belonging to a
	// non-deleted, is_fixed_schedule = true activity. The worker evaluates
	// cron_expression/timezone itself and calls
	// activity_captures.CreateScheduledActivityCapture when a slot fires.
	ListActiveSchedulesForGeneration(ctx context.Context) ([]ActivitySchedule, error)
	ListActivitiesByUserID(ctx context.Context, userID uuid.UUID) ([]Activity, error)
	ListActivityCaptureImagesByItemID(ctx context.Context, activityCaptureID uuid.UUID) ([]ActivityCaptureImage, error)
	// Timeline/history view for one activity, newest occurrence first.
	ListActivityCapturesByActivityID(ctx context.Context, arg ListActivityCapturesByActivityIDParams) ([]ActivityCapture, error)
	ListActivityImagesByActivityID(ctx context.Context, activityID uuid.UUID) ([]ActivityImage, error)
	// Candidates the timeout worker is about to flip to 'missed'; useful for
	// notifying the user beforehand, logging, etc. Mirrors the condition in
	// MarkOverdueItemsAsMissed below.
	ListAwaitingItemsPastDeadline(ctx context.Context) ([]ActivityCapture, error)
	// "How has this activity's schedule changed over time" view.
	ListScheduleHistoryByActivityID(ctx context.Context, activityID uuid.UUID) ([]ActivityScheduleHistory, error)
	// "Linked accounts" list in account settings.
	ListUserAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]UserAccount, error)
	// For a purge job: pass purge_before = NOW() - INTERVAL '30 days' (or
	// whatever grace period is chosen) from the application.
	ListUsersPendingPurge(ctx context.Context, purgeBefore pgtype.Timestamptz) ([]User, error)
	// The timeout job itself: bulk-flip every 'awaiting' item whose deadline
	// (scheduled_at + activities.confirmation_timeout_minutes) has passed.
	// Run this on a schedule (e.g. every minute).
	MarkOverdueItemsAsMissed(ctx context.Context) (int64, error)
	RestoreActivity(ctx context.Context, arg RestoreActivityParams) error
	RestoreActivityCapture(ctx context.Context, id uuid.UUID) error
	RestoreUser(ctx context.Context, id uuid.UUID) error
	RevokeAllRefreshTokensByUserID(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error
	// Rotate is a compare-and-swap: it only succeeds if the row is still
	// active (revoked_at IS NULL) when this statement runs. If two
	// concurrent Refresh requests race on the same token, only one can
	// win; the loser gets 0 affected rows and the usecase rolls back its
	// whole transaction.
	RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (int64, error)
	// Search & filter activities for the authenticated user's activity list.
	// All filters are optional (NULL = "don't filter on this"):
	//   - name: case-insensitive partial match (ILIKE) against activities.name
	//   - is_fixed_schedule: exact boolean match
	// Ordered newest-first; paginated via page_limit / page_offset.
	SearchActivities(ctx context.Context, arg SearchActivitiesParams) ([]Activity, error)
	// Toggling this does NOT itself touch activity_schedules — if flipping
	// to false, the app should separately retire/archive existing schedules
	// (see activity_schedules.sql) so the generator job actually stops.
	SetActivityFixedSchedule(ctx context.Context, arg SetActivityFixedScheduleParams) error
	SetUserEmailVerified(ctx context.Context, id uuid.UUID) error
	SoftDeleteActivity(ctx context.Context, arg SoftDeleteActivityParams) error
	SoftDeleteActivityCapture(ctx context.Context, id uuid.UUID) error
	// Starts the recovery grace period. Caller should also revoke all
	// sessions (see user_sessions.DeleteAllSessionsByUserID) in the same
	// transaction.
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateActivity(ctx context.Context, arg UpdateActivityParams) (Activity, error)
	// Edit the logged moment (content/color) after the fact, without
	// touching status/confirmed_at.
	UpdateActivityCaptureMoment(ctx context.Context, arg UpdateActivityCaptureMomentParams) (ActivityCapture, error)
	// Update in place (same id) so existing activity_captures.schedule_id links
	// stay valid. The caller must insert a row into
	// activity_schedule_histories with the OLD cron_expression/timezone
	// BEFORE calling this, in the same transaction.
	UpdateActivitySchedule(ctx context.Context, arg UpdateActivityScheduleParams) (ActivitySchedule, error)
	// Called after a token refresh with the provider.
	UpdateOAuthUserAccountTokens(ctx context.Context, arg UpdateOAuthUserAccountTokensParams) error
	// Password change / reset flow.
	UpdateUserAccountPasswordHash(ctx context.Context, arg UpdateUserAccountPasswordHashParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
