// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: threads.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSearchThreads = `-- name: CountSearchThreads :one
SELECT COUNT(*)
FROM threads
WHERE user_id = $1
    AND deleted_at IS NULL
    AND (
        $2::text IS NULL
        OR name ILIKE '%' || $2::text || '%'
    )
    AND (
        $3::bool IS NULL
        OR has_commitment = $3::bool
    )
`

type CountSearchThreadsParams struct {
	UserID        uuid.UUID
	Name          pgtype.Text
	HasCommitment pgtype.Bool
}

// Total matching row count for SearchThreads, ignoring
// page_limit/page_offset — used to compute pagination metadata.
func (q *Queries) CountSearchThreads(ctx context.Context, arg CountSearchThreadsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchThreads, arg.UserID, arg.Name, arg.HasCommitment)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createThread = `-- name: CreateThread :one
INSERT INTO threads(
    user_id, name, description, has_commitment,
    color_hex, confirmation_timeout_minutes
) VALUES (
    $1, $2, $3, $4,
    $5, $6
)
RETURNING id, user_id, name, description, has_commitment, color_hex, confirmation_timeout_minutes, created_at, updated_at, deleted_at
`

type CreateThreadParams struct {
	UserID                     uuid.UUID
	Name                       string
	Description                pgtype.Text
	HasCommitment              bool
	ColorHex                   pgtype.Text
	ConfirmationTimeoutMinutes pgtype.Int4
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, createThread,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.HasCommitment,
		arg.ColorHex,
		arg.ConfirmationTimeoutMinutes,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.HasCommitment,
		&i.ColorHex,
		&i.ConfirmationTimeoutMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getThreadByID = `-- name: GetThreadByID :one
SELECT id, user_id, name, description, has_commitment, color_hex, confirmation_timeout_minutes, created_at, updated_at, deleted_at
FROM threads
WHERE id = $1
    AND user_id = $2
    AND deleted_at IS NULL
`

type GetThreadByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// user_id in the WHERE clause doubles as an ownership check.
func (q *Queries) GetThreadByID(ctx context.Context, arg GetThreadByIDParams) (Thread, error) {
	row := q.db.QueryRow(ctx, getThreadByID, arg.ID, arg.UserID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.HasCommitment,
		&i.ColorHex,
		&i.ConfirmationTimeoutMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteThread = `-- name: HardDeleteThread :exec
DELETE FROM threads
WHERE id = $1
    AND user_id = $2
`

type HardDeleteThreadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) HardDeleteThread(ctx context.Context, arg HardDeleteThreadParams) error {
	_, err := q.db.Exec(ctx, hardDeleteThread, arg.ID, arg.UserID)
	return err
}

const listThreadsByUserID = `-- name: ListThreadsByUserID :many
SELECT id, user_id, name, description, has_commitment, color_hex, confirmation_timeout_minutes, created_at, updated_at, deleted_at
FROM threads
WHERE user_id = $1
    AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListThreadsByUserID(ctx context.Context, userID uuid.UUID) ([]Thread, error) {
	rows, err := q.db.Query(ctx, listThreadsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Thread{}
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.HasCommitment,
			&i.ColorHex,
			&i.ConfirmationTimeoutMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreThread = `-- name: RestoreThread :exec
UPDATE threads
SET deleted_at = NULL
WHERE id = $1
    AND user_id = $2
`

type RestoreThreadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RestoreThread(ctx context.Context, arg RestoreThreadParams) error {
	_, err := q.db.Exec(ctx, restoreThread, arg.ID, arg.UserID)
	return err
}

const searchThreads = `-- name: SearchThreads :many
SELECT id, user_id, name, description, has_commitment, color_hex, confirmation_timeout_minutes, created_at, updated_at, deleted_at
FROM threads
WHERE user_id = $1
    AND deleted_at IS NULL
    AND (
        $2::text IS NULL
        OR name ILIKE '%' || $2::text || '%'
    )
    AND (
        $3::bool IS NULL
        OR has_commitment = $3::bool
    )
ORDER BY created_at DESC
LIMIT $5
OFFSET $4
`

type SearchThreadsParams struct {
	UserID        uuid.UUID
	Name          pgtype.Text
	HasCommitment pgtype.Bool
	PageOffset    int32
	PageLimit     int32
}

// Search & filter threads for the authenticated user's thread list.
// All filters are optional (NULL = "don't filter on this"):
//   - name: case-insensitive partial match (ILIKE) against threads.name
//   - has_commitment: exact boolean match
//
// Ordered newest-first; paginated via page_limit / page_offset.
func (q *Queries) SearchThreads(ctx context.Context, arg SearchThreadsParams) ([]Thread, error) {
	rows, err := q.db.Query(ctx, searchThreads,
		arg.UserID,
		arg.Name,
		arg.HasCommitment,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Thread{}
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.HasCommitment,
			&i.ColorHex,
			&i.ConfirmationTimeoutMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setThreadHasCommitment = `-- name: SetThreadHasCommitment :exec
UPDATE threads
SET has_commitment = $1,
    updated_at = NOW()
WHERE id = $2
    AND user_id = $3
`

type SetThreadHasCommitmentParams struct {
	HasCommitment bool
	ID            uuid.UUID
	UserID        uuid.UUID
}

// Toggling this does NOT itself touch commitments — if flipping to
// false, the app should separately retire/archive existing commitments
// (see commitments.sql) so the generator job actually stops.
func (q *Queries) SetThreadHasCommitment(ctx context.Context, arg SetThreadHasCommitmentParams) error {
	_, err := q.db.Exec(ctx, setThreadHasCommitment, arg.HasCommitment, arg.ID, arg.UserID)
	return err
}

const softDeleteThread = `-- name: SoftDeleteThread :exec
UPDATE threads
SET deleted_at = NOW()
WHERE id = $1
    AND user_id = $2
    AND deleted_at IS NULL
`

type SoftDeleteThreadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) SoftDeleteThread(ctx context.Context, arg SoftDeleteThreadParams) error {
	_, err := q.db.Exec(ctx, softDeleteThread, arg.ID, arg.UserID)
	return err
}

const updateThread = `-- name: UpdateThread :one
UPDATE threads
SET name = $1,
    description = $2,
    color_hex = $3,
    confirmation_timeout_minutes = $4,
    updated_at = NOW()
WHERE id = $5
    AND user_id = $6
    AND deleted_at IS NULL
    RETURNING id, user_id, name, description, has_commitment, color_hex, confirmation_timeout_minutes, created_at, updated_at, deleted_at
`

type UpdateThreadParams struct {
	Name                       string
	Description                pgtype.Text
	ColorHex                   pgtype.Text
	ConfirmationTimeoutMinutes pgtype.Int4
	ID                         uuid.UUID
	UserID                     uuid.UUID
}

func (q *Queries) UpdateThread(ctx context.Context, arg UpdateThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, updateThread,
		arg.Name,
		arg.Description,
		arg.ColorHex,
		arg.ConfirmationTimeoutMinutes,
		arg.ID,
		arg.UserID,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.HasCommitment,
		&i.ColorHex,
		&i.ConfirmationTimeoutMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
