// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: thread_images.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addThreadImage = `-- name: AddThreadImage :one
INSERT INTO thread_images(thread_id, image_path, image_alt)
VALUES ($1, $2, $3)
RETURNING id, thread_id, image_path, image_alt, sort_order, created_at
`

type AddThreadImageParams struct {
	ThreadID  uuid.UUID
	ImagePath string
	ImageAlt  pgtype.Text
}

func (q *Queries) AddThreadImage(ctx context.Context, arg AddThreadImageParams) (ThreadImage, error) {
	row := q.db.QueryRow(ctx, addThreadImage, arg.ThreadID, arg.ImagePath, arg.ImageAlt)
	var i ThreadImage
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.ImagePath,
		&i.ImageAlt,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteThreadImage = `-- name: DeleteThreadImage :one
DELETE FROM thread_images
WHERE id = $1
    AND thread_id = $2
RETURNING id, thread_id, image_path, image_alt, sort_order, created_at
`

type DeleteThreadImageParams struct {
	ID       uuid.UUID
	ThreadID uuid.UUID
}

// Returns the deleted row (specifically image_path) so the caller can
// remove the matching storage object after the DB record is gone — see
// ThreadImageUsecase.DeleteThreadImage for the ordering rationale. No
// matching row (already deleted / wrong thread) surfaces as
// pgx.ErrNoRows, which the repository treats as a silent no-op, same as
// the :exec version this replaces.
func (q *Queries) DeleteThreadImage(ctx context.Context, arg DeleteThreadImageParams) (ThreadImage, error) {
	row := q.db.QueryRow(ctx, deleteThreadImage, arg.ID, arg.ThreadID)
	var i ThreadImage
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.ImagePath,
		&i.ImageAlt,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listThreadImagePathsByOwnerID = `-- name: ListThreadImagePathsByOwnerID :many
SELECT thread_images.image_path
FROM thread_images
    JOIN threads ON threads.id = thread_images.thread_id
WHERE threads.user_id = $1
    AND threads.deleted_at IS NULL
`

// Storage cleanup targets for account deletion — every image path
// belonging to a Thread this user owns, gathered before
// SoftDeleteThreadsByUserID runs (see UserUsecase.DeleteAccount).
func (q *Queries) ListThreadImagePathsByOwnerID(ctx context.Context, ownerUserID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listThreadImagePathsByOwnerID, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var image_path string
		if err := rows.Scan(&image_path); err != nil {
			return nil, err
		}
		items = append(items, image_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadImagesByThreadID = `-- name: ListThreadImagesByThreadID :many
SELECT id, thread_id, image_path, image_alt, sort_order, created_at
FROM thread_images
WHERE thread_id = $1
ORDER BY sort_order, created_at
`

func (q *Queries) ListThreadImagesByThreadID(ctx context.Context, threadID uuid.UUID) ([]ThreadImage, error) {
	rows, err := q.db.Query(ctx, listThreadImagesByThreadID, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThreadImage{}
	for rows.Next() {
		var i ThreadImage
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.ImagePath,
			&i.ImageAlt,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
