// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(name, username, email, timezone)
VALUES ($1, $2, $3, $4)
RETURNING id, name, username, email, email_verified, image_path, bio, timezone, created_at, updated_at, mention_policy, circle_invite_policy, discoverable_by_username, strip_photo_metadata, deleted_at
`

type CreateUserParams struct {
	Name     string
	Username pgtype.Text
	Email    string
	Timezone string
}

// username is nullable here: registration creates the account before the
// onboarding step (SetUsername) claims one.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.ImagePath,
		&i.Bio,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MentionPolicy,
		&i.CircleInvitePolicy,
		&i.DiscoverableByUsername,
		&i.StripPhotoMetadata,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, username, email, email_verified, image_path, bio, timezone, created_at, updated_at, mention_policy, circle_invite_policy, discoverable_by_username, strip_photo_metadata, deleted_at
FROM users
WHERE lower(email) = lower($1)
    AND deleted_at IS NULL
`

// Case-insensitive lookup, matches uq_users_email_lower.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.ImagePath,
		&i.Bio,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MentionPolicy,
		&i.CircleInvitePolicy,
		&i.DiscoverableByUsername,
		&i.StripPhotoMetadata,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, username, email, email_verified, image_path, bio, timezone, created_at, updated_at, mention_policy, circle_invite_policy, discoverable_by_username, strip_photo_metadata, deleted_at
FROM users
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.ImagePath,
		&i.Bio,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MentionPolicy,
		&i.CircleInvitePolicy,
		&i.DiscoverableByUsername,
		&i.StripPhotoMetadata,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, name, username, email, email_verified, image_path, bio, timezone, created_at, updated_at, mention_policy, circle_invite_policy, discoverable_by_username, strip_photo_metadata, deleted_at
FROM users
WHERE lower(username) = lower($1)
    AND deleted_at IS NULL
`

// Case-insensitive lookup, matches uq_users_username_lower. Backs
// @mention resolution and "invite by entering their username" (Circle
// Invite) — callers must additionally check discoverable_by_username
// for the invite path, since a mentionable user may still opt out of
// being found by handle.
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.ImagePath,
		&i.Bio,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MentionPolicy,
		&i.CircleInvitePolicy,
		&i.DiscoverableByUsername,
		&i.StripPhotoMetadata,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteUser = `-- name: HardDeleteUser :exec
DELETE FROM users
WHERE id = $1
`

// Actually cascades into user_accounts/refresh_tokens/threads/moments/...
// Only call this from the purge job, on rows already past their grace
// period.
func (q *Queries) HardDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteUser, id)
	return err
}

const listUsersPendingPurge = `-- name: ListUsersPendingPurge :many
SELECT id, name, username, email, email_verified, image_path, bio, timezone, created_at, updated_at, mention_policy, circle_invite_policy, discoverable_by_username, strip_photo_metadata, deleted_at
FROM users
WHERE deleted_at IS NOT NULL
    AND deleted_at < $1
`

// For a purge job: pass purge_before = NOW() - INTERVAL '30 days' (or
// whatever grace period is chosen) from the application.
func (q *Queries) ListUsersPendingPurge(ctx context.Context, purgeBefore pgtype.Timestamptz) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersPendingPurge, purgeBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Email,
			&i.EmailVerified,
			&i.ImagePath,
			&i.Bio,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MentionPolicy,
			&i.CircleInvitePolicy,
			&i.DiscoverableByUsername,
			&i.StripPhotoMetadata,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreUser = `-- name: RestoreUser :exec
UPDATE users
SET deleted_at = NULL
WHERE id = $1
`

func (q *Queries) RestoreUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreUser, id)
	return err
}

const setUserEmailVerified = `-- name: SetUserEmailVerified :exec
UPDATE users
SET email_verified = TRUE,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SetUserEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setUserEmailVerified, id)
	return err
}

const setUsername = `-- name: SetUsername :one
UPDATE users
SET username = $1,
    updated_at = NOW()
WHERE id = $2
    AND deleted_at IS NULL
    RETURNING id, name, username, email, email_verified, image_path, bio, timezone, created_at, updated_at, mention_policy, circle_invite_policy, discoverable_by_username, strip_photo_metadata, deleted_at
`

type SetUsernameParams struct {
	Username pgtype.Text
	ID       uuid.UUID
}

// Claims a username for an account that doesn't have one yet (the
// post-register onboarding step). uq_users_username_lower/
// chk_users_username_format still guard uniqueness/format at the DB
// level regardless of caller-side validation.
func (q *Queries) SetUsername(ctx context.Context, arg SetUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, setUsername, arg.Username, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.ImagePath,
		&i.Bio,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MentionPolicy,
		&i.CircleInvitePolicy,
		&i.DiscoverableByUsername,
		&i.StripPhotoMetadata,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
`

// Starts the recovery grace period. Caller should also revoke all
// refresh tokens (see refresh_tokens.RevokeAllRefreshTokensByUserID) in
// the same transaction.
func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUserPrivacySettings = `-- name: UpdateUserPrivacySettings :one
UPDATE users
SET mention_policy = $1,
    circle_invite_policy = $2,
    discoverable_by_username = $3,
    strip_photo_metadata = $4,
    updated_at = NOW()
WHERE id = $5
    AND deleted_at IS NULL
    RETURNING id, name, username, email, email_verified, image_path, bio, timezone, created_at, updated_at, mention_policy, circle_invite_policy, discoverable_by_username, strip_photo_metadata, deleted_at
`

type UpdateUserPrivacySettingsParams struct {
	MentionPolicy          AudiencePolicy
	CircleInvitePolicy     AudiencePolicy
	DiscoverableByUsername bool
	StripPhotoMetadata     bool
	ID                     uuid.UUID
}

// Social Interaction Controls + Data Controls (FEATURES.md, Privacy &
// Control) — the account-level privacy toggles, separate from profile
// content so a settings screen can save them independently.
func (q *Queries) UpdateUserPrivacySettings(ctx context.Context, arg UpdateUserPrivacySettingsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPrivacySettings,
		arg.MentionPolicy,
		arg.CircleInvitePolicy,
		arg.DiscoverableByUsername,
		arg.StripPhotoMetadata,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.ImagePath,
		&i.Bio,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MentionPolicy,
		&i.CircleInvitePolicy,
		&i.DiscoverableByUsername,
		&i.StripPhotoMetadata,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET name = $1,
    username = $2,
    image_path = $3,
    bio = $4,
    timezone = $5,
    updated_at = NOW()
WHERE id = $6
    AND deleted_at IS NULL
    RETURNING id, name, username, email, email_verified, image_path, bio, timezone, created_at, updated_at, mention_policy, circle_invite_policy, discoverable_by_username, strip_photo_metadata, deleted_at
`

type UpdateUserProfileParams struct {
	Name      string
	Username  pgtype.Text
	ImagePath pgtype.Text
	Bio       pgtype.Text
	Timezone  string
	ID        uuid.UUID
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.Name,
		arg.Username,
		arg.ImagePath,
		arg.Bio,
		arg.Timezone,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.ImagePath,
		&i.Bio,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MentionPolicy,
		&i.CircleInvitePolicy,
		&i.DiscoverableByUsername,
		&i.StripPhotoMetadata,
		&i.DeletedAt,
	)
	return i, err
}
