// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCredentialUserAccount = `-- name: CreateCredentialUserAccount :one
INSERT INTO user_accounts(user_id, account_id, provider_id, password_hash)
VALUES ($1, $2, 'credential', $3)
RETURNING id, user_id, account_id, provider_id, access_token, refresh_token, access_token_expires_at, refresh_token_expires_at, scope, id_token, password_hash, created_at, updated_at, failed_login_attempts, locked_until
`

type CreateCredentialUserAccountParams struct {
	UserID       uuid.UUID
	AccountID    string
	PasswordHash pgtype.Text
}

func (q *Queries) CreateCredentialUserAccount(ctx context.Context, arg CreateCredentialUserAccountParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, createCredentialUserAccount, arg.UserID, arg.AccountID, arg.PasswordHash)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.ProviderID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.IDToken,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const createOAuthUserAccount = `-- name: CreateOAuthUserAccount :one
INSERT INTO user_accounts(
    user_id, account_id, provider_id,
    access_token, refresh_token,
    access_token_expires_at, refresh_token_expires_at,
    scope, id_token
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9
)
RETURNING id, user_id, account_id, provider_id, access_token, refresh_token, access_token_expires_at, refresh_token_expires_at, scope, id_token, password_hash, created_at, updated_at, failed_login_attempts, locked_until
`

type CreateOAuthUserAccountParams struct {
	UserID                uuid.UUID
	AccountID             string
	ProviderID            AuthProviderID
	AccessToken           pgtype.Text
	RefreshToken          pgtype.Text
	AccessTokenExpiresAt  pgtype.Timestamptz
	RefreshTokenExpiresAt pgtype.Timestamptz
	Scope                 pgtype.Text
	IDToken               pgtype.Text
}

func (q *Queries) CreateOAuthUserAccount(ctx context.Context, arg CreateOAuthUserAccountParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthUserAccount,
		arg.UserID,
		arg.AccountID,
		arg.ProviderID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.AccessTokenExpiresAt,
		arg.RefreshTokenExpiresAt,
		arg.Scope,
		arg.IDToken,
	)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.ProviderID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.IDToken,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const deleteUserAccount = `-- name: DeleteUserAccount :exec
DELETE FROM user_accounts
WHERE id = $1
    AND user_id = $2
`

type DeleteUserAccountParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Unlink a provider. user_id in the WHERE clause is a safety check so a
// caller can't unlink someone else's account by guessing an id.
func (q *Queries) DeleteUserAccount(ctx context.Context, arg DeleteUserAccountParams) error {
	_, err := q.db.Exec(ctx, deleteUserAccount, arg.ID, arg.UserID)
	return err
}

const getCredentialUserAccountByUserID = `-- name: GetCredentialUserAccountByUserID :one
SELECT id, user_id, account_id, provider_id, access_token, refresh_token, access_token_expires_at, refresh_token_expires_at, scope, id_token, password_hash, created_at, updated_at, failed_login_attempts, locked_until
FROM user_accounts
WHERE user_id = $1
    AND provider_id = 'credential'
`

func (q *Queries) GetCredentialUserAccountByUserID(ctx context.Context, userID uuid.UUID) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getCredentialUserAccountByUserID, userID)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.ProviderID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.IDToken,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const getUserAccountByProvider = `-- name: GetUserAccountByProvider :one
SELECT id, user_id, account_id, provider_id, access_token, refresh_token, access_token_expires_at, refresh_token_expires_at, scope, id_token, password_hash, created_at, updated_at, failed_login_attempts, locked_until
FROM user_accounts
WHERE provider_id = $1
    AND account_id = $2
`

type GetUserAccountByProviderParams struct {
	ProviderID AuthProviderID
	AccountID  string
}

// Login lookup: OAuth callback (provider_id, account_id from the
// provider) or credential login (provider_id = 'credential', account_id
// = whatever convention the app uses, e.g. the user's id or email).
func (q *Queries) GetUserAccountByProvider(ctx context.Context, arg GetUserAccountByProviderParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByProvider, arg.ProviderID, arg.AccountID)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.ProviderID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.IDToken,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const incrementFailedLoginAttempts = `-- name: IncrementFailedLoginAttempts :one
UPDATE user_accounts
SET failed_login_attempts = failed_login_attempts + 1,
    updated_at = NOW()
WHERE user_id = $1
    AND provider_id = 'credential'
RETURNING id, user_id, account_id, provider_id, access_token, refresh_token, access_token_expires_at, refresh_token_expires_at, scope, id_token, password_hash, created_at, updated_at, failed_login_attempts, locked_until
`

// Called after a wrong password. The usecase decides whether the
// returned failed_login_attempts count crosses the configured
// lockout threshold and, if so, calls LockCredentialUserAccount.
func (q *Queries) IncrementFailedLoginAttempts(ctx context.Context, userID uuid.UUID) (UserAccount, error) {
	row := q.db.QueryRow(ctx, incrementFailedLoginAttempts, userID)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.ProviderID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.IDToken,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const listUserAccountsByUserID = `-- name: ListUserAccountsByUserID :many
SELECT id, user_id, account_id, provider_id, access_token, refresh_token, access_token_expires_at, refresh_token_expires_at, scope, id_token, password_hash, created_at, updated_at, failed_login_attempts, locked_until
FROM user_accounts
WHERE user_id = $1
ORDER BY created_at
`

// "Linked accounts" list in account settings.
func (q *Queries) ListUserAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]UserAccount, error) {
	rows, err := q.db.Query(ctx, listUserAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserAccount{}
	for rows.Next() {
		var i UserAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.ProviderID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.AccessTokenExpiresAt,
			&i.RefreshTokenExpiresAt,
			&i.Scope,
			&i.IDToken,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCredentialUserAccount = `-- name: LockCredentialUserAccount :exec
UPDATE user_accounts
SET locked_until = $1,
    updated_at = NOW()
WHERE user_id = $2
    AND provider_id = 'credential'
`

type LockCredentialUserAccountParams struct {
	LockedUntil pgtype.Timestamptz
	UserID      uuid.UUID
}

func (q *Queries) LockCredentialUserAccount(ctx context.Context, arg LockCredentialUserAccountParams) error {
	_, err := q.db.Exec(ctx, lockCredentialUserAccount, arg.LockedUntil, arg.UserID)
	return err
}

const resetFailedLoginAttempts = `-- name: ResetFailedLoginAttempts :exec
UPDATE user_accounts
SET failed_login_attempts = 0,
    locked_until = NULL,
    updated_at = NOW()
WHERE user_id = $1
    AND provider_id = 'credential'
`

// Called after a successful login to clear any accumulated failures.
func (q *Queries) ResetFailedLoginAttempts(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedLoginAttempts, userID)
	return err
}

const updateOAuthUserAccountTokens = `-- name: UpdateOAuthUserAccountTokens :exec
UPDATE user_accounts
SET access_token = $1,
    refresh_token = $2,
    access_token_expires_at = $3,
    refresh_token_expires_at = $4,
    updated_at = NOW()
WHERE id = $5
`

type UpdateOAuthUserAccountTokensParams struct {
	AccessToken           pgtype.Text
	RefreshToken          pgtype.Text
	AccessTokenExpiresAt  pgtype.Timestamptz
	RefreshTokenExpiresAt pgtype.Timestamptz
	ID                    uuid.UUID
}

// Called after a token refresh with the provider.
func (q *Queries) UpdateOAuthUserAccountTokens(ctx context.Context, arg UpdateOAuthUserAccountTokensParams) error {
	_, err := q.db.Exec(ctx, updateOAuthUserAccountTokens,
		arg.AccessToken,
		arg.RefreshToken,
		arg.AccessTokenExpiresAt,
		arg.RefreshTokenExpiresAt,
		arg.ID,
	)
	return err
}

const updateUserAccountPasswordHash = `-- name: UpdateUserAccountPasswordHash :exec
UPDATE user_accounts
SET password_hash = $1,
    updated_at = NOW()
WHERE user_id = $2
    AND provider_id = 'credential'
`

type UpdateUserAccountPasswordHashParams struct {
	PasswordHash pgtype.Text
	UserID       uuid.UUID
}

// Password change / reset flow.
func (q *Queries) UpdateUserAccountPasswordHash(ctx context.Context, arg UpdateUserAccountPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserAccountPasswordHash, arg.PasswordHash, arg.UserID)
	return err
}
