// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/ngodingvareng/memoria/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockActivityImageRepository creates a new instance of MockActivityImageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActivityImageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActivityImageRepository {
	mock := &MockActivityImageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActivityImageRepository is an autogenerated mock type for the ActivityImageRepository type
type MockActivityImageRepository struct {
	mock.Mock
}

type MockActivityImageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActivityImageRepository) EXPECT() *MockActivityImageRepository_Expecter {
	return &MockActivityImageRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockActivityImageRepository
func (_mock *MockActivityImageRepository) Create(ctx context.Context, image *entity.ActivityImage) (*entity.ActivityImage, error) {
	ret := _mock.Called(ctx, image)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.ActivityImage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.ActivityImage) (*entity.ActivityImage, error)); ok {
		return returnFunc(ctx, image)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.ActivityImage) *entity.ActivityImage); ok {
		r0 = returnFunc(ctx, image)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ActivityImage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.ActivityImage) error); ok {
		r1 = returnFunc(ctx, image)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityImageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockActivityImageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - image *entity.ActivityImage
func (_e *MockActivityImageRepository_Expecter) Create(ctx any, image any) *MockActivityImageRepository_Create_Call {
	return &MockActivityImageRepository_Create_Call{Call: _e.mock.On("Create", ctx, image)}
}

func (_c *MockActivityImageRepository_Create_Call) Run(run func(ctx context.Context, image *entity.ActivityImage)) *MockActivityImageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.ActivityImage
		if args[1] != nil {
			arg1 = args[1].(*entity.ActivityImage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivityImageRepository_Create_Call) Return(activityImage *entity.ActivityImage, err error) *MockActivityImageRepository_Create_Call {
	_c.Call.Return(activityImage, err)
	return _c
}

func (_c *MockActivityImageRepository_Create_Call) RunAndReturn(run func(ctx context.Context, image *entity.ActivityImage) (*entity.ActivityImage, error)) *MockActivityImageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockActivityImageRepository
func (_mock *MockActivityImageRepository) Delete(ctx context.Context, activityID uuid.UUID, imageID uuid.UUID) error {
	ret := _mock.Called(ctx, activityID, imageID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, activityID, imageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActivityImageRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockActivityImageRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - activityID uuid.UUID
//   - imageID uuid.UUID
func (_e *MockActivityImageRepository_Expecter) Delete(ctx any, activityID any, imageID any) *MockActivityImageRepository_Delete_Call {
	return &MockActivityImageRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, activityID, imageID)}
}

func (_c *MockActivityImageRepository_Delete_Call) Run(run func(ctx context.Context, activityID uuid.UUID, imageID uuid.UUID)) *MockActivityImageRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockActivityImageRepository_Delete_Call) Return(err error) *MockActivityImageRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActivityImageRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, activityID uuid.UUID, imageID uuid.UUID) error) *MockActivityImageRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ListByActivityID provides a mock function for the type MockActivityImageRepository
func (_mock *MockActivityImageRepository) ListByActivityID(ctx context.Context, activityID uuid.UUID) ([]*entity.ActivityImage, error) {
	ret := _mock.Called(ctx, activityID)

	if len(ret) == 0 {
		panic("no return value specified for ListByActivityID")
	}

	var r0 []*entity.ActivityImage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.ActivityImage, error)); ok {
		return returnFunc(ctx, activityID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.ActivityImage); ok {
		r0 = returnFunc(ctx, activityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ActivityImage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, activityID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityImageRepository_ListByActivityID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByActivityID'
type MockActivityImageRepository_ListByActivityID_Call struct {
	*mock.Call
}

// ListByActivityID is a helper method to define mock.On call
//   - ctx context.Context
//   - activityID uuid.UUID
func (_e *MockActivityImageRepository_Expecter) ListByActivityID(ctx any, activityID any) *MockActivityImageRepository_ListByActivityID_Call {
	return &MockActivityImageRepository_ListByActivityID_Call{Call: _e.mock.On("ListByActivityID", ctx, activityID)}
}

func (_c *MockActivityImageRepository_ListByActivityID_Call) Run(run func(ctx context.Context, activityID uuid.UUID)) *MockActivityImageRepository_ListByActivityID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivityImageRepository_ListByActivityID_Call) Return(activityImages []*entity.ActivityImage, err error) *MockActivityImageRepository_ListByActivityID_Call {
	_c.Call.Return(activityImages, err)
	return _c
}

func (_c *MockActivityImageRepository_ListByActivityID_Call) RunAndReturn(run func(ctx context.Context, activityID uuid.UUID) ([]*entity.ActivityImage, error)) *MockActivityImageRepository_ListByActivityID_Call {
	_c.Call.Return(run)
	return _c
}
