// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/ngodingvareng/memoria/internal/entity"
	"github.com/ngodingvareng/memoria/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewMockActivityRepository creates a new instance of MockActivityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActivityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActivityRepository {
	mock := &MockActivityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActivityRepository is an autogenerated mock type for the ActivityRepository type
type MockActivityRepository struct {
	mock.Mock
}

type MockActivityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActivityRepository) EXPECT() *MockActivityRepository_Expecter {
	return &MockActivityRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockActivityRepository
func (_mock *MockActivityRepository) Create(ctx context.Context, activity *entity.Activity) (*entity.Activity, error) {
	ret := _mock.Called(ctx, activity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Activity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Activity) (*entity.Activity, error)); ok {
		return returnFunc(ctx, activity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Activity) *entity.Activity); ok {
		r0 = returnFunc(ctx, activity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Activity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Activity) error); ok {
		r1 = returnFunc(ctx, activity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockActivityRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - activity *entity.Activity
func (_e *MockActivityRepository_Expecter) Create(ctx any, activity any) *MockActivityRepository_Create_Call {
	return &MockActivityRepository_Create_Call{Call: _e.mock.On("Create", ctx, activity)}
}

func (_c *MockActivityRepository_Create_Call) Run(run func(ctx context.Context, activity *entity.Activity)) *MockActivityRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Activity
		if args[1] != nil {
			arg1 = args[1].(*entity.Activity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivityRepository_Create_Call) Return(activity1 *entity.Activity, err error) *MockActivityRepository_Create_Call {
	_c.Call.Return(activity1, err)
	return _c
}

func (_c *MockActivityRepository_Create_Call) RunAndReturn(run func(ctx context.Context, activity *entity.Activity) (*entity.Activity, error)) *MockActivityRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockActivityRepository
func (_mock *MockActivityRepository) GetByID(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entity.Activity, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Activity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.Activity, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.Activity); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Activity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockActivityRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockActivityRepository_Expecter) GetByID(ctx any, id any, userID any) *MockActivityRepository_GetByID_Call {
	return &MockActivityRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id, userID)}
}

func (_c *MockActivityRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockActivityRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockActivityRepository_GetByID_Call) Return(activity *entity.Activity, err error) *MockActivityRepository_GetByID_Call {
	_c.Call.Return(activity, err)
	return _c
}

func (_c *MockActivityRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entity.Activity, error)) *MockActivityRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockActivityRepository
func (_mock *MockActivityRepository) Search(ctx context.Context, params usecase.SearchActivitiesParams) ([]*entity.Activity, int64, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*entity.Activity
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.SearchActivitiesParams) ([]*entity.Activity, int64, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.SearchActivitiesParams) []*entity.Activity); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Activity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecase.SearchActivitiesParams) int64); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, usecase.SearchActivitiesParams) error); ok {
		r2 = returnFunc(ctx, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockActivityRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockActivityRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - params usecase.SearchActivitiesParams
func (_e *MockActivityRepository_Expecter) Search(ctx any, params any) *MockActivityRepository_Search_Call {
	return &MockActivityRepository_Search_Call{Call: _e.mock.On("Search", ctx, params)}
}

func (_c *MockActivityRepository_Search_Call) Run(run func(ctx context.Context, params usecase.SearchActivitiesParams)) *MockActivityRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.SearchActivitiesParams
		if args[1] != nil {
			arg1 = args[1].(usecase.SearchActivitiesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivityRepository_Search_Call) Return(activitys []*entity.Activity, n int64, err error) *MockActivityRepository_Search_Call {
	_c.Call.Return(activitys, n, err)
	return _c
}

func (_c *MockActivityRepository_Search_Call) RunAndReturn(run func(ctx context.Context, params usecase.SearchActivitiesParams) ([]*entity.Activity, int64, error)) *MockActivityRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function for the type MockActivityRepository
func (_mock *MockActivityRepository) SoftDelete(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActivityRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockActivityRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockActivityRepository_Expecter) SoftDelete(ctx any, id any, userID any) *MockActivityRepository_SoftDelete_Call {
	return &MockActivityRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id, userID)}
}

func (_c *MockActivityRepository_SoftDelete_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockActivityRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockActivityRepository_SoftDelete_Call) Return(err error) *MockActivityRepository_SoftDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActivityRepository_SoftDelete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockActivityRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockActivityRepository
func (_mock *MockActivityRepository) Update(ctx context.Context, activity *entity.Activity) (*entity.Activity, error) {
	ret := _mock.Called(ctx, activity)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.Activity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Activity) (*entity.Activity, error)); ok {
		return returnFunc(ctx, activity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Activity) *entity.Activity); ok {
		r0 = returnFunc(ctx, activity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Activity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Activity) error); ok {
		r1 = returnFunc(ctx, activity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockActivityRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - activity *entity.Activity
func (_e *MockActivityRepository_Expecter) Update(ctx any, activity any) *MockActivityRepository_Update_Call {
	return &MockActivityRepository_Update_Call{Call: _e.mock.On("Update", ctx, activity)}
}

func (_c *MockActivityRepository_Update_Call) Run(run func(ctx context.Context, activity *entity.Activity)) *MockActivityRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Activity
		if args[1] != nil {
			arg1 = args[1].(*entity.Activity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivityRepository_Update_Call) Return(activity1 *entity.Activity, err error) *MockActivityRepository_Update_Call {
	_c.Call.Return(activity1, err)
	return _c
}

func (_c *MockActivityRepository_Update_Call) RunAndReturn(run func(ctx context.Context, activity *entity.Activity) (*entity.Activity, error)) *MockActivityRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithTransaction provides a mock function for the type MockActivityRepository
func (_mock *MockActivityRepository) WithTransaction(ctx context.Context, fn func(usecase.ActivityRepository) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(usecase.ActivityRepository) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActivityRepository_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type MockActivityRepository_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(usecase.ActivityRepository) error
func (_e *MockActivityRepository_Expecter) WithTransaction(ctx any, fn any) *MockActivityRepository_WithTransaction_Call {
	return &MockActivityRepository_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, fn)}
}

func (_c *MockActivityRepository_WithTransaction_Call) Run(run func(ctx context.Context, fn func(usecase.ActivityRepository) error)) *MockActivityRepository_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(usecase.ActivityRepository) error
		if args[1] != nil {
			arg1 = args[1].(func(usecase.ActivityRepository) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivityRepository_WithTransaction_Call) Return(err error) *MockActivityRepository_WithTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActivityRepository_WithTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(usecase.ActivityRepository) error) error) *MockActivityRepository_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}
