// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/ngodingvareng/memoria/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockActivityAccessChecker creates a new instance of MockActivityAccessChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActivityAccessChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActivityAccessChecker {
	mock := &MockActivityAccessChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActivityAccessChecker is an autogenerated mock type for the ActivityAccessChecker type
type MockActivityAccessChecker struct {
	mock.Mock
}

type MockActivityAccessChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActivityAccessChecker) EXPECT() *MockActivityAccessChecker_Expecter {
	return &MockActivityAccessChecker_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockActivityAccessChecker
func (_mock *MockActivityAccessChecker) GetByID(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entity.Activity, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Activity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.Activity, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.Activity); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Activity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityAccessChecker_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockActivityAccessChecker_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockActivityAccessChecker_Expecter) GetByID(ctx any, id any, userID any) *MockActivityAccessChecker_GetByID_Call {
	return &MockActivityAccessChecker_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id, userID)}
}

func (_c *MockActivityAccessChecker_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockActivityAccessChecker_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockActivityAccessChecker_GetByID_Call) Return(activity *entity.Activity, err error) *MockActivityAccessChecker_GetByID_Call {
	_c.Call.Return(activity, err)
	return _c
}

func (_c *MockActivityAccessChecker_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entity.Activity, error)) *MockActivityAccessChecker_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
