// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/ngodingvareng/memoria/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAlbumRepository creates a new instance of MockAlbumRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlbumRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlbumRepository {
	mock := &MockAlbumRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAlbumRepository is an autogenerated mock type for the AlbumRepository type
type MockAlbumRepository struct {
	mock.Mock
}

type MockAlbumRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlbumRepository) EXPECT() *MockAlbumRepository_Expecter {
	return &MockAlbumRepository_Expecter{mock: &_m.Mock}
}

// ListCircleImages provides a mock function for the type MockAlbumRepository
func (_mock *MockAlbumRepository) ListCircleImages(ctx context.Context, circleID uuid.UUID, limit int32, offset int32) ([]*entity.AlbumImage, error) {
	ret := _mock.Called(ctx, circleID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListCircleImages")
	}

	var r0 []*entity.AlbumImage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, int32) ([]*entity.AlbumImage, error)); ok {
		return returnFunc(ctx, circleID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, int32) []*entity.AlbumImage); ok {
		r0 = returnFunc(ctx, circleID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AlbumImage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int32, int32) error); ok {
		r1 = returnFunc(ctx, circleID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAlbumRepository_ListCircleImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCircleImages'
type MockAlbumRepository_ListCircleImages_Call struct {
	*mock.Call
}

// ListCircleImages is a helper method to define mock.On call
//   - ctx context.Context
//   - circleID uuid.UUID
//   - limit int32
//   - offset int32
func (_e *MockAlbumRepository_Expecter) ListCircleImages(ctx any, circleID any, limit any, offset any) *MockAlbumRepository_ListCircleImages_Call {
	return &MockAlbumRepository_ListCircleImages_Call{Call: _e.mock.On("ListCircleImages", ctx, circleID, limit, offset)}
}

func (_c *MockAlbumRepository_ListCircleImages_Call) Run(run func(ctx context.Context, circleID uuid.UUID, limit int32, offset int32)) *MockAlbumRepository_ListCircleImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAlbumRepository_ListCircleImages_Call) Return(albumImages []*entity.AlbumImage, err error) *MockAlbumRepository_ListCircleImages_Call {
	_c.Call.Return(albumImages, err)
	return _c
}

func (_c *MockAlbumRepository_ListCircleImages_Call) RunAndReturn(run func(ctx context.Context, circleID uuid.UUID, limit int32, offset int32) ([]*entity.AlbumImage, error)) *MockAlbumRepository_ListCircleImages_Call {
	_c.Call.Return(run)
	return _c
}

// ListPersonalImages provides a mock function for the type MockAlbumRepository
func (_mock *MockAlbumRepository) ListPersonalImages(ctx context.Context, userID uuid.UUID, limit int32, offset int32) ([]*entity.AlbumImage, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListPersonalImages")
	}

	var r0 []*entity.AlbumImage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, int32) ([]*entity.AlbumImage, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, int32) []*entity.AlbumImage); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AlbumImage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int32, int32) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAlbumRepository_ListPersonalImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPersonalImages'
type MockAlbumRepository_ListPersonalImages_Call struct {
	*mock.Call
}

// ListPersonalImages is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int32
//   - offset int32
func (_e *MockAlbumRepository_Expecter) ListPersonalImages(ctx any, userID any, limit any, offset any) *MockAlbumRepository_ListPersonalImages_Call {
	return &MockAlbumRepository_ListPersonalImages_Call{Call: _e.mock.On("ListPersonalImages", ctx, userID, limit, offset)}
}

func (_c *MockAlbumRepository_ListPersonalImages_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int32, offset int32)) *MockAlbumRepository_ListPersonalImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAlbumRepository_ListPersonalImages_Call) Return(albumImages []*entity.AlbumImage, err error) *MockAlbumRepository_ListPersonalImages_Call {
	_c.Call.Return(albumImages, err)
	return _c
}

func (_c *MockAlbumRepository_ListPersonalImages_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, limit int32, offset int32) ([]*entity.AlbumImage, error)) *MockAlbumRepository_ListPersonalImages_Call {
	_c.Call.Return(run)
	return _c
}
