// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCircleShareChecker creates a new instance of MockCircleShareChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCircleShareChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCircleShareChecker {
	mock := &MockCircleShareChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCircleShareChecker is an autogenerated mock type for the CircleShareChecker type
type MockCircleShareChecker struct {
	mock.Mock
}

type MockCircleShareChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCircleShareChecker) EXPECT() *MockCircleShareChecker_Expecter {
	return &MockCircleShareChecker_Expecter{mock: &_m.Mock}
}

// ListSharedCircleIDs provides a mock function for the type MockCircleShareChecker
func (_mock *MockCircleShareChecker) ListSharedCircleIDs(ctx context.Context, userA uuid.UUID, userB uuid.UUID) ([]uuid.UUID, error) {
	ret := _mock.Called(ctx, userA, userB)

	if len(ret) == 0 {
		panic("no return value specified for ListSharedCircleIDs")
	}

	var r0 []uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]uuid.UUID, error)); ok {
		return returnFunc(ctx, userA, userB)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []uuid.UUID); ok {
		r0 = returnFunc(ctx, userA, userB)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userA, userB)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCircleShareChecker_ListSharedCircleIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSharedCircleIDs'
type MockCircleShareChecker_ListSharedCircleIDs_Call struct {
	*mock.Call
}

// ListSharedCircleIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userA uuid.UUID
//   - userB uuid.UUID
func (_e *MockCircleShareChecker_Expecter) ListSharedCircleIDs(ctx any, userA any, userB any) *MockCircleShareChecker_ListSharedCircleIDs_Call {
	return &MockCircleShareChecker_ListSharedCircleIDs_Call{Call: _e.mock.On("ListSharedCircleIDs", ctx, userA, userB)}
}

func (_c *MockCircleShareChecker_ListSharedCircleIDs_Call) Run(run func(ctx context.Context, userA uuid.UUID, userB uuid.UUID)) *MockCircleShareChecker_ListSharedCircleIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCircleShareChecker_ListSharedCircleIDs_Call) Return(uUIDs []uuid.UUID, err error) *MockCircleShareChecker_ListSharedCircleIDs_Call {
	_c.Call.Return(uUIDs, err)
	return _c
}

func (_c *MockCircleShareChecker_ListSharedCircleIDs_Call) RunAndReturn(run func(ctx context.Context, userA uuid.UUID, userB uuid.UUID) ([]uuid.UUID, error)) *MockCircleShareChecker_ListSharedCircleIDs_Call {
	_c.Call.Return(run)
	return _c
}
