// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/ngodingvareng/memoria/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCircleAccessChecker creates a new instance of MockCircleAccessChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCircleAccessChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCircleAccessChecker {
	mock := &MockCircleAccessChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCircleAccessChecker is an autogenerated mock type for the CircleAccessChecker type
type MockCircleAccessChecker struct {
	mock.Mock
}

type MockCircleAccessChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCircleAccessChecker) EXPECT() *MockCircleAccessChecker_Expecter {
	return &MockCircleAccessChecker_Expecter{mock: &_m.Mock}
}

// GetActiveMember provides a mock function for the type MockCircleAccessChecker
func (_mock *MockCircleAccessChecker) GetActiveMember(ctx context.Context, circleID uuid.UUID, userID uuid.UUID) (*entity.CircleMember, error) {
	ret := _mock.Called(ctx, circleID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveMember")
	}

	var r0 *entity.CircleMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.CircleMember, error)); ok {
		return returnFunc(ctx, circleID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.CircleMember); ok {
		r0 = returnFunc(ctx, circleID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CircleMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, circleID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCircleAccessChecker_GetActiveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveMember'
type MockCircleAccessChecker_GetActiveMember_Call struct {
	*mock.Call
}

// GetActiveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - circleID uuid.UUID
//   - userID uuid.UUID
func (_e *MockCircleAccessChecker_Expecter) GetActiveMember(ctx any, circleID any, userID any) *MockCircleAccessChecker_GetActiveMember_Call {
	return &MockCircleAccessChecker_GetActiveMember_Call{Call: _e.mock.On("GetActiveMember", ctx, circleID, userID)}
}

func (_c *MockCircleAccessChecker_GetActiveMember_Call) Run(run func(ctx context.Context, circleID uuid.UUID, userID uuid.UUID)) *MockCircleAccessChecker_GetActiveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCircleAccessChecker_GetActiveMember_Call) Return(circleMember *entity.CircleMember, err error) *MockCircleAccessChecker_GetActiveMember_Call {
	_c.Call.Return(circleMember, err)
	return _c
}

func (_c *MockCircleAccessChecker_GetActiveMember_Call) RunAndReturn(run func(ctx context.Context, circleID uuid.UUID, userID uuid.UUID) (*entity.CircleMember, error)) *MockCircleAccessChecker_GetActiveMember_Call {
	_c.Call.Return(run)
	return _c
}
