// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/ngodingvareng/memoria/internal/entity"
	"github.com/ngodingvareng/memoria/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMomentRepository creates a new instance of MockMomentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMomentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMomentRepository {
	mock := &MockMomentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMomentRepository is an autogenerated mock type for the MomentRepository type
type MockMomentRepository struct {
	mock.Mock
}

type MockMomentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMomentRepository) EXPECT() *MockMomentRepository_Expecter {
	return &MockMomentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) Create(ctx context.Context, moment *entity.Moment) (*entity.Moment, error) {
	ret := _mock.Called(ctx, moment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Moment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Moment) (*entity.Moment, error)); ok {
		return returnFunc(ctx, moment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Moment) *entity.Moment); ok {
		r0 = returnFunc(ctx, moment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Moment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Moment) error); ok {
		r1 = returnFunc(ctx, moment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMomentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMomentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - moment *entity.Moment
func (_e *MockMomentRepository_Expecter) Create(ctx any, moment any) *MockMomentRepository_Create_Call {
	return &MockMomentRepository_Create_Call{Call: _e.mock.On("Create", ctx, moment)}
}

func (_c *MockMomentRepository_Create_Call) Run(run func(ctx context.Context, moment *entity.Moment)) *MockMomentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Moment
		if args[1] != nil {
			arg1 = args[1].(*entity.Moment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMomentRepository_Create_Call) Return(moment1 *entity.Moment, err error) *MockMomentRepository_Create_Call {
	_c.Call.Return(moment1, err)
	return _c
}

func (_c *MockMomentRepository_Create_Call) RunAndReturn(run func(ctx context.Context, moment *entity.Moment) (*entity.Moment, error)) *MockMomentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) GetByID(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entity.Moment, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Moment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.Moment, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.Moment); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Moment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMomentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockMomentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockMomentRepository_Expecter) GetByID(ctx any, id any, userID any) *MockMomentRepository_GetByID_Call {
	return &MockMomentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id, userID)}
}

func (_c *MockMomentRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockMomentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMomentRepository_GetByID_Call) Return(moment *entity.Moment, err error) *MockMomentRepository_GetByID_Call {
	_c.Call.Return(moment, err)
	return _c
}

func (_c *MockMomentRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entity.Moment, error)) *MockMomentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithAccess provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) GetWithAccess(ctx context.Context, id uuid.UUID, viewerID uuid.UUID) (*entity.Moment, error) {
	ret := _mock.Called(ctx, id, viewerID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithAccess")
	}

	var r0 *entity.Moment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.Moment, error)); ok {
		return returnFunc(ctx, id, viewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.Moment); ok {
		r0 = returnFunc(ctx, id, viewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Moment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, viewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMomentRepository_GetWithAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithAccess'
type MockMomentRepository_GetWithAccess_Call struct {
	*mock.Call
}

// GetWithAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - viewerID uuid.UUID
func (_e *MockMomentRepository_Expecter) GetWithAccess(ctx any, id any, viewerID any) *MockMomentRepository_GetWithAccess_Call {
	return &MockMomentRepository_GetWithAccess_Call{Call: _e.mock.On("GetWithAccess", ctx, id, viewerID)}
}

func (_c *MockMomentRepository_GetWithAccess_Call) Run(run func(ctx context.Context, id uuid.UUID, viewerID uuid.UUID)) *MockMomentRepository_GetWithAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMomentRepository_GetWithAccess_Call) Return(moment *entity.Moment, err error) *MockMomentRepository_GetWithAccess_Call {
	_c.Call.Return(moment, err)
	return _c
}

func (_c *MockMomentRepository_GetWithAccess_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, viewerID uuid.UUID) (*entity.Moment, error)) *MockMomentRepository_GetWithAccess_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCircle provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) ListByCircle(ctx context.Context, circleID uuid.UUID, limit int32, offset int32) ([]*entity.Moment, error) {
	ret := _mock.Called(ctx, circleID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByCircle")
	}

	var r0 []*entity.Moment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, int32) ([]*entity.Moment, error)); ok {
		return returnFunc(ctx, circleID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, int32) []*entity.Moment); ok {
		r0 = returnFunc(ctx, circleID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Moment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int32, int32) error); ok {
		r1 = returnFunc(ctx, circleID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMomentRepository_ListByCircle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCircle'
type MockMomentRepository_ListByCircle_Call struct {
	*mock.Call
}

// ListByCircle is a helper method to define mock.On call
//   - ctx context.Context
//   - circleID uuid.UUID
//   - limit int32
//   - offset int32
func (_e *MockMomentRepository_Expecter) ListByCircle(ctx any, circleID any, limit any, offset any) *MockMomentRepository_ListByCircle_Call {
	return &MockMomentRepository_ListByCircle_Call{Call: _e.mock.On("ListByCircle", ctx, circleID, limit, offset)}
}

func (_c *MockMomentRepository_ListByCircle_Call) Run(run func(ctx context.Context, circleID uuid.UUID, limit int32, offset int32)) *MockMomentRepository_ListByCircle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMomentRepository_ListByCircle_Call) Return(moments []*entity.Moment, err error) *MockMomentRepository_ListByCircle_Call {
	_c.Call.Return(moments, err)
	return _c
}

func (_c *MockMomentRepository_ListByCircle_Call) RunAndReturn(run func(ctx context.Context, circleID uuid.UUID, limit int32, offset int32) ([]*entity.Moment, error)) *MockMomentRepository_ListByCircle_Call {
	_c.Call.Return(run)
	return _c
}

// ListByThreadID provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) ListByThreadID(ctx context.Context, threadID uuid.UUID, limit int32, offset int32) ([]*entity.Moment, error) {
	ret := _mock.Called(ctx, threadID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByThreadID")
	}

	var r0 []*entity.Moment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, int32) ([]*entity.Moment, error)); ok {
		return returnFunc(ctx, threadID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, int32) []*entity.Moment); ok {
		r0 = returnFunc(ctx, threadID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Moment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int32, int32) error); ok {
		r1 = returnFunc(ctx, threadID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMomentRepository_ListByThreadID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByThreadID'
type MockMomentRepository_ListByThreadID_Call struct {
	*mock.Call
}

// ListByThreadID is a helper method to define mock.On call
//   - ctx context.Context
//   - threadID uuid.UUID
//   - limit int32
//   - offset int32
func (_e *MockMomentRepository_Expecter) ListByThreadID(ctx any, threadID any, limit any, offset any) *MockMomentRepository_ListByThreadID_Call {
	return &MockMomentRepository_ListByThreadID_Call{Call: _e.mock.On("ListByThreadID", ctx, threadID, limit, offset)}
}

func (_c *MockMomentRepository_ListByThreadID_Call) Run(run func(ctx context.Context, threadID uuid.UUID, limit int32, offset int32)) *MockMomentRepository_ListByThreadID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMomentRepository_ListByThreadID_Call) Return(moments []*entity.Moment, err error) *MockMomentRepository_ListByThreadID_Call {
	_c.Call.Return(moments, err)
	return _c
}

func (_c *MockMomentRepository_ListByThreadID_Call) RunAndReturn(run func(ctx context.Context, threadID uuid.UUID, limit int32, offset int32) ([]*entity.Moment, error)) *MockMomentRepository_ListByThreadID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) ListByUserID(ctx context.Context, userID uuid.UUID, limit int32, offset int32) ([]*entity.Moment, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*entity.Moment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, int32) ([]*entity.Moment, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, int32) []*entity.Moment); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Moment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int32, int32) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMomentRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockMomentRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int32
//   - offset int32
func (_e *MockMomentRepository_Expecter) ListByUserID(ctx any, userID any, limit any, offset any) *MockMomentRepository_ListByUserID_Call {
	return &MockMomentRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID, limit, offset)}
}

func (_c *MockMomentRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int32, offset int32)) *MockMomentRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMomentRepository_ListByUserID_Call) Return(moments []*entity.Moment, err error) *MockMomentRepository_ListByUserID_Call {
	_c.Call.Return(moments, err)
	return _c
}

func (_c *MockMomentRepository_ListByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, limit int32, offset int32) ([]*entity.Moment, error)) *MockMomentRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ListHomeFeed provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) ListHomeFeed(ctx context.Context, userID uuid.UUID, limit int32, offset int32) ([]*entity.Moment, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListHomeFeed")
	}

	var r0 []*entity.Moment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, int32) ([]*entity.Moment, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, int32) []*entity.Moment); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Moment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int32, int32) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMomentRepository_ListHomeFeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHomeFeed'
type MockMomentRepository_ListHomeFeed_Call struct {
	*mock.Call
}

// ListHomeFeed is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int32
//   - offset int32
func (_e *MockMomentRepository_Expecter) ListHomeFeed(ctx any, userID any, limit any, offset any) *MockMomentRepository_ListHomeFeed_Call {
	return &MockMomentRepository_ListHomeFeed_Call{Call: _e.mock.On("ListHomeFeed", ctx, userID, limit, offset)}
}

func (_c *MockMomentRepository_ListHomeFeed_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int32, offset int32)) *MockMomentRepository_ListHomeFeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMomentRepository_ListHomeFeed_Call) Return(moments []*entity.Moment, err error) *MockMomentRepository_ListHomeFeed_Call {
	_c.Call.Return(moments, err)
	return _c
}

func (_c *MockMomentRepository_ListHomeFeed_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, limit int32, offset int32) ([]*entity.Moment, error)) *MockMomentRepository_ListHomeFeed_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) Search(ctx context.Context, userID uuid.UUID, query string, limit int32, offset int32) ([]*entity.Moment, error) {
	ret := _mock.Called(ctx, userID, query, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*entity.Moment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int32, int32) ([]*entity.Moment, error)); ok {
		return returnFunc(ctx, userID, query, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int32, int32) []*entity.Moment); ok {
		r0 = returnFunc(ctx, userID, query, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Moment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int32, int32) error); ok {
		r1 = returnFunc(ctx, userID, query, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMomentRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockMomentRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - query string
//   - limit int32
//   - offset int32
func (_e *MockMomentRepository_Expecter) Search(ctx any, userID any, query any, limit any, offset any) *MockMomentRepository_Search_Call {
	return &MockMomentRepository_Search_Call{Call: _e.mock.On("Search", ctx, userID, query, limit, offset)}
}

func (_c *MockMomentRepository_Search_Call) Run(run func(ctx context.Context, userID uuid.UUID, query string, limit int32, offset int32)) *MockMomentRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		var arg4 int32
		if args[4] != nil {
			arg4 = args[4].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockMomentRepository_Search_Call) Return(moments []*entity.Moment, err error) *MockMomentRepository_Search_Call {
	_c.Call.Return(moments, err)
	return _c
}

func (_c *MockMomentRepository_Search_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, query string, limit int32, offset int32) ([]*entity.Moment, error)) *MockMomentRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SearchSuggestions provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) SearchSuggestions(ctx context.Context, userID uuid.UUID, query string, prefixQuery string, limit int32) ([]*entity.Moment, error) {
	ret := _mock.Called(ctx, userID, query, prefixQuery, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchSuggestions")
	}

	var r0 []*entity.Moment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, int32) ([]*entity.Moment, error)); ok {
		return returnFunc(ctx, userID, query, prefixQuery, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, int32) []*entity.Moment); ok {
		r0 = returnFunc(ctx, userID, query, prefixQuery, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Moment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, int32) error); ok {
		r1 = returnFunc(ctx, userID, query, prefixQuery, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMomentRepository_SearchSuggestions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchSuggestions'
type MockMomentRepository_SearchSuggestions_Call struct {
	*mock.Call
}

// SearchSuggestions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - query string
//   - prefixQuery string
//   - limit int32
func (_e *MockMomentRepository_Expecter) SearchSuggestions(ctx any, userID any, query any, prefixQuery any, limit any) *MockMomentRepository_SearchSuggestions_Call {
	return &MockMomentRepository_SearchSuggestions_Call{Call: _e.mock.On("SearchSuggestions", ctx, userID, query, prefixQuery, limit)}
}

func (_c *MockMomentRepository_SearchSuggestions_Call) Run(run func(ctx context.Context, userID uuid.UUID, query string, prefixQuery string, limit int32)) *MockMomentRepository_SearchSuggestions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int32
		if args[4] != nil {
			arg4 = args[4].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockMomentRepository_SearchSuggestions_Call) Return(moments []*entity.Moment, err error) *MockMomentRepository_SearchSuggestions_Call {
	_c.Call.Return(moments, err)
	return _c
}

func (_c *MockMomentRepository_SearchSuggestions_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, query string, prefixQuery string, limit int32) ([]*entity.Moment, error)) *MockMomentRepository_SearchSuggestions_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) SoftDelete(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMomentRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockMomentRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockMomentRepository_Expecter) SoftDelete(ctx any, id any, userID any) *MockMomentRepository_SoftDelete_Call {
	return &MockMomentRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id, userID)}
}

func (_c *MockMomentRepository_SoftDelete_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockMomentRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMomentRepository_SoftDelete_Call) Return(err error) *MockMomentRepository_SoftDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMomentRepository_SoftDelete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockMomentRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) Update(ctx context.Context, moment *entity.Moment) (*entity.Moment, error) {
	ret := _mock.Called(ctx, moment)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.Moment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Moment) (*entity.Moment, error)); ok {
		return returnFunc(ctx, moment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Moment) *entity.Moment); ok {
		r0 = returnFunc(ctx, moment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Moment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Moment) error); ok {
		r1 = returnFunc(ctx, moment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMomentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMomentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - moment *entity.Moment
func (_e *MockMomentRepository_Expecter) Update(ctx any, moment any) *MockMomentRepository_Update_Call {
	return &MockMomentRepository_Update_Call{Call: _e.mock.On("Update", ctx, moment)}
}

func (_c *MockMomentRepository_Update_Call) Run(run func(ctx context.Context, moment *entity.Moment)) *MockMomentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Moment
		if args[1] != nil {
			arg1 = args[1].(*entity.Moment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMomentRepository_Update_Call) Return(moment1 *entity.Moment, err error) *MockMomentRepository_Update_Call {
	_c.Call.Return(moment1, err)
	return _c
}

func (_c *MockMomentRepository_Update_Call) RunAndReturn(run func(ctx context.Context, moment *entity.Moment) (*entity.Moment, error)) *MockMomentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithTransaction provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) WithTransaction(ctx context.Context, fn func(usecase.MomentRepository) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(usecase.MomentRepository) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMomentRepository_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type MockMomentRepository_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(usecase.MomentRepository) error
func (_e *MockMomentRepository_Expecter) WithTransaction(ctx any, fn any) *MockMomentRepository_WithTransaction_Call {
	return &MockMomentRepository_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, fn)}
}

func (_c *MockMomentRepository_WithTransaction_Call) Run(run func(ctx context.Context, fn func(usecase.MomentRepository) error)) *MockMomentRepository_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(usecase.MomentRepository) error
		if args[1] != nil {
			arg1 = args[1].(func(usecase.MomentRepository) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMomentRepository_WithTransaction_Call) Return(err error) *MockMomentRepository_WithTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMomentRepository_WithTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(usecase.MomentRepository) error) error) *MockMomentRepository_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}
