// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/ngodingvareng/memoria/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMomentImageRepository creates a new instance of MockMomentImageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMomentImageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMomentImageRepository {
	mock := &MockMomentImageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMomentImageRepository is an autogenerated mock type for the MomentImageRepository type
type MockMomentImageRepository struct {
	mock.Mock
}

type MockMomentImageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMomentImageRepository) EXPECT() *MockMomentImageRepository_Expecter {
	return &MockMomentImageRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockMomentImageRepository
func (_mock *MockMomentImageRepository) Create(ctx context.Context, image *entity.MomentImage) (*entity.MomentImage, error) {
	ret := _mock.Called(ctx, image)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.MomentImage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.MomentImage) (*entity.MomentImage, error)); ok {
		return returnFunc(ctx, image)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.MomentImage) *entity.MomentImage); ok {
		r0 = returnFunc(ctx, image)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.MomentImage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.MomentImage) error); ok {
		r1 = returnFunc(ctx, image)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMomentImageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMomentImageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - image *entity.MomentImage
func (_e *MockMomentImageRepository_Expecter) Create(ctx any, image any) *MockMomentImageRepository_Create_Call {
	return &MockMomentImageRepository_Create_Call{Call: _e.mock.On("Create", ctx, image)}
}

func (_c *MockMomentImageRepository_Create_Call) Run(run func(ctx context.Context, image *entity.MomentImage)) *MockMomentImageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.MomentImage
		if args[1] != nil {
			arg1 = args[1].(*entity.MomentImage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMomentImageRepository_Create_Call) Return(momentImage *entity.MomentImage, err error) *MockMomentImageRepository_Create_Call {
	_c.Call.Return(momentImage, err)
	return _c
}

func (_c *MockMomentImageRepository_Create_Call) RunAndReturn(run func(ctx context.Context, image *entity.MomentImage) (*entity.MomentImage, error)) *MockMomentImageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockMomentImageRepository
func (_mock *MockMomentImageRepository) Delete(ctx context.Context, momentID uuid.UUID, imageID uuid.UUID) (*entity.MomentImage, error) {
	ret := _mock.Called(ctx, momentID, imageID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *entity.MomentImage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.MomentImage, error)); ok {
		return returnFunc(ctx, momentID, imageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.MomentImage); ok {
		r0 = returnFunc(ctx, momentID, imageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.MomentImage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, momentID, imageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMomentImageRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMomentImageRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - momentID uuid.UUID
//   - imageID uuid.UUID
func (_e *MockMomentImageRepository_Expecter) Delete(ctx any, momentID any, imageID any) *MockMomentImageRepository_Delete_Call {
	return &MockMomentImageRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, momentID, imageID)}
}

func (_c *MockMomentImageRepository_Delete_Call) Run(run func(ctx context.Context, momentID uuid.UUID, imageID uuid.UUID)) *MockMomentImageRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMomentImageRepository_Delete_Call) Return(momentImage *entity.MomentImage, err error) *MockMomentImageRepository_Delete_Call {
	_c.Call.Return(momentImage, err)
	return _c
}

func (_c *MockMomentImageRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, momentID uuid.UUID, imageID uuid.UUID) (*entity.MomentImage, error)) *MockMomentImageRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ListByMomentID provides a mock function for the type MockMomentImageRepository
func (_mock *MockMomentImageRepository) ListByMomentID(ctx context.Context, momentID uuid.UUID) ([]*entity.MomentImage, error) {
	ret := _mock.Called(ctx, momentID)

	if len(ret) == 0 {
		panic("no return value specified for ListByMomentID")
	}

	var r0 []*entity.MomentImage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.MomentImage, error)); ok {
		return returnFunc(ctx, momentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.MomentImage); ok {
		r0 = returnFunc(ctx, momentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.MomentImage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, momentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMomentImageRepository_ListByMomentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByMomentID'
type MockMomentImageRepository_ListByMomentID_Call struct {
	*mock.Call
}

// ListByMomentID is a helper method to define mock.On call
//   - ctx context.Context
//   - momentID uuid.UUID
func (_e *MockMomentImageRepository_Expecter) ListByMomentID(ctx any, momentID any) *MockMomentImageRepository_ListByMomentID_Call {
	return &MockMomentImageRepository_ListByMomentID_Call{Call: _e.mock.On("ListByMomentID", ctx, momentID)}
}

func (_c *MockMomentImageRepository_ListByMomentID_Call) Run(run func(ctx context.Context, momentID uuid.UUID)) *MockMomentImageRepository_ListByMomentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMomentImageRepository_ListByMomentID_Call) Return(momentImages []*entity.MomentImage, err error) *MockMomentImageRepository_ListByMomentID_Call {
	_c.Call.Return(momentImages, err)
	return _c
}

func (_c *MockMomentImageRepository_ListByMomentID_Call) RunAndReturn(run func(ctx context.Context, momentID uuid.UUID) ([]*entity.MomentImage, error)) *MockMomentImageRepository_ListByMomentID_Call {
	_c.Call.Return(run)
	return _c
}
