// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProfileImageStorage creates a new instance of MockProfileImageStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileImageStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileImageStorage {
	mock := &MockProfileImageStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfileImageStorage is an autogenerated mock type for the ProfileImageStorage type
type MockProfileImageStorage struct {
	mock.Mock
}

type MockProfileImageStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileImageStorage) EXPECT() *MockProfileImageStorage_Expecter {
	return &MockProfileImageStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockProfileImageStorage
func (_mock *MockProfileImageStorage) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfileImageStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProfileImageStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockProfileImageStorage_Expecter) Delete(ctx any, key any) *MockProfileImageStorage_Delete_Call {
	return &MockProfileImageStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockProfileImageStorage_Delete_Call) Run(run func(ctx context.Context, key string)) *MockProfileImageStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileImageStorage_Delete_Call) Return(err error) *MockProfileImageStorage_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfileImageStorage_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockProfileImageStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// PublicURL provides a mock function for the type MockProfileImageStorage
func (_mock *MockProfileImageStorage) PublicURL(key string) string {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for PublicURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProfileImageStorage_PublicURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublicURL'
type MockProfileImageStorage_PublicURL_Call struct {
	*mock.Call
}

// PublicURL is a helper method to define mock.On call
//   - key string
func (_e *MockProfileImageStorage_Expecter) PublicURL(key any) *MockProfileImageStorage_PublicURL_Call {
	return &MockProfileImageStorage_PublicURL_Call{Call: _e.mock.On("PublicURL", key)}
}

func (_c *MockProfileImageStorage_PublicURL_Call) Run(run func(key string)) *MockProfileImageStorage_PublicURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfileImageStorage_PublicURL_Call) Return(s string) *MockProfileImageStorage_PublicURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProfileImageStorage_PublicURL_Call) RunAndReturn(run func(key string) string) *MockProfileImageStorage_PublicURL_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockProfileImageStorage
func (_mock *MockProfileImageStorage) Put(ctx context.Context, key string, body io.Reader, size int64, contentType string) error {
	ret := _mock.Called(ctx, key, body, size, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string) error); ok {
		r0 = returnFunc(ctx, key, body, size, contentType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfileImageStorage_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockProfileImageStorage_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - body io.Reader
//   - size int64
//   - contentType string
func (_e *MockProfileImageStorage_Expecter) Put(ctx any, key any, body any, size any, contentType any) *MockProfileImageStorage_Put_Call {
	return &MockProfileImageStorage_Put_Call{Call: _e.mock.On("Put", ctx, key, body, size, contentType)}
}

func (_c *MockProfileImageStorage_Put_Call) Run(run func(ctx context.Context, key string, body io.Reader, size int64, contentType string)) *MockProfileImageStorage_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockProfileImageStorage_Put_Call) Return(err error) *MockProfileImageStorage_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfileImageStorage_Put_Call) RunAndReturn(run func(ctx context.Context, key string, body io.Reader, size int64, contentType string) error) *MockProfileImageStorage_Put_Call {
	_c.Call.Return(run)
	return _c
}
