// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRefreshTokenGenerator creates a new instance of MockRefreshTokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenGenerator {
	mock := &MockRefreshTokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRefreshTokenGenerator is an autogenerated mock type for the RefreshTokenGenerator type
type MockRefreshTokenGenerator struct {
	mock.Mock
}

type MockRefreshTokenGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenGenerator) EXPECT() *MockRefreshTokenGenerator_Expecter {
	return &MockRefreshTokenGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockRefreshTokenGenerator
func (_mock *MockRefreshTokenGenerator) Generate() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRefreshTokenGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockRefreshTokenGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *MockRefreshTokenGenerator_Expecter) Generate() *MockRefreshTokenGenerator_Generate_Call {
	return &MockRefreshTokenGenerator_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *MockRefreshTokenGenerator_Generate_Call) Run(run func()) *MockRefreshTokenGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRefreshTokenGenerator_Generate_Call) Return(raw string, err error) *MockRefreshTokenGenerator_Generate_Call {
	_c.Call.Return(raw, err)
	return _c
}

func (_c *MockRefreshTokenGenerator_Generate_Call) RunAndReturn(run func() (string, error)) *MockRefreshTokenGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type MockRefreshTokenGenerator
func (_mock *MockRefreshTokenGenerator) Hash(raw string) string {
	ret := _mock.Called(raw)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(raw)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRefreshTokenGenerator_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockRefreshTokenGenerator_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - raw string
func (_e *MockRefreshTokenGenerator_Expecter) Hash(raw any) *MockRefreshTokenGenerator_Hash_Call {
	return &MockRefreshTokenGenerator_Hash_Call{Call: _e.mock.On("Hash", raw)}
}

func (_c *MockRefreshTokenGenerator_Hash_Call) Run(run func(raw string)) *MockRefreshTokenGenerator_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRefreshTokenGenerator_Hash_Call) Return(s string) *MockRefreshTokenGenerator_Hash_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRefreshTokenGenerator_Hash_Call) RunAndReturn(run func(raw string) string) *MockRefreshTokenGenerator_Hash_Call {
	_c.Call.Return(run)
	return _c
}
