// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ngodingvareng/memoria/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockResponseEventRepository creates a new instance of MockResponseEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResponseEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResponseEventRepository {
	mock := &MockResponseEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResponseEventRepository is an autogenerated mock type for the ResponseEventRepository type
type MockResponseEventRepository struct {
	mock.Mock
}

type MockResponseEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResponseEventRepository) EXPECT() *MockResponseEventRepository_Expecter {
	return &MockResponseEventRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockResponseEventRepository
func (_mock *MockResponseEventRepository) Create(ctx context.Context, event *entity.ResponseEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.ResponseEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockResponseEventRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockResponseEventRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - event *entity.ResponseEvent
func (_e *MockResponseEventRepository_Expecter) Create(ctx any, event any) *MockResponseEventRepository_Create_Call {
	return &MockResponseEventRepository_Create_Call{Call: _e.mock.On("Create", ctx, event)}
}

func (_c *MockResponseEventRepository_Create_Call) Run(run func(ctx context.Context, event *entity.ResponseEvent)) *MockResponseEventRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.ResponseEvent
		if args[1] != nil {
			arg1 = args[1].(*entity.ResponseEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockResponseEventRepository_Create_Call) Return(err error) *MockResponseEventRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockResponseEventRepository_Create_Call) RunAndReturn(run func(ctx context.Context, event *entity.ResponseEvent) error) *MockResponseEventRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
