// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/ngodingvareng/memoria/internal/entity"
	"github.com/ngodingvareng/memoria/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewMockThreadRepository creates a new instance of MockThreadRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockThreadRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockThreadRepository {
	mock := &MockThreadRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockThreadRepository is an autogenerated mock type for the ThreadRepository type
type MockThreadRepository struct {
	mock.Mock
}

type MockThreadRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockThreadRepository) EXPECT() *MockThreadRepository_Expecter {
	return &MockThreadRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockThreadRepository
func (_mock *MockThreadRepository) Create(ctx context.Context, thread *entity.Thread) (*entity.Thread, error) {
	ret := _mock.Called(ctx, thread)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Thread
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Thread) (*entity.Thread, error)); ok {
		return returnFunc(ctx, thread)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Thread) *entity.Thread); ok {
		r0 = returnFunc(ctx, thread)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Thread)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Thread) error); ok {
		r1 = returnFunc(ctx, thread)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockThreadRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockThreadRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - thread *entity.Thread
func (_e *MockThreadRepository_Expecter) Create(ctx any, thread any) *MockThreadRepository_Create_Call {
	return &MockThreadRepository_Create_Call{Call: _e.mock.On("Create", ctx, thread)}
}

func (_c *MockThreadRepository_Create_Call) Run(run func(ctx context.Context, thread *entity.Thread)) *MockThreadRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Thread
		if args[1] != nil {
			arg1 = args[1].(*entity.Thread)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockThreadRepository_Create_Call) Return(thread1 *entity.Thread, err error) *MockThreadRepository_Create_Call {
	_c.Call.Return(thread1, err)
	return _c
}

func (_c *MockThreadRepository_Create_Call) RunAndReturn(run func(ctx context.Context, thread *entity.Thread) (*entity.Thread, error)) *MockThreadRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockThreadRepository
func (_mock *MockThreadRepository) GetByID(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entity.Thread, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Thread
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.Thread, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.Thread); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Thread)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockThreadRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockThreadRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockThreadRepository_Expecter) GetByID(ctx any, id any, userID any) *MockThreadRepository_GetByID_Call {
	return &MockThreadRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id, userID)}
}

func (_c *MockThreadRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockThreadRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockThreadRepository_GetByID_Call) Return(thread *entity.Thread, err error) *MockThreadRepository_GetByID_Call {
	_c.Call.Return(thread, err)
	return _c
}

func (_c *MockThreadRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entity.Thread, error)) *MockThreadRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockThreadRepository
func (_mock *MockThreadRepository) Search(ctx context.Context, params usecase.SearchThreadsParams) ([]*entity.Thread, int64, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*entity.Thread
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.SearchThreadsParams) ([]*entity.Thread, int64, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.SearchThreadsParams) []*entity.Thread); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Thread)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecase.SearchThreadsParams) int64); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, usecase.SearchThreadsParams) error); ok {
		r2 = returnFunc(ctx, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockThreadRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockThreadRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - params usecase.SearchThreadsParams
func (_e *MockThreadRepository_Expecter) Search(ctx any, params any) *MockThreadRepository_Search_Call {
	return &MockThreadRepository_Search_Call{Call: _e.mock.On("Search", ctx, params)}
}

func (_c *MockThreadRepository_Search_Call) Run(run func(ctx context.Context, params usecase.SearchThreadsParams)) *MockThreadRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.SearchThreadsParams
		if args[1] != nil {
			arg1 = args[1].(usecase.SearchThreadsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockThreadRepository_Search_Call) Return(threads []*entity.Thread, n int64, err error) *MockThreadRepository_Search_Call {
	_c.Call.Return(threads, n, err)
	return _c
}

func (_c *MockThreadRepository_Search_Call) RunAndReturn(run func(ctx context.Context, params usecase.SearchThreadsParams) ([]*entity.Thread, int64, error)) *MockThreadRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function for the type MockThreadRepository
func (_mock *MockThreadRepository) SoftDelete(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockThreadRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockThreadRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockThreadRepository_Expecter) SoftDelete(ctx any, id any, userID any) *MockThreadRepository_SoftDelete_Call {
	return &MockThreadRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id, userID)}
}

func (_c *MockThreadRepository_SoftDelete_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockThreadRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockThreadRepository_SoftDelete_Call) Return(err error) *MockThreadRepository_SoftDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockThreadRepository_SoftDelete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockThreadRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockThreadRepository
func (_mock *MockThreadRepository) Update(ctx context.Context, thread *entity.Thread) (*entity.Thread, error) {
	ret := _mock.Called(ctx, thread)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.Thread
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Thread) (*entity.Thread, error)); ok {
		return returnFunc(ctx, thread)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Thread) *entity.Thread); ok {
		r0 = returnFunc(ctx, thread)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Thread)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Thread) error); ok {
		r1 = returnFunc(ctx, thread)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockThreadRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockThreadRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - thread *entity.Thread
func (_e *MockThreadRepository_Expecter) Update(ctx any, thread any) *MockThreadRepository_Update_Call {
	return &MockThreadRepository_Update_Call{Call: _e.mock.On("Update", ctx, thread)}
}

func (_c *MockThreadRepository_Update_Call) Run(run func(ctx context.Context, thread *entity.Thread)) *MockThreadRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Thread
		if args[1] != nil {
			arg1 = args[1].(*entity.Thread)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockThreadRepository_Update_Call) Return(thread1 *entity.Thread, err error) *MockThreadRepository_Update_Call {
	_c.Call.Return(thread1, err)
	return _c
}

func (_c *MockThreadRepository_Update_Call) RunAndReturn(run func(ctx context.Context, thread *entity.Thread) (*entity.Thread, error)) *MockThreadRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithTransaction provides a mock function for the type MockThreadRepository
func (_mock *MockThreadRepository) WithTransaction(ctx context.Context, fn func(usecase.ThreadRepository) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(usecase.ThreadRepository) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockThreadRepository_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type MockThreadRepository_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(usecase.ThreadRepository) error
func (_e *MockThreadRepository_Expecter) WithTransaction(ctx any, fn any) *MockThreadRepository_WithTransaction_Call {
	return &MockThreadRepository_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, fn)}
}

func (_c *MockThreadRepository_WithTransaction_Call) Run(run func(ctx context.Context, fn func(usecase.ThreadRepository) error)) *MockThreadRepository_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(usecase.ThreadRepository) error
		if args[1] != nil {
			arg1 = args[1].(func(usecase.ThreadRepository) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockThreadRepository_WithTransaction_Call) Return(err error) *MockThreadRepository_WithTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockThreadRepository_WithTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(usecase.ThreadRepository) error) error) *MockThreadRepository_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}
