// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenGenerator creates a new instance of MockTokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenGenerator {
	mock := &MockTokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenGenerator is an autogenerated mock type for the TokenGenerator type
type MockTokenGenerator struct {
	mock.Mock
}

type MockTokenGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenGenerator) EXPECT() *MockTokenGenerator_Expecter {
	return &MockTokenGenerator_Expecter{mock: &_m.Mock}
}

// GenerateSessionToken provides a mock function for the type MockTokenGenerator
func (_mock *MockTokenGenerator) GenerateSessionToken() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateSessionToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenGenerator_GenerateSessionToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateSessionToken'
type MockTokenGenerator_GenerateSessionToken_Call struct {
	*mock.Call
}

// GenerateSessionToken is a helper method to define mock.On call
func (_e *MockTokenGenerator_Expecter) GenerateSessionToken() *MockTokenGenerator_GenerateSessionToken_Call {
	return &MockTokenGenerator_GenerateSessionToken_Call{Call: _e.mock.On("GenerateSessionToken")}
}

func (_c *MockTokenGenerator_GenerateSessionToken_Call) Run(run func()) *MockTokenGenerator_GenerateSessionToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenGenerator_GenerateSessionToken_Call) Return(s string, err error) *MockTokenGenerator_GenerateSessionToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenGenerator_GenerateSessionToken_Call) RunAndReturn(run func() (string, error)) *MockTokenGenerator_GenerateSessionToken_Call {
	_c.Call.Return(run)
	return _c
}

// HashToken provides a mock function for the type MockTokenGenerator
func (_mock *MockTokenGenerator) HashToken(rawToken string) string {
	ret := _mock.Called(rawToken)

	if len(ret) == 0 {
		panic("no return value specified for HashToken")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(rawToken)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTokenGenerator_HashToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashToken'
type MockTokenGenerator_HashToken_Call struct {
	*mock.Call
}

// HashToken is a helper method to define mock.On call
//   - rawToken string
func (_e *MockTokenGenerator_Expecter) HashToken(rawToken any) *MockTokenGenerator_HashToken_Call {
	return &MockTokenGenerator_HashToken_Call{Call: _e.mock.On("HashToken", rawToken)}
}

func (_c *MockTokenGenerator_HashToken_Call) Run(run func(rawToken string)) *MockTokenGenerator_HashToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenGenerator_HashToken_Call) Return(s string) *MockTokenGenerator_HashToken_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTokenGenerator_HashToken_Call) RunAndReturn(run func(rawToken string) string) *MockTokenGenerator_HashToken_Call {
	_c.Call.Return(run)
	return _c
}
