// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/ngodingvareng/memoria/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserSessionRepository creates a new instance of MockUserSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserSessionRepository {
	mock := &MockUserSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserSessionRepository is an autogenerated mock type for the UserSessionRepository type
type MockUserSessionRepository struct {
	mock.Mock
}

type MockUserSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserSessionRepository) EXPECT() *MockUserSessionRepository_Expecter {
	return &MockUserSessionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserSessionRepository
func (_mock *MockUserSessionRepository) Create(ctx context.Context, session *entity.UserSession) (*entity.UserSession, error) {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.UserSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.UserSession) (*entity.UserSession, error)); ok {
		return returnFunc(ctx, session)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.UserSession) *entity.UserSession); ok {
		r0 = returnFunc(ctx, session)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.UserSession) error); ok {
		r1 = returnFunc(ctx, session)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserSessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserSessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *entity.UserSession
func (_e *MockUserSessionRepository_Expecter) Create(ctx any, session any) *MockUserSessionRepository_Create_Call {
	return &MockUserSessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *MockUserSessionRepository_Create_Call) Run(run func(ctx context.Context, session *entity.UserSession)) *MockUserSessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.UserSession
		if args[1] != nil {
			arg1 = args[1].(*entity.UserSession)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserSessionRepository_Create_Call) Return(userSession *entity.UserSession, err error) *MockUserSessionRepository_Create_Call {
	_c.Call.Return(userSession, err)
	return _c
}

func (_c *MockUserSessionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, session *entity.UserSession) (*entity.UserSession, error)) *MockUserSessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllByUserID provides a mock function for the type MockUserSessionRepository
func (_mock *MockUserSessionRepository) DeleteAllByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserSessionRepository_DeleteAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllByUserID'
type MockUserSessionRepository_DeleteAllByUserID_Call struct {
	*mock.Call
}

// DeleteAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserSessionRepository_Expecter) DeleteAllByUserID(ctx any, userID any) *MockUserSessionRepository_DeleteAllByUserID_Call {
	return &MockUserSessionRepository_DeleteAllByUserID_Call{Call: _e.mock.On("DeleteAllByUserID", ctx, userID)}
}

func (_c *MockUserSessionRepository_DeleteAllByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserSessionRepository_DeleteAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserSessionRepository_DeleteAllByUserID_Call) Return(err error) *MockUserSessionRepository_DeleteAllByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserSessionRepository_DeleteAllByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockUserSessionRepository_DeleteAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByTokenHash provides a mock function for the type MockUserSessionRepository
func (_mock *MockUserSessionRepository) DeleteByTokenHash(ctx context.Context, tokenHash string) error {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByTokenHash")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserSessionRepository_DeleteByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByTokenHash'
type MockUserSessionRepository_DeleteByTokenHash_Call struct {
	*mock.Call
}

// DeleteByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockUserSessionRepository_Expecter) DeleteByTokenHash(ctx any, tokenHash any) *MockUserSessionRepository_DeleteByTokenHash_Call {
	return &MockUserSessionRepository_DeleteByTokenHash_Call{Call: _e.mock.On("DeleteByTokenHash", ctx, tokenHash)}
}

func (_c *MockUserSessionRepository_DeleteByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockUserSessionRepository_DeleteByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserSessionRepository_DeleteByTokenHash_Call) Return(err error) *MockUserSessionRepository_DeleteByTokenHash_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserSessionRepository_DeleteByTokenHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) error) *MockUserSessionRepository_DeleteByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTokenHash provides a mock function for the type MockUserSessionRepository
func (_mock *MockUserSessionRepository) GetByTokenHash(ctx context.Context, tokenHash string) (*entity.UserSession, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByTokenHash")
	}

	var r0 *entity.UserSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.UserSession, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.UserSession); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserSessionRepository_GetByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTokenHash'
type MockUserSessionRepository_GetByTokenHash_Call struct {
	*mock.Call
}

// GetByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockUserSessionRepository_Expecter) GetByTokenHash(ctx any, tokenHash any) *MockUserSessionRepository_GetByTokenHash_Call {
	return &MockUserSessionRepository_GetByTokenHash_Call{Call: _e.mock.On("GetByTokenHash", ctx, tokenHash)}
}

func (_c *MockUserSessionRepository_GetByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockUserSessionRepository_GetByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserSessionRepository_GetByTokenHash_Call) Return(userSession *entity.UserSession, err error) *MockUserSessionRepository_GetByTokenHash_Call {
	_c.Call.Return(userSession, err)
	return _c
}

func (_c *MockUserSessionRepository_GetByTokenHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (*entity.UserSession, error)) *MockUserSessionRepository_GetByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}
