// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/ngodingvareng/memoria/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserAccountRepository creates a new instance of MockUserAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserAccountRepository {
	mock := &MockUserAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserAccountRepository is an autogenerated mock type for the UserAccountRepository type
type MockUserAccountRepository struct {
	mock.Mock
}

type MockUserAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserAccountRepository) EXPECT() *MockUserAccountRepository_Expecter {
	return &MockUserAccountRepository_Expecter{mock: &_m.Mock}
}

// CreateCredential provides a mock function for the type MockUserAccountRepository
func (_mock *MockUserAccountRepository) CreateCredential(ctx context.Context, userID uuid.UUID, accountID string, passwordHash string) (*entity.UserAccount, error) {
	ret := _mock.Called(ctx, userID, accountID, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateCredential")
	}

	var r0 *entity.UserAccount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (*entity.UserAccount, error)); ok {
		return returnFunc(ctx, userID, accountID, passwordHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) *entity.UserAccount); ok {
		r0 = returnFunc(ctx, userID, accountID, passwordHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserAccount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = returnFunc(ctx, userID, accountID, passwordHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAccountRepository_CreateCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCredential'
type MockUserAccountRepository_CreateCredential_Call struct {
	*mock.Call
}

// CreateCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - accountID string
//   - passwordHash string
func (_e *MockUserAccountRepository_Expecter) CreateCredential(ctx any, userID any, accountID any, passwordHash any) *MockUserAccountRepository_CreateCredential_Call {
	return &MockUserAccountRepository_CreateCredential_Call{Call: _e.mock.On("CreateCredential", ctx, userID, accountID, passwordHash)}
}

func (_c *MockUserAccountRepository_CreateCredential_Call) Run(run func(ctx context.Context, userID uuid.UUID, accountID string, passwordHash string)) *MockUserAccountRepository_CreateCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserAccountRepository_CreateCredential_Call) Return(userAccount *entity.UserAccount, err error) *MockUserAccountRepository_CreateCredential_Call {
	_c.Call.Return(userAccount, err)
	return _c
}

func (_c *MockUserAccountRepository_CreateCredential_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, accountID string, passwordHash string) (*entity.UserAccount, error)) *MockUserAccountRepository_CreateCredential_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredentialByUserID provides a mock function for the type MockUserAccountRepository
func (_mock *MockUserAccountRepository) GetCredentialByUserID(ctx context.Context, userID uuid.UUID) (*entity.UserAccount, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCredentialByUserID")
	}

	var r0 *entity.UserAccount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.UserAccount, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.UserAccount); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserAccount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAccountRepository_GetCredentialByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredentialByUserID'
type MockUserAccountRepository_GetCredentialByUserID_Call struct {
	*mock.Call
}

// GetCredentialByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserAccountRepository_Expecter) GetCredentialByUserID(ctx any, userID any) *MockUserAccountRepository_GetCredentialByUserID_Call {
	return &MockUserAccountRepository_GetCredentialByUserID_Call{Call: _e.mock.On("GetCredentialByUserID", ctx, userID)}
}

func (_c *MockUserAccountRepository_GetCredentialByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserAccountRepository_GetCredentialByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserAccountRepository_GetCredentialByUserID_Call) Return(userAccount *entity.UserAccount, err error) *MockUserAccountRepository_GetCredentialByUserID_Call {
	_c.Call.Return(userAccount, err)
	return _c
}

func (_c *MockUserAccountRepository_GetCredentialByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*entity.UserAccount, error)) *MockUserAccountRepository_GetCredentialByUserID_Call {
	_c.Call.Return(run)
	return _c
}
