// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/ngodingvareng/memoria/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserVerificationRepository creates a new instance of MockUserVerificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserVerificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserVerificationRepository {
	mock := &MockUserVerificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserVerificationRepository is an autogenerated mock type for the UserVerificationRepository type
type MockUserVerificationRepository struct {
	mock.Mock
}

type MockUserVerificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserVerificationRepository) EXPECT() *MockUserVerificationRepository_Expecter {
	return &MockUserVerificationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserVerificationRepository
func (_mock *MockUserVerificationRepository) Create(ctx context.Context, identifier string, value string, expiresAt time.Time) (*entity.UserVerification, error) {
	ret := _mock.Called(ctx, identifier, value, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.UserVerification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (*entity.UserVerification, error)); ok {
		return returnFunc(ctx, identifier, value, expiresAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) *entity.UserVerification); ok {
		r0 = returnFunc(ctx, identifier, value, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserVerification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = returnFunc(ctx, identifier, value, expiresAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserVerificationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserVerificationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
//   - value string
//   - expiresAt time.Time
func (_e *MockUserVerificationRepository_Expecter) Create(ctx any, identifier any, value any, expiresAt any) *MockUserVerificationRepository_Create_Call {
	return &MockUserVerificationRepository_Create_Call{Call: _e.mock.On("Create", ctx, identifier, value, expiresAt)}
}

func (_c *MockUserVerificationRepository_Create_Call) Run(run func(ctx context.Context, identifier string, value string, expiresAt time.Time)) *MockUserVerificationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserVerificationRepository_Create_Call) Return(userVerification *entity.UserVerification, err error) *MockUserVerificationRepository_Create_Call {
	_c.Call.Return(userVerification, err)
	return _c
}

func (_c *MockUserVerificationRepository_Create_Call) RunAndReturn(run func(ctx context.Context, identifier string, value string, expiresAt time.Time) (*entity.UserVerification, error)) *MockUserVerificationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserVerificationRepository
func (_mock *MockUserVerificationRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserVerificationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserVerificationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserVerificationRepository_Expecter) Delete(ctx any, id any) *MockUserVerificationRepository_Delete_Call {
	return &MockUserVerificationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUserVerificationRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserVerificationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserVerificationRepository_Delete_Call) Return(err error) *MockUserVerificationRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserVerificationRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockUserVerificationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByIdentifier provides a mock function for the type MockUserVerificationRepository
func (_mock *MockUserVerificationRepository) DeleteByIdentifier(ctx context.Context, identifier string) error {
	ret := _mock.Called(ctx, identifier)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByIdentifier")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, identifier)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserVerificationRepository_DeleteByIdentifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByIdentifier'
type MockUserVerificationRepository_DeleteByIdentifier_Call struct {
	*mock.Call
}

// DeleteByIdentifier is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
func (_e *MockUserVerificationRepository_Expecter) DeleteByIdentifier(ctx any, identifier any) *MockUserVerificationRepository_DeleteByIdentifier_Call {
	return &MockUserVerificationRepository_DeleteByIdentifier_Call{Call: _e.mock.On("DeleteByIdentifier", ctx, identifier)}
}

func (_c *MockUserVerificationRepository_DeleteByIdentifier_Call) Run(run func(ctx context.Context, identifier string)) *MockUserVerificationRepository_DeleteByIdentifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserVerificationRepository_DeleteByIdentifier_Call) Return(err error) *MockUserVerificationRepository_DeleteByIdentifier_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserVerificationRepository_DeleteByIdentifier_Call) RunAndReturn(run func(ctx context.Context, identifier string) error) *MockUserVerificationRepository_DeleteByIdentifier_Call {
	_c.Call.Return(run)
	return _c
}

// GetValid provides a mock function for the type MockUserVerificationRepository
func (_mock *MockUserVerificationRepository) GetValid(ctx context.Context, identifier string, value string) (*entity.UserVerification, error) {
	ret := _mock.Called(ctx, identifier, value)

	if len(ret) == 0 {
		panic("no return value specified for GetValid")
	}

	var r0 *entity.UserVerification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*entity.UserVerification, error)); ok {
		return returnFunc(ctx, identifier, value)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *entity.UserVerification); ok {
		r0 = returnFunc(ctx, identifier, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserVerification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, identifier, value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserVerificationRepository_GetValid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetValid'
type MockUserVerificationRepository_GetValid_Call struct {
	*mock.Call
}

// GetValid is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
//   - value string
func (_e *MockUserVerificationRepository_Expecter) GetValid(ctx any, identifier any, value any) *MockUserVerificationRepository_GetValid_Call {
	return &MockUserVerificationRepository_GetValid_Call{Call: _e.mock.On("GetValid", ctx, identifier, value)}
}

func (_c *MockUserVerificationRepository_GetValid_Call) Run(run func(ctx context.Context, identifier string, value string)) *MockUserVerificationRepository_GetValid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserVerificationRepository_GetValid_Call) Return(userVerification *entity.UserVerification, err error) *MockUserVerificationRepository_GetValid_Call {
	_c.Call.Return(userVerification, err)
	return _c
}

func (_c *MockUserVerificationRepository_GetValid_Call) RunAndReturn(run func(ctx context.Context, identifier string, value string) (*entity.UserVerification, error)) *MockUserVerificationRepository_GetValid_Call {
	_c.Call.Return(run)
	return _c
}
