// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/ngodingvareng/memoria/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserSearcher creates a new instance of MockUserSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserSearcher {
	mock := &MockUserSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserSearcher is an autogenerated mock type for the UserSearcher type
type MockUserSearcher struct {
	mock.Mock
}

type MockUserSearcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserSearcher) EXPECT() *MockUserSearcher_Expecter {
	return &MockUserSearcher_Expecter{mock: &_m.Mock}
}

// SearchByUsernamePrefix provides a mock function for the type MockUserSearcher
func (_mock *MockUserSearcher) SearchByUsernamePrefix(ctx context.Context, excludeUserID uuid.UUID, query string, limit int32) ([]*entity.User, error) {
	ret := _mock.Called(ctx, excludeUserID, query, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchByUsernamePrefix")
	}

	var r0 []*entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int32) ([]*entity.User, error)); ok {
		return returnFunc(ctx, excludeUserID, query, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int32) []*entity.User); ok {
		r0 = returnFunc(ctx, excludeUserID, query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int32) error); ok {
		r1 = returnFunc(ctx, excludeUserID, query, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserSearcher_SearchByUsernamePrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByUsernamePrefix'
type MockUserSearcher_SearchByUsernamePrefix_Call struct {
	*mock.Call
}

// SearchByUsernamePrefix is a helper method to define mock.On call
//   - ctx context.Context
//   - excludeUserID uuid.UUID
//   - query string
//   - limit int32
func (_e *MockUserSearcher_Expecter) SearchByUsernamePrefix(ctx any, excludeUserID any, query any, limit any) *MockUserSearcher_SearchByUsernamePrefix_Call {
	return &MockUserSearcher_SearchByUsernamePrefix_Call{Call: _e.mock.On("SearchByUsernamePrefix", ctx, excludeUserID, query, limit)}
}

func (_c *MockUserSearcher_SearchByUsernamePrefix_Call) Run(run func(ctx context.Context, excludeUserID uuid.UUID, query string, limit int32)) *MockUserSearcher_SearchByUsernamePrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserSearcher_SearchByUsernamePrefix_Call) Return(users []*entity.User, err error) *MockUserSearcher_SearchByUsernamePrefix_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserSearcher_SearchByUsernamePrefix_Call) RunAndReturn(run func(ctx context.Context, excludeUserID uuid.UUID, query string, limit int32) ([]*entity.User, error)) *MockUserSearcher_SearchByUsernamePrefix_Call {
	_c.Call.Return(run)
	return _c
}
