// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserBlockChecker creates a new instance of MockUserBlockChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserBlockChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserBlockChecker {
	mock := &MockUserBlockChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserBlockChecker is an autogenerated mock type for the UserBlockChecker type
type MockUserBlockChecker struct {
	mock.Mock
}

type MockUserBlockChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserBlockChecker) EXPECT() *MockUserBlockChecker_Expecter {
	return &MockUserBlockChecker_Expecter{mock: &_m.Mock}
}

// IsBlockedEitherDirection provides a mock function for the type MockUserBlockChecker
func (_mock *MockUserBlockChecker) IsBlockedEitherDirection(ctx context.Context, userA uuid.UUID, userB uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, userA, userB)

	if len(ret) == 0 {
		panic("no return value specified for IsBlockedEitherDirection")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, userA, userB)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, userA, userB)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userA, userB)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserBlockChecker_IsBlockedEitherDirection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBlockedEitherDirection'
type MockUserBlockChecker_IsBlockedEitherDirection_Call struct {
	*mock.Call
}

// IsBlockedEitherDirection is a helper method to define mock.On call
//   - ctx context.Context
//   - userA uuid.UUID
//   - userB uuid.UUID
func (_e *MockUserBlockChecker_Expecter) IsBlockedEitherDirection(ctx any, userA any, userB any) *MockUserBlockChecker_IsBlockedEitherDirection_Call {
	return &MockUserBlockChecker_IsBlockedEitherDirection_Call{Call: _e.mock.On("IsBlockedEitherDirection", ctx, userA, userB)}
}

func (_c *MockUserBlockChecker_IsBlockedEitherDirection_Call) Run(run func(ctx context.Context, userA uuid.UUID, userB uuid.UUID)) *MockUserBlockChecker_IsBlockedEitherDirection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserBlockChecker_IsBlockedEitherDirection_Call) Return(b bool, err error) *MockUserBlockChecker_IsBlockedEitherDirection_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserBlockChecker_IsBlockedEitherDirection_Call) RunAndReturn(run func(ctx context.Context, userA uuid.UUID, userB uuid.UUID) (bool, error)) *MockUserBlockChecker_IsBlockedEitherDirection_Call {
	_c.Call.Return(run)
	return _c
}
