// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/ngodingvareng/memoria/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserPolicyReader creates a new instance of MockUserPolicyReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserPolicyReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserPolicyReader {
	mock := &MockUserPolicyReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserPolicyReader is an autogenerated mock type for the UserPolicyReader type
type MockUserPolicyReader struct {
	mock.Mock
}

type MockUserPolicyReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserPolicyReader) EXPECT() *MockUserPolicyReader_Expecter {
	return &MockUserPolicyReader_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockUserPolicyReader
func (_mock *MockUserPolicyReader) GetByID(ctx context.Context, id uuid.UUID) (*entity.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserPolicyReader_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserPolicyReader_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserPolicyReader_Expecter) GetByID(ctx any, id any) *MockUserPolicyReader_GetByID_Call {
	return &MockUserPolicyReader_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserPolicyReader_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserPolicyReader_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserPolicyReader_GetByID_Call) Return(user *entity.User, err error) *MockUserPolicyReader_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserPolicyReader_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.User, error)) *MockUserPolicyReader_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function for the type MockUserPolicyReader
func (_mock *MockUserPolicyReader) GetByUsername(ctx context.Context, username string) (*entity.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserPolicyReader_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type MockUserPolicyReader_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserPolicyReader_Expecter) GetByUsername(ctx any, username any) *MockUserPolicyReader_GetByUsername_Call {
	return &MockUserPolicyReader_GetByUsername_Call{Call: _e.mock.On("GetByUsername", ctx, username)}
}

func (_c *MockUserPolicyReader_GetByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserPolicyReader_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserPolicyReader_GetByUsername_Call) Return(user *entity.User, err error) *MockUserPolicyReader_GetByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserPolicyReader_GetByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*entity.User, error)) *MockUserPolicyReader_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}
