// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserKnownChecker creates a new instance of MockUserKnownChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserKnownChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserKnownChecker {
	mock := &MockUserKnownChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserKnownChecker is an autogenerated mock type for the UserKnownChecker type
type MockUserKnownChecker struct {
	mock.Mock
}

type MockUserKnownChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserKnownChecker) EXPECT() *MockUserKnownChecker_Expecter {
	return &MockUserKnownChecker_Expecter{mock: &_m.Mock}
}

// IsKnownTo provides a mock function for the type MockUserKnownChecker
func (_mock *MockUserKnownChecker) IsKnownTo(ctx context.Context, ownerUserID uuid.UUID, otherUserID uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, ownerUserID, otherUserID)

	if len(ret) == 0 {
		panic("no return value specified for IsKnownTo")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, ownerUserID, otherUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, ownerUserID, otherUserID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ownerUserID, otherUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserKnownChecker_IsKnownTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsKnownTo'
type MockUserKnownChecker_IsKnownTo_Call struct {
	*mock.Call
}

// IsKnownTo is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerUserID uuid.UUID
//   - otherUserID uuid.UUID
func (_e *MockUserKnownChecker_Expecter) IsKnownTo(ctx any, ownerUserID any, otherUserID any) *MockUserKnownChecker_IsKnownTo_Call {
	return &MockUserKnownChecker_IsKnownTo_Call{Call: _e.mock.On("IsKnownTo", ctx, ownerUserID, otherUserID)}
}

func (_c *MockUserKnownChecker_IsKnownTo_Call) Run(run func(ctx context.Context, ownerUserID uuid.UUID, otherUserID uuid.UUID)) *MockUserKnownChecker_IsKnownTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserKnownChecker_IsKnownTo_Call) Return(b bool, err error) *MockUserKnownChecker_IsKnownTo_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserKnownChecker_IsKnownTo_Call) RunAndReturn(run func(ctx context.Context, ownerUserID uuid.UUID, otherUserID uuid.UUID) (bool, error)) *MockUserKnownChecker_IsKnownTo_Call {
	_c.Call.Return(run)
	return _c
}
