/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as UserRouteImport } from './routes/_user'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HelpRouteImport } from './routes/help'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUsernameRouteImport } from './routes/_app/$username'
import { Route as AppCircleRouteImport } from './routes/_app/_circle'
import { Route as AppMentionsRouteImport } from './routes/_app/mentions'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthWelcomeRouteImport } from './routes/_auth/welcome'
import { Route as AppAlbumIndexRouteImport } from './routes/_app/album.index'
import { Route as AppCircleIndexRouteImport } from './routes/_app/circle.index'
import { Route as AppCircleNewRouteImport } from './routes/_app/circle.new'
import { Route as AppMomentNewRouteImport } from './routes/_app/moment.new'
import { Route as AppRecapPeriodRouteImport } from './routes/_app/recap.$period'
import { Route as AppThreadIndexRouteImport } from './routes/_app/thread.index'
import { Route as AppThreadNewRouteImport } from './routes/_app/thread.new'
import { Route as UserUserIndexRouteImport } from './routes/_user/user.index'
import { Route as UserUserAccountRouteImport } from './routes/_user/user.account'
import { Route as UserUserNotificationRouteImport } from './routes/_user/user.notification'
import { Route as UserUserPrivacyRouteImport } from './routes/_user/user.privacy'
import { Route as UserUserThreadsRouteImport } from './routes/_user/user.threads'
import { Route as AppThreadIdIndexRouteImport } from './routes/_app/thread.$id.index'
import { Route as AppThreadIdManageRouteImport } from './routes/_app/thread.$id.manage'
import { Route as AppCircleCIdIndexRouteImport } from './routes/_app/_circle/c.$id.index'
import { Route as AppCircleCIdAlbumRouteImport } from './routes/_app/_circle/c.$id.album'
import { Route as AppCircleCIdInviteRouteImport } from './routes/_app/_circle/c.$id.invite'
import { Route as AppCircleCIdMemberRouteImport } from './routes/_app/_circle/c.$id.member'
import { Route as AppCircleCIdSettingsRouteImport } from './routes/_app/_circle/c.$id.settings'
import { Route as AppCircleCIdThreadRouteImport } from './routes/_app/_circle/c.$id.thread'
import { Route as AppThreadIdMomentsMomentIdRouteImport } from './routes/_app/thread.$id.moments.$momentId'
import { Route as AppCircleCIdJoinCodeRouteImport } from './routes/_app/_circle/c.$id.join.$code'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsernameRoute = AppUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => AppRoute,
} as any)
const AppCircleRoute = AppCircleRouteImport.update({
  id: '/_circle',
  getParentRoute: () => AppRoute,
} as any)
const AppMentionsRoute = AppMentionsRouteImport.update({
  id: '/mentions',
  path: '/mentions',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWelcomeRoute = AuthWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthRoute,
} as any)
const AppAlbumIndexRoute = AppAlbumIndexRouteImport.update({
  id: '/album/',
  path: '/album/',
  getParentRoute: () => AppRoute,
} as any)
const AppCircleIndexRoute = AppCircleIndexRouteImport.update({
  id: '/circle/',
  path: '/circle/',
  getParentRoute: () => AppRoute,
} as any)
const AppCircleNewRoute = AppCircleNewRouteImport.update({
  id: '/circle/new',
  path: '/circle/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMomentNewRoute = AppMomentNewRouteImport.update({
  id: '/moment/new',
  path: '/moment/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRecapPeriodRoute = AppRecapPeriodRouteImport.update({
  id: '/recap/$period',
  path: '/recap/$period',
  getParentRoute: () => AppRoute,
} as any)
const AppThreadIndexRoute = AppThreadIndexRouteImport.update({
  id: '/thread/',
  path: '/thread/',
  getParentRoute: () => AppRoute,
} as any)
const AppThreadNewRoute = AppThreadNewRouteImport.update({
  id: '/thread/new',
  path: '/thread/new',
  getParentRoute: () => AppRoute,
} as any)
const UserUserIndexRoute = UserUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => UserRoute,
} as any)
const UserUserAccountRoute = UserUserAccountRouteImport.update({
  id: '/user/account',
  path: '/user/account',
  getParentRoute: () => UserRoute,
} as any)
const UserUserNotificationRoute = UserUserNotificationRouteImport.update({
  id: '/user/notification',
  path: '/user/notification',
  getParentRoute: () => UserRoute,
} as any)
const UserUserPrivacyRoute = UserUserPrivacyRouteImport.update({
  id: '/user/privacy',
  path: '/user/privacy',
  getParentRoute: () => UserRoute,
} as any)
const UserUserThreadsRoute = UserUserThreadsRouteImport.update({
  id: '/user/threads',
  path: '/user/threads',
  getParentRoute: () => UserRoute,
} as any)
const AppThreadIdIndexRoute = AppThreadIdIndexRouteImport.update({
  id: '/thread/$id/',
  path: '/thread/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppThreadIdManageRoute = AppThreadIdManageRouteImport.update({
  id: '/thread/$id/manage',
  path: '/thread/$id/manage',
  getParentRoute: () => AppRoute,
} as any)
const AppCircleCIdIndexRoute = AppCircleCIdIndexRouteImport.update({
  id: '/c/$id/',
  path: '/c/$id/',
  getParentRoute: () => AppCircleRoute,
} as any)
const AppCircleCIdAlbumRoute = AppCircleCIdAlbumRouteImport.update({
  id: '/c/$id/album',
  path: '/c/$id/album',
  getParentRoute: () => AppCircleRoute,
} as any)
const AppCircleCIdInviteRoute = AppCircleCIdInviteRouteImport.update({
  id: '/c/$id/invite',
  path: '/c/$id/invite',
  getParentRoute: () => AppCircleRoute,
} as any)
const AppCircleCIdMemberRoute = AppCircleCIdMemberRouteImport.update({
  id: '/c/$id/member',
  path: '/c/$id/member',
  getParentRoute: () => AppCircleRoute,
} as any)
const AppCircleCIdSettingsRoute = AppCircleCIdSettingsRouteImport.update({
  id: '/c/$id/settings',
  path: '/c/$id/settings',
  getParentRoute: () => AppCircleRoute,
} as any)
const AppCircleCIdThreadRoute = AppCircleCIdThreadRouteImport.update({
  id: '/c/$id/thread',
  path: '/c/$id/thread',
  getParentRoute: () => AppCircleRoute,
} as any)
const AppThreadIdMomentsMomentIdRoute =
  AppThreadIdMomentsMomentIdRouteImport.update({
    id: '/thread/$id/moments/$momentId',
    path: '/thread/$id/moments/$momentId',
    getParentRoute: () => AppRoute,
  } as any)
const AppCircleCIdJoinCodeRoute = AppCircleCIdJoinCodeRouteImport.update({
  id: '/c/$id/join/$code',
  path: '/c/$id/join/$code',
  getParentRoute: () => AppCircleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$username': typeof AppUsernameRoute
  '/mentions': typeof AppMentionsRoute
  '/notifications': typeof AppNotificationsRoute
  '/search': typeof AppSearchRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/welcome': typeof AuthWelcomeRoute
  '/circle/new': typeof AppCircleNewRoute
  '/moment/new': typeof AppMomentNewRoute
  '/recap/$period': typeof AppRecapPeriodRoute
  '/thread/new': typeof AppThreadNewRoute
  '/user/account': typeof UserUserAccountRoute
  '/user/notification': typeof UserUserNotificationRoute
  '/user/privacy': typeof UserUserPrivacyRoute
  '/user/threads': typeof UserUserThreadsRoute
  '/album/': typeof AppAlbumIndexRoute
  '/circle/': typeof AppCircleIndexRoute
  '/thread/': typeof AppThreadIndexRoute
  '/user/': typeof UserUserIndexRoute
  '/thread/$id/manage': typeof AppThreadIdManageRoute
  '/thread/$id/': typeof AppThreadIdIndexRoute
  '/c/$id/album': typeof AppCircleCIdAlbumRoute
  '/c/$id/invite': typeof AppCircleCIdInviteRoute
  '/c/$id/member': typeof AppCircleCIdMemberRoute
  '/c/$id/settings': typeof AppCircleCIdSettingsRoute
  '/c/$id/thread': typeof AppCircleCIdThreadRoute
  '/thread/$id/moments/$momentId': typeof AppThreadIdMomentsMomentIdRoute
  '/c/$id/': typeof AppCircleCIdIndexRoute
  '/c/$id/join/$code': typeof AppCircleCIdJoinCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$username': typeof AppUsernameRoute
  '/mentions': typeof AppMentionsRoute
  '/notifications': typeof AppNotificationsRoute
  '/search': typeof AppSearchRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/welcome': typeof AuthWelcomeRoute
  '/circle/new': typeof AppCircleNewRoute
  '/moment/new': typeof AppMomentNewRoute
  '/recap/$period': typeof AppRecapPeriodRoute
  '/thread/new': typeof AppThreadNewRoute
  '/user/account': typeof UserUserAccountRoute
  '/user/notification': typeof UserUserNotificationRoute
  '/user/privacy': typeof UserUserPrivacyRoute
  '/user/threads': typeof UserUserThreadsRoute
  '/album': typeof AppAlbumIndexRoute
  '/circle': typeof AppCircleIndexRoute
  '/thread': typeof AppThreadIndexRoute
  '/user': typeof UserUserIndexRoute
  '/thread/$id/manage': typeof AppThreadIdManageRoute
  '/thread/$id': typeof AppThreadIdIndexRoute
  '/c/$id/album': typeof AppCircleCIdAlbumRoute
  '/c/$id/invite': typeof AppCircleCIdInviteRoute
  '/c/$id/member': typeof AppCircleCIdMemberRoute
  '/c/$id/settings': typeof AppCircleCIdSettingsRoute
  '/c/$id/thread': typeof AppCircleCIdThreadRoute
  '/thread/$id/moments/$momentId': typeof AppThreadIdMomentsMomentIdRoute
  '/c/$id': typeof AppCircleCIdIndexRoute
  '/c/$id/join/$code': typeof AppCircleCIdJoinCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_user': typeof UserRouteWithChildren
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_app/$username': typeof AppUsernameRoute
  '/_app/_circle': typeof AppCircleRouteWithChildren
  '/_app/mentions': typeof AppMentionsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/search': typeof AppSearchRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/welcome': typeof AuthWelcomeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/circle/new': typeof AppCircleNewRoute
  '/_app/moment/new': typeof AppMomentNewRoute
  '/_app/recap/$period': typeof AppRecapPeriodRoute
  '/_app/thread/new': typeof AppThreadNewRoute
  '/_user/user/account': typeof UserUserAccountRoute
  '/_user/user/notification': typeof UserUserNotificationRoute
  '/_user/user/privacy': typeof UserUserPrivacyRoute
  '/_user/user/threads': typeof UserUserThreadsRoute
  '/_app/album/': typeof AppAlbumIndexRoute
  '/_app/circle/': typeof AppCircleIndexRoute
  '/_app/thread/': typeof AppThreadIndexRoute
  '/_user/user/': typeof UserUserIndexRoute
  '/_app/thread/$id/manage': typeof AppThreadIdManageRoute
  '/_app/thread/$id/': typeof AppThreadIdIndexRoute
  '/_app/_circle/c/$id/album': typeof AppCircleCIdAlbumRoute
  '/_app/_circle/c/$id/invite': typeof AppCircleCIdInviteRoute
  '/_app/_circle/c/$id/member': typeof AppCircleCIdMemberRoute
  '/_app/_circle/c/$id/settings': typeof AppCircleCIdSettingsRoute
  '/_app/_circle/c/$id/thread': typeof AppCircleCIdThreadRoute
  '/_app/thread/$id/moments/$momentId': typeof AppThreadIdMomentsMomentIdRoute
  '/_app/_circle/c/$id/': typeof AppCircleCIdIndexRoute
  '/_app/_circle/c/$id/join/$code': typeof AppCircleCIdJoinCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/$username'
    | '/mentions'
    | '/notifications'
    | '/search'
    | '/signin'
    | '/signup'
    | '/welcome'
    | '/circle/new'
    | '/moment/new'
    | '/recap/$period'
    | '/thread/new'
    | '/user/account'
    | '/user/notification'
    | '/user/privacy'
    | '/user/threads'
    | '/album/'
    | '/circle/'
    | '/thread/'
    | '/user/'
    | '/thread/$id/manage'
    | '/thread/$id/'
    | '/c/$id/album'
    | '/c/$id/invite'
    | '/c/$id/member'
    | '/c/$id/settings'
    | '/c/$id/thread'
    | '/thread/$id/moments/$momentId'
    | '/c/$id/'
    | '/c/$id/join/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/$username'
    | '/mentions'
    | '/notifications'
    | '/search'
    | '/signin'
    | '/signup'
    | '/welcome'
    | '/circle/new'
    | '/moment/new'
    | '/recap/$period'
    | '/thread/new'
    | '/user/account'
    | '/user/notification'
    | '/user/privacy'
    | '/user/threads'
    | '/album'
    | '/circle'
    | '/thread'
    | '/user'
    | '/thread/$id/manage'
    | '/thread/$id'
    | '/c/$id/album'
    | '/c/$id/invite'
    | '/c/$id/member'
    | '/c/$id/settings'
    | '/c/$id/thread'
    | '/thread/$id/moments/$momentId'
    | '/c/$id'
    | '/c/$id/join/$code'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_user'
    | '/about'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/_app/$username'
    | '/_app/_circle'
    | '/_app/mentions'
    | '/_app/notifications'
    | '/_app/search'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_auth/welcome'
    | '/_app/'
    | '/_app/circle/new'
    | '/_app/moment/new'
    | '/_app/recap/$period'
    | '/_app/thread/new'
    | '/_user/user/account'
    | '/_user/user/notification'
    | '/_user/user/privacy'
    | '/_user/user/threads'
    | '/_app/album/'
    | '/_app/circle/'
    | '/_app/thread/'
    | '/_user/user/'
    | '/_app/thread/$id/manage'
    | '/_app/thread/$id/'
    | '/_app/_circle/c/$id/album'
    | '/_app/_circle/c/$id/invite'
    | '/_app/_circle/c/$id/member'
    | '/_app/_circle/c/$id/settings'
    | '/_app/_circle/c/$id/thread'
    | '/_app/thread/$id/moments/$momentId'
    | '/_app/_circle/c/$id/'
    | '/_app/_circle/c/$id/join/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  AboutRoute: typeof AboutRoute
  HelpRoute: typeof HelpRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$username': {
      id: '/_app/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof AppUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_circle': {
      id: '/_app/_circle'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppCircleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mentions': {
      id: '/_app/mentions'
      path: '/mentions'
      fullPath: '/mentions'
      preLoaderRoute: typeof AppMentionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/welcome': {
      id: '/_auth/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthWelcomeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/album/': {
      id: '/_app/album/'
      path: '/album'
      fullPath: '/album/'
      preLoaderRoute: typeof AppAlbumIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/circle/': {
      id: '/_app/circle/'
      path: '/circle'
      fullPath: '/circle/'
      preLoaderRoute: typeof AppCircleIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/circle/new': {
      id: '/_app/circle/new'
      path: '/circle/new'
      fullPath: '/circle/new'
      preLoaderRoute: typeof AppCircleNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/moment/new': {
      id: '/_app/moment/new'
      path: '/moment/new'
      fullPath: '/moment/new'
      preLoaderRoute: typeof AppMomentNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recap/$period': {
      id: '/_app/recap/$period'
      path: '/recap/$period'
      fullPath: '/recap/$period'
      preLoaderRoute: typeof AppRecapPeriodRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/thread/': {
      id: '/_app/thread/'
      path: '/thread'
      fullPath: '/thread/'
      preLoaderRoute: typeof AppThreadIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/thread/new': {
      id: '/_app/thread/new'
      path: '/thread/new'
      fullPath: '/thread/new'
      preLoaderRoute: typeof AppThreadNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_user/user/': {
      id: '/_user/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof UserUserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/user/account': {
      id: '/_user/user/account'
      path: '/user/account'
      fullPath: '/user/account'
      preLoaderRoute: typeof UserUserAccountRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/user/notification': {
      id: '/_user/user/notification'
      path: '/user/notification'
      fullPath: '/user/notification'
      preLoaderRoute: typeof UserUserNotificationRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/user/privacy': {
      id: '/_user/user/privacy'
      path: '/user/privacy'
      fullPath: '/user/privacy'
      preLoaderRoute: typeof UserUserPrivacyRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/user/threads': {
      id: '/_user/user/threads'
      path: '/user/threads'
      fullPath: '/user/threads'
      preLoaderRoute: typeof UserUserThreadsRouteImport
      parentRoute: typeof UserRoute
    }
    '/_app/thread/$id/': {
      id: '/_app/thread/$id/'
      path: '/thread/$id'
      fullPath: '/thread/$id/'
      preLoaderRoute: typeof AppThreadIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/thread/$id/manage': {
      id: '/_app/thread/$id/manage'
      path: '/thread/$id/manage'
      fullPath: '/thread/$id/manage'
      preLoaderRoute: typeof AppThreadIdManageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_circle/c/$id/': {
      id: '/_app/_circle/c/$id/'
      path: '/c/$id'
      fullPath: '/c/$id/'
      preLoaderRoute: typeof AppCircleCIdIndexRouteImport
      parentRoute: typeof AppCircleRoute
    }
    '/_app/_circle/c/$id/album': {
      id: '/_app/_circle/c/$id/album'
      path: '/c/$id/album'
      fullPath: '/c/$id/album'
      preLoaderRoute: typeof AppCircleCIdAlbumRouteImport
      parentRoute: typeof AppCircleRoute
    }
    '/_app/_circle/c/$id/invite': {
      id: '/_app/_circle/c/$id/invite'
      path: '/c/$id/invite'
      fullPath: '/c/$id/invite'
      preLoaderRoute: typeof AppCircleCIdInviteRouteImport
      parentRoute: typeof AppCircleRoute
    }
    '/_app/_circle/c/$id/member': {
      id: '/_app/_circle/c/$id/member'
      path: '/c/$id/member'
      fullPath: '/c/$id/member'
      preLoaderRoute: typeof AppCircleCIdMemberRouteImport
      parentRoute: typeof AppCircleRoute
    }
    '/_app/_circle/c/$id/settings': {
      id: '/_app/_circle/c/$id/settings'
      path: '/c/$id/settings'
      fullPath: '/c/$id/settings'
      preLoaderRoute: typeof AppCircleCIdSettingsRouteImport
      parentRoute: typeof AppCircleRoute
    }
    '/_app/_circle/c/$id/thread': {
      id: '/_app/_circle/c/$id/thread'
      path: '/c/$id/thread'
      fullPath: '/c/$id/thread'
      preLoaderRoute: typeof AppCircleCIdThreadRouteImport
      parentRoute: typeof AppCircleRoute
    }
    '/_app/thread/$id/moments/$momentId': {
      id: '/_app/thread/$id/moments/$momentId'
      path: '/thread/$id/moments/$momentId'
      fullPath: '/thread/$id/moments/$momentId'
      preLoaderRoute: typeof AppThreadIdMomentsMomentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_circle/c/$id/join/$code': {
      id: '/_app/_circle/c/$id/join/$code'
      path: '/c/$id/join/$code'
      fullPath: '/c/$id/join/$code'
      preLoaderRoute: typeof AppCircleCIdJoinCodeRouteImport
      parentRoute: typeof AppCircleRoute
    }
  }
}

interface AppCircleRouteChildren {
  AppCircleCIdAlbumRoute: typeof AppCircleCIdAlbumRoute
  AppCircleCIdInviteRoute: typeof AppCircleCIdInviteRoute
  AppCircleCIdMemberRoute: typeof AppCircleCIdMemberRoute
  AppCircleCIdSettingsRoute: typeof AppCircleCIdSettingsRoute
  AppCircleCIdThreadRoute: typeof AppCircleCIdThreadRoute
  AppCircleCIdIndexRoute: typeof AppCircleCIdIndexRoute
  AppCircleCIdJoinCodeRoute: typeof AppCircleCIdJoinCodeRoute
}

const AppCircleRouteChildren: AppCircleRouteChildren = {
  AppCircleCIdAlbumRoute: AppCircleCIdAlbumRoute,
  AppCircleCIdInviteRoute: AppCircleCIdInviteRoute,
  AppCircleCIdMemberRoute: AppCircleCIdMemberRoute,
  AppCircleCIdSettingsRoute: AppCircleCIdSettingsRoute,
  AppCircleCIdThreadRoute: AppCircleCIdThreadRoute,
  AppCircleCIdIndexRoute: AppCircleCIdIndexRoute,
  AppCircleCIdJoinCodeRoute: AppCircleCIdJoinCodeRoute,
}

const AppCircleRouteWithChildren = AppCircleRoute._addFileChildren(
  AppCircleRouteChildren,
)

interface AppRouteChildren {
  AppUsernameRoute: typeof AppUsernameRoute
  AppCircleRoute: typeof AppCircleRouteWithChildren
  AppMentionsRoute: typeof AppMentionsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCircleNewRoute: typeof AppCircleNewRoute
  AppMomentNewRoute: typeof AppMomentNewRoute
  AppRecapPeriodRoute: typeof AppRecapPeriodRoute
  AppThreadNewRoute: typeof AppThreadNewRoute
  AppAlbumIndexRoute: typeof AppAlbumIndexRoute
  AppCircleIndexRoute: typeof AppCircleIndexRoute
  AppThreadIndexRoute: typeof AppThreadIndexRoute
  AppThreadIdManageRoute: typeof AppThreadIdManageRoute
  AppThreadIdIndexRoute: typeof AppThreadIdIndexRoute
  AppThreadIdMomentsMomentIdRoute: typeof AppThreadIdMomentsMomentIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppUsernameRoute: AppUsernameRoute,
  AppCircleRoute: AppCircleRouteWithChildren,
  AppMentionsRoute: AppMentionsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppCircleNewRoute: AppCircleNewRoute,
  AppMomentNewRoute: AppMomentNewRoute,
  AppRecapPeriodRoute: AppRecapPeriodRoute,
  AppThreadNewRoute: AppThreadNewRoute,
  AppAlbumIndexRoute: AppAlbumIndexRoute,
  AppCircleIndexRoute: AppCircleIndexRoute,
  AppThreadIndexRoute: AppThreadIndexRoute,
  AppThreadIdManageRoute: AppThreadIdManageRoute,
  AppThreadIdIndexRoute: AppThreadIdIndexRoute,
  AppThreadIdMomentsMomentIdRoute: AppThreadIdMomentsMomentIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthWelcomeRoute: typeof AuthWelcomeRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthWelcomeRoute: AuthWelcomeRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface UserRouteChildren {
  UserUserAccountRoute: typeof UserUserAccountRoute
  UserUserNotificationRoute: typeof UserUserNotificationRoute
  UserUserPrivacyRoute: typeof UserUserPrivacyRoute
  UserUserThreadsRoute: typeof UserUserThreadsRoute
  UserUserIndexRoute: typeof UserUserIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserUserAccountRoute: UserUserAccountRoute,
  UserUserNotificationRoute: UserUserNotificationRoute,
  UserUserPrivacyRoute: UserUserPrivacyRoute,
  UserUserThreadsRoute: UserUserThreadsRoute,
  UserUserIndexRoute: UserUserIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  AboutRoute: AboutRoute,
  HelpRoute: HelpRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
