dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName}}.go"
pkgname: "mocks"
packages:
  "github.com/ngodingvareng/memoria/internal/usecase":
    interfaces:
      Storage:

      PasswordHasher:
      TokenGenerator:

      AuthUnitOfWork:

      ActivityRepository:
      ActivityImageRepository:
      UserRepository:
      UserAccountRepository:
      UserSessionRepository:
