dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName}}.go"
pkgname: "mocks"
packages:
  "github.com/ngodingvareng/memoria/internal/usecase":
    interfaces:
      Storage:

      PasswordHasher:
      AccessTokenIssuer:
      RefreshTokenGenerator:

      AuthUnitOfWork:

      ActivityRepository:
      ActivityImageRepository:
      UserRepository:
      UserAccountRepository:
      RefreshTokenRepository:

      ActivityAccessChecker:
