name: API test

on:
  push:
    branches: ["main"]
    paths:
      - 'api/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'api/**'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.5"
          cache: true
          cache-dependency-path: api/go.sum

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: go test -tags=unit ./... -v

      - name: Run integration tests
        run: go test -tags=integration ./... -v
